/* content_generated.h — AUTO-GENERATED from data/content JSON files.
 * Do not edit manually. Run: python3 scripts/gen_content.py
 * Content translation arrays for content_i18n.c. */

#ifndef TIME_CONTENT_GENERATED_H
#define TIME_CONTENT_GENERATED_H

#include "i18n.h"

/* ---- EN (253 keys, canonical) ---- */

static const i18n_entry_t gen_content_en[] = {
    { "astronomy.phase.0.brief", "The dark seed \xe2\x80\x94 invisible, full of potential, everything begins here" },
    { "astronomy.phase.0.guidance", "Set intentions, start projects, rest and reflect in the darkness" },
    { "astronomy.phase.0.name", "New Moon" },
    { "astronomy.phase.0.theme", "Beginnings, seed planting, intention setting, the dark of renewal" },
    { "astronomy.phase.1.brief", "The first sliver \xe2\x80\x94 intention made visible, the young light gathering strength" },
    { "astronomy.phase.1.guidance", "Take the first step, gather resources, push through initial resistance" },
    { "astronomy.phase.1.name", "Waxing Crescent" },
    { "astronomy.phase.1.theme", "Emerging intention, first commitment, the courage to begin" },
    { "astronomy.phase.2.brief", "The half-lit choice \xe2\x80\x94 light and dark in equal measure, the crossroads" },
    { "astronomy.phase.2.guidance", "Make decisions, overcome obstacles, commit to the direction chosen" },
    { "astronomy.phase.2.name", "First Quarter" },
    { "astronomy.phase.2.theme", "Challenge, decision, the crisis of action" },
    { "astronomy.phase.3.brief", "Almost full \xe2\x80\x94 the final preparation, polishing before the peak" },
    { "astronomy.phase.3.guidance", "Refine the plan, adjust based on feedback, trust the process" },
    { "astronomy.phase.3.name", "Waxing Gibbous" },
    { "astronomy.phase.3.theme", "Refinement, adjustment, patience before fulfillment" },
    { "astronomy.phase.4.brief", "The full light \xe2\x80\x94 everything illuminated, nothing hidden, the peak" },
    { "astronomy.phase.4.guidance", "Celebrate completion, see clearly, harvest what was planted at the new moon" },
    { "astronomy.phase.4.name", "Full Moon" },
    { "astronomy.phase.4.theme", "Culmination, illumination, harvest, revelation" },
    { "astronomy.phase.5.brief", "The generous decline \xe2\x80\x94 the light begins to give itself away" },
    { "astronomy.phase.5.guidance", "Share what you have learned, give back, express gratitude for the harvest" },
    { "astronomy.phase.5.name", "Waning Gibbous" },
    { "astronomy.phase.5.theme", "Gratitude, sharing, teaching, distribution" },
    { "astronomy.phase.6.brief", "The half-lit release \xe2\x80\x94 light and dark again equal, but now the light is leaving" },
    { "astronomy.phase.6.guidance", "Let go of what no longer serves, forgive, clear space for the new" },
    { "astronomy.phase.6.name", "Last Quarter" },
    { "astronomy.phase.6.theme", "Release, forgiveness, clearing, the crisis of letting go" },
    { "astronomy.phase.7.brief", "The last whisper \xe2\x80\x94 the thinnest light before the dark, the wisdom of surrender" },
    { "astronomy.phase.7.guidance", "Rest deeply, surrender control, prepare for the coming darkness" },
    { "astronomy.phase.7.name", "Waning Crescent" },
    { "astronomy.phase.7.theme", "Surrender, rest, preparation for the void, the balsamic phase" },
    { "astronomy.planet.0.archetype", "The Trickster-Messenger \xe2\x80\x94 quicksilver mind, the psychopomp who bridges realms" },
    { "astronomy.planet.0.brief", "The swift messenger \xe2\x80\x94 closest to the Sun, never far from the source of light" },
    { "astronomy.planet.0.deity", "Hermes / Nabu / Thoth" },
    { "astronomy.planet.0.domain", "Communication, intellect, commerce, the messenger between worlds" },
    { "astronomy.planet.0.name", "Mercury" },
    { "astronomy.planet.1.archetype", "The Beloved \xe2\x80\x94 the mirror of desire, beauty as a force that civilizes" },
    { "astronomy.planet.1.brief", "The morning and evening star \xe2\x80\x94 the brightest planet, whose light is borrowed" },
    { "astronomy.planet.1.deity", "Aphrodite / Ishtar / Freya" },
    { "astronomy.planet.1.domain", "Love, beauty, harmony, values, artistic creation" },
    { "astronomy.planet.1.name", "Venus" },
    { "astronomy.planet.2.archetype", "The Mother \xe2\x80\x94 the living world that sustains all observation of the cosmos" },
    { "astronomy.planet.2.brief", "The pale blue dot \xe2\x80\x94 the only planet we know that looks back at the sky" },
    { "astronomy.planet.2.deity", "Gaia / Terra / Jord" },
    { "astronomy.planet.2.domain", "Home, embodiment, the body, the ground we stand on" },
    { "astronomy.planet.2.name", "Earth" },
    { "astronomy.planet.3.archetype", "The Warrior \xe2\x80\x94 the red force that fights for what matters" },
    { "astronomy.planet.3.brief", "The red planet \xe2\x80\x94 iron-rusted, blood-colored, named for the god of war" },
    { "astronomy.planet.3.deity", "Ares / Nergal / Tyr" },
    { "astronomy.planet.3.domain", "Action, drive, conflict, courage, the will to assert" },
    { "astronomy.planet.3.name", "Mars" },
    { "astronomy.planet.4.archetype", "The King \xe2\x80\x94 the largest body in the solar system after the Sun, protector and judge" },
    { "astronomy.planet.4.brief", "The great benefic \xe2\x80\x94 more massive than all other planets combined" },
    { "astronomy.planet.4.deity", "Zeus / Marduk / Thor" },
    { "astronomy.planet.4.domain", "Expansion, wisdom, generosity, law, the great benefic" },
    { "astronomy.planet.4.name", "Jupiter" },
    { "astronomy.planet.5.archetype", "The Elder \xe2\x80\x94 the ringed boundary, the lesson that cannot be avoided" },
    { "astronomy.planet.5.brief", "The ringed teacher \xe2\x80\x94 beautiful and severe, the lord of time and consequence" },
    { "astronomy.planet.5.deity", "Kronos / Ninurta / Loki" },
    { "astronomy.planet.5.domain", "Structure, limitation, time, discipline, the great teacher" },
    { "astronomy.planet.5.name", "Saturn" },
    { "astronomy.planet.6.archetype", "The Awakener \xe2\x80\x94 the lightning bolt of change, the force that disrupts to liberate" },
    { "astronomy.planet.6.brief", "The tilted rebel \xe2\x80\x94 rolling on its side, the planet that breaks every rule" },
    { "astronomy.planet.6.deity", "Ouranos / sky father" },
    { "astronomy.planet.6.domain", "Revolution, originality, sudden insight, the unexpected" },
    { "astronomy.planet.6.name", "Uranus" },
    { "astronomy.planet.7.archetype", "The Mystic \xe2\x80\x94 the dissolving ocean where boundaries cease to exist" },
    { "astronomy.planet.7.brief", "The blue dreamer \xe2\x80\x94 farthest major planet, where the solar system fades into mystery" },
    { "astronomy.planet.7.deity", "Poseidon / Ea / Njord" },
    { "astronomy.planet.7.domain", "Imagination, transcendence, illusion, the oceanic unconscious" },
    { "astronomy.planet.7.name", "Neptune" },
    { "astronomy.tpl.detail_moon", " Moon: %1$s \xe2\x80\x94 %2$s." },
    { "astronomy.tpl.detail_planet", "Planet: %1$s. Deity: %2$s. Domain: %3$s. %4$s." },
    { "astronomy.tpl.detail_retro", " RETROGRADE: apparent backward motion \xe2\x80\x94 the planet's themes turn inward for review." },
    { "astronomy.tpl.glance", "%1$s \xe2\x80\x94 %2$s" },
    { "astronomy.tpl.glance_moon", "%1$s \xe2\x80\x94 %2$s + %3$s" },
    { "astronomy.tpl.glance_retro", "%1$s (retrograde) \xe2\x80\x94 %2$s" },
    { "gregorian.day.0.brief", "The Moon's day \xe2\x80\x94 intuition, emotion, the tides within" },
    { "gregorian.day.0.name", "Monday" },
    { "gregorian.day.0.origin", "Old English Monandaeg (Moon's day)" },
    { "gregorian.day.0.planet", "Moon" },
    { "gregorian.day.1.brief", "Mars' day \xe2\x80\x94 courage, action, the warrior's resolve" },
    { "gregorian.day.1.name", "Tuesday" },
    { "gregorian.day.1.origin", "Old English Tiwesdaeg (Tyr's day, Norse Mars)" },
    { "gregorian.day.1.planet", "Mars" },
    { "gregorian.day.2.brief", "Mercury's day \xe2\x80\x94 communication, craft, the trickster's wit" },
    { "gregorian.day.2.name", "Wednesday" },
    { "gregorian.day.2.origin", "Old English Wodnesdaeg (Woden's day, Norse Mercury)" },
    { "gregorian.day.2.planet", "Mercury" },
    { "gregorian.day.3.brief", "Jupiter's day \xe2\x80\x94 expansion, abundance, the thunder god's generosity" },
    { "gregorian.day.3.name", "Thursday" },
    { "gregorian.day.3.origin", "Old English Thunresdaeg (Thor's day, Norse Jupiter)" },
    { "gregorian.day.3.planet", "Jupiter" },
    { "gregorian.day.4.brief", "Venus' day \xe2\x80\x94 love, beauty, the goddess of desire" },
    { "gregorian.day.4.name", "Friday" },
    { "gregorian.day.4.origin", "Old English Frigedaeg (Freya's day, Norse Venus)" },
    { "gregorian.day.4.planet", "Venus" },
    { "gregorian.day.5.brief", "Saturn's day \xe2\x80\x94 discipline, structure, the taskmaster's lesson" },
    { "gregorian.day.5.name", "Saturday" },
    { "gregorian.day.5.origin", "Latin Saturni dies (Saturn's day)" },
    { "gregorian.day.5.planet", "Saturn" },
    { "gregorian.day.6.brief", "The Sun's day \xe2\x80\x94 vitality, sovereignty, the center of all orbits" },
    { "gregorian.day.6.name", "Sunday" },
    { "gregorian.day.6.origin", "Old English Sunnandaeg (Sun's day)" },
    { "gregorian.day.6.planet", "Sun" },
    { "gregorian.month.1.brief", "The month of doorways \xe2\x80\x94 one face looks back, one looks forward" },
    { "gregorian.month.1.name", "January" },
    { "gregorian.month.1.origin", "Janus \xe2\x80\x94 two-faced god of beginnings, gates, and transitions" },
    { "gregorian.month.1.quality", "Deep winter, reflection, fresh starts" },
    { "gregorian.month.10.brief", "The eighth month \xe2\x80\x94 the world turns inward as the light contracts" },
    { "gregorian.month.10.name", "October" },
    { "gregorian.month.10.origin", "Octo (eight) \xe2\x80\x94 the eighth month of the old Roman calendar" },
    { "gregorian.month.10.quality", "Mid-autumn, deepening, transformation" },
    { "gregorian.month.11.brief", "The ninth month \xe2\x80\x94 the dead are honored as the year grows old" },
    { "gregorian.month.11.name", "November" },
    { "gregorian.month.11.origin", "Novem (nine) \xe2\x80\x94 the ninth month of the old Roman calendar" },
    { "gregorian.month.11.quality", "Late autumn, remembrance, preparation for dark" },
    { "gregorian.month.12.brief", "The tenth month \xe2\x80\x94 in the deepest dark, the ancient Romans feasted and the sun was reborn" },
    { "gregorian.month.12.name", "December" },
    { "gregorian.month.12.origin", "Decem (ten) \xe2\x80\x94 the tenth month of the old Roman calendar" },
    { "gregorian.month.12.quality", "Winter solstice, Saturnalia, the return of light" },
    { "gregorian.month.2.brief", "The month of cleansing \xe2\x80\x94 the last fires of purification before new growth" },
    { "gregorian.month.2.name", "February" },
    { "gregorian.month.2.origin", "Februa \xe2\x80\x94 Roman purification festival (Lupercalia)" },
    { "gregorian.month.2.quality", "Late winter, purification, preparation for spring" },
    { "gregorian.month.3.brief", "The month of Mars \xe2\x80\x94 the old Roman year began here, with war and planting alike" },
    { "gregorian.month.3.name", "March" },
    { "gregorian.month.3.origin", "Mars \xe2\x80\x94 god of war and agriculture, the Roman new year" },
    { "gregorian.month.3.quality", "Spring equinox, awakening, aggressive new growth" },
    { "gregorian.month.4.brief", "The month of opening \xe2\x80\x94 everything that was closed begins to unfold" },
    { "gregorian.month.4.name", "April" },
    { "gregorian.month.4.origin", "Aperire (to open) \xe2\x80\x94 the earth opens, buds unfold" },
    { "gregorian.month.4.quality", "Full spring, opening, blossoming" },
    { "gregorian.month.5.brief", "The month of growth \xe2\x80\x94 the earth goddess whose name means 'she who is great'" },
    { "gregorian.month.5.name", "May" },
    { "gregorian.month.5.origin", "Maia \xe2\x80\x94 goddess of growth, mother of Mercury" },
    { "gregorian.month.5.quality", "Late spring, fertility, abundance beginning" },
    { "gregorian.month.6.brief", "The month of marriage \xe2\x80\x94 the queen of heaven blesses the longest days" },
    { "gregorian.month.6.name", "June" },
    { "gregorian.month.6.origin", "Juno \xe2\x80\x94 queen of the gods, patron of marriage" },
    { "gregorian.month.6.quality", "Summer solstice, union, peak daylight" },
    { "gregorian.month.7.brief", "The month of Caesar \xe2\x80\x94 named for the man who remade time itself" },
    { "gregorian.month.7.name", "July" },
    { "gregorian.month.7.origin", "Julius Caesar \xe2\x80\x94 reformed the calendar, deified after death" },
    { "gregorian.month.7.quality", "High summer, power, radiance" },
    { "gregorian.month.8.brief", "The month of Augustus \xe2\x80\x94 the emperor who demanded a month as grand as July" },
    { "gregorian.month.8.name", "August" },
    { "gregorian.month.8.origin", "Augustus Caesar \xe2\x80\x94 first Roman emperor, 'the revered one'" },
    { "gregorian.month.8.quality", "Late summer, harvest begins, empire at zenith" },
    { "gregorian.month.9.brief", "The seventh month \xe2\x80\x94 still carrying its old number though it is now the ninth" },
    { "gregorian.month.9.name", "September" },
    { "gregorian.month.9.origin", "Septem (seven) \xe2\x80\x94 the seventh month of the old Roman calendar" },
    { "gregorian.month.9.quality", "Autumn equinox, balance, gathering in" },
    { "gregorian.season.0.brief", "The season of becoming \xe2\x80\x94 everything that slept now wakes" },
    { "gregorian.season.0.name", "Spring" },
    { "gregorian.season.0.quality", "Expansive \xe2\x80\x94 energy rises, seeds germinate, days lengthen" },
    { "gregorian.season.0.theme", "Rebirth, growth, potential becoming actual" },
    { "gregorian.season.1.brief", "The season of being \xe2\x80\x94 the world at maximum brilliance" },
    { "gregorian.season.1.name", "Summer" },
    { "gregorian.season.1.quality", "Radiant \xe2\x80\x94 energy at peak, light dominates, life in full bloom" },
    { "gregorian.season.1.theme", "Fullness, radiance, maximum expression" },
    { "gregorian.season.2.brief", "The season of letting go \xe2\x80\x94 beauty in decay, richness in release" },
    { "gregorian.season.2.name", "Autumn" },
    { "gregorian.season.2.quality", "Contracting \xe2\x80\x94 energy turns inward, fruit ripens, leaves fall" },
    { "gregorian.season.2.theme", "Harvest, release, gratitude for what grew" },
    { "gregorian.season.3.brief", "The season of rest \xe2\x80\x94 what appears dead is dreaming" },
    { "gregorian.season.3.name", "Winter" },
    { "gregorian.season.3.quality", "Still \xe2\x80\x94 energy withdrawn to roots, silence, gestation in darkness" },
    { "gregorian.season.3.theme", "Rest, depth, the hidden seed, essential stillness" },
    { "gregorian.tpl.detail", "%1$s: %2$s. %3$s. Season: %4$s \xe2\x80\x94 %5$s. %6$s (%7$s): %8$s." },
    { "gregorian.tpl.glance", "%1$s %2$d (%3$s) \xe2\x80\x94 %4$s" },
    { "hebrew.month.1.brief", "Month of miracles and liberation \xe2\x80\x94 Passover" },
    { "hebrew.month.1.letter", "Hei" },
    { "hebrew.month.1.name", "Nisan" },
    { "hebrew.month.1.quality", "Redemption" },
    { "hebrew.month.1.sense", "Speech" },
    { "hebrew.month.1.tribe", "Judah" },
    { "hebrew.month.10.brief", "The darkest month \xe2\x80\x94 righteous indignation" },
    { "hebrew.month.10.letter", "Ayin" },
    { "hebrew.month.10.name", "Tevet" },
    { "hebrew.month.10.quality", "Transformation" },
    { "hebrew.month.10.sense", "Anger (righteous)" },
    { "hebrew.month.10.tribe", "Dan" },
    { "hebrew.month.11.brief", "New Year of Trees \xe2\x80\x94 Tu B'Shevat" },
    { "hebrew.month.11.letter", "Tzadi" },
    { "hebrew.month.11.name", "Shevat" },
    { "hebrew.month.11.quality", "Renewal" },
    { "hebrew.month.11.sense", "Taste" },
    { "hebrew.month.11.tribe", "Asher" },
    { "hebrew.month.12.brief", "Month of Purim \xe2\x80\x94 hidden miracles revealed" },
    { "hebrew.month.12.letter", "Qof" },
    { "hebrew.month.12.name", "Adar" },
    { "hebrew.month.12.quality", "Joy and reversal" },
    { "hebrew.month.12.sense", "Laughter" },
    { "hebrew.month.12.tribe", "Naphtali" },
    { "hebrew.month.13.brief", "Leap month \xe2\x80\x94 Purim celebrated here in leap years" },
    { "hebrew.month.13.letter", "Qof" },
    { "hebrew.month.13.name", "Adar II" },
    { "hebrew.month.13.quality", "Joy doubled" },
    { "hebrew.month.13.sense", "Laughter" },
    { "hebrew.month.13.tribe", "Naphtali" },
    { "hebrew.month.2.brief", "Month of natural healing \xe2\x80\x94 counting the Omer" },
    { "hebrew.month.2.letter", "Vav" },
    { "hebrew.month.2.name", "Iyar" },
    { "hebrew.month.2.quality", "Healing" },
    { "hebrew.month.2.sense", "Thought" },
    { "hebrew.month.2.tribe", "Issachar" },
    { "hebrew.month.3.brief", "Month of Torah giving \xe2\x80\x94 Shavuot" },
    { "hebrew.month.3.letter", "Zayin" },
    { "hebrew.month.3.name", "Sivan" },
    { "hebrew.month.3.quality", "Revelation" },
    { "hebrew.month.3.sense", "Motion" },
    { "hebrew.month.3.tribe", "Zebulun" },
    { "hebrew.month.4.brief", "Month of the broken tablets \xe2\x80\x94 seeing beyond" },
    { "hebrew.month.4.letter", "Chet" },
    { "hebrew.month.4.name", "Tammuz" },
    { "hebrew.month.4.quality", "Vision through darkness" },
    { "hebrew.month.4.sense", "Sight" },
    { "hebrew.month.4.tribe", "Reuben" },
    { "hebrew.month.5.brief", "Month of destruction and consolation" },
    { "hebrew.month.5.letter", "Tet" },
    { "hebrew.month.5.name", "Av" },
    { "hebrew.month.5.quality", "Transformation of sorrow" },
    { "hebrew.month.5.sense", "Hearing" },
    { "hebrew.month.5.tribe", "Simeon" },
    { "hebrew.month.6.brief", "Month of returning \xe2\x80\x94 preparation for the new year" },
    { "hebrew.month.6.letter", "Yod" },
    { "hebrew.month.6.name", "Elul" },
    { "hebrew.month.6.quality", "Repentance" },
    { "hebrew.month.6.sense", "Action" },
    { "hebrew.month.6.tribe", "Gad" },
    { "hebrew.month.7.brief", "Month of the High Holidays \xe2\x80\x94 Rosh Hashanah, Yom Kippur, Sukkot" },
    { "hebrew.month.7.letter", "Lamed" },
    { "hebrew.month.7.name", "Tishrei" },
    { "hebrew.month.7.quality", "Awe and judgment" },
    { "hebrew.month.7.sense", "Touch" },
    { "hebrew.month.7.tribe", "Ephraim" },
    { "hebrew.month.8.brief", "The bitter month \xe2\x80\x94 no holidays, only rain prayers" },
    { "hebrew.month.8.letter", "Nun" },
    { "hebrew.month.8.name", "Cheshvan" },
    { "hebrew.month.8.quality", "Quiet depth" },
    { "hebrew.month.8.sense", "Smell" },
    { "hebrew.month.8.tribe", "Manasseh" },
    { "hebrew.month.9.brief", "Month of dreams and lights \xe2\x80\x94 Hanukkah" },
    { "hebrew.month.9.letter", "Samekh" },
    { "hebrew.month.9.name", "Kislev" },
    { "hebrew.month.9.quality", "Trust and miracles" },
    { "hebrew.month.9.sense", "Sleep" },
    { "hebrew.month.9.tribe", "Benjamin" },
    { "hebrew.tpl.detail", "%1$s is the month of %2$s. Its letter is %3$s, its tribe is %4$s, its sense is %5$s. %6$s." },
    { "hebrew.tpl.glance", "%1$d %2$s %3$d \xe2\x80\x94 %4$s" },
    { "hebrew.tpl.sabbatical", " Shemitah year %1$d of 7." },
};

#define GEN_CONTENT_EN_COUNT \
    ((int)(sizeof(gen_content_en) / sizeof(gen_content_en[0])))

/* ---- ES (253 keys) ---- */

static const i18n_entry_t gen_content_es[] = {
    { "astronomy.phase.0.brief", "La semilla oscura \xe2\x80\x94 invisible, llena de potencial, todo comienza aqu\xc3\xad" },
    { "astronomy.phase.0.guidance", "Establece intenciones, inicia proyectos, descansa y reflexiona en la oscuridad" },
    { "astronomy.phase.0.name", "Luna Nueva" },
    { "astronomy.phase.0.theme", "Comienzos, siembra, intenci\xc3\xb3n, la oscuridad de la renovaci\xc3\xb3n" },
    { "astronomy.phase.1.brief", "La primera franja \xe2\x80\x94 la intenci\xc3\xb3n hecha visible, la joven luz ganando fuerza" },
    { "astronomy.phase.1.guidance", "Da el primer paso, re\xc3\xbane recursos, supera la resistencia inicial" },
    { "astronomy.phase.1.name", "Creciente" },
    { "astronomy.phase.1.theme", "Intenci\xc3\xb3n emergente, primer compromiso, el coraje de comenzar" },
    { "astronomy.phase.2.brief", "La elecci\xc3\xb3n a media luz \xe2\x80\x94 luz y oscuridad en igual medida, la encrucijada" },
    { "astronomy.phase.2.guidance", "Toma decisiones, supera obst\xc3\xa1" "culos, compr\xc3\xb3metete con la direcci\xc3\xb3n elegida" },
    { "astronomy.phase.2.name", "Cuarto Creciente" },
    { "astronomy.phase.2.theme", "Desaf\xc3\xado, decisi\xc3\xb3n, la crisis de la acci\xc3\xb3n" },
    { "astronomy.phase.3.brief", "Casi llena \xe2\x80\x94 la preparaci\xc3\xb3n final, puliendo antes del apogeo" },
    { "astronomy.phase.3.guidance", "Refina el plan, aj\xc3\xbastalo seg\xc3\xban la retroalimentaci\xc3\xb3n, conf\xc3\xad" "a en el proceso" },
    { "astronomy.phase.3.name", "Gibosa Creciente" },
    { "astronomy.phase.3.theme", "Refinamiento, ajuste, paciencia antes de la plenitud" },
    { "astronomy.phase.4.brief", "La luz plena \xe2\x80\x94 todo iluminado, nada oculto, el apogeo" },
    { "astronomy.phase.4.guidance", "Celebra la completud, mira con claridad, cosecha lo sembrado en luna nueva" },
    { "astronomy.phase.4.name", "Luna Llena" },
    { "astronomy.phase.4.theme", "Culminaci\xc3\xb3n, iluminaci\xc3\xb3n, cosecha, revelaci\xc3\xb3n" },
    { "astronomy.phase.5.brief", "El generoso declive \xe2\x80\x94 la luz comienza a entregarse" },
    { "astronomy.phase.5.guidance", "Comparte lo aprendido, retribuye, expresa gratitud por la cosecha" },
    { "astronomy.phase.5.name", "Gibosa Menguante" },
    { "astronomy.phase.5.theme", "Gratitud, compartir, ense\xc3\xb1" "ar, distribuci\xc3\xb3n" },
    { "astronomy.phase.6.brief", "La liberaci\xc3\xb3n a media luz \xe2\x80\x94 luz y oscuridad iguales, pero ahora la luz se va" },
    { "astronomy.phase.6.guidance", "Suelta lo que ya no sirve, perdona, abre espacio para lo nuevo" },
    { "astronomy.phase.6.name", "\xc3\x9altimo Cuarto" },
    { "astronomy.phase.6.theme", "Liberaci\xc3\xb3n, perd\xc3\xb3n, limpieza, la crisis de soltar" },
    { "astronomy.phase.7.brief", "El \xc3\xbaltimo susurro \xe2\x80\x94 la luz m\xc3\xa1s tenue antes de la oscuridad, la sabidur\xc3\xad" "a de rendirse" },
    { "astronomy.phase.7.guidance", "Descansa profundamente, entrega el control, prep\xc3\xa1rate para la oscuridad" },
    { "astronomy.phase.7.name", "Menguante" },
    { "astronomy.phase.7.theme", "Rendici\xc3\xb3n, descanso, preparaci\xc3\xb3n para el vac\xc3\xado, la fase bals\xc3\xa1mica" },
    { "astronomy.planet.0.archetype", "El Tramposo-Mensajero \xe2\x80\x94 mente de mercurio, el psicopompo que une reinos" },
    { "astronomy.planet.0.brief", "El veloz mensajero \xe2\x80\x94 el m\xc3\xa1s cercano al Sol, nunca lejos de la fuente de luz" },
    { "astronomy.planet.0.deity", "Hermes / Nabu / Thoth" },
    { "astronomy.planet.0.domain", "Comunicaci\xc3\xb3n, intelecto, comercio, el mensajero entre mundos" },
    { "astronomy.planet.0.name", "Mercurio" },
    { "astronomy.planet.1.archetype", "La Amada \xe2\x80\x94 el espejo del deseo, la belleza como fuerza civilizadora" },
    { "astronomy.planet.1.brief", "La estrella de la ma\xc3\xb1" "ana y la tarde \xe2\x80\x94 el planeta m\xc3\xa1s brillante, cuya luz es prestada" },
    { "astronomy.planet.1.deity", "Afrodita / Ishtar / Freya" },
    { "astronomy.planet.1.domain", "Amor, belleza, armon\xc3\xad" "a, valores, creaci\xc3\xb3n art\xc3\xadstica" },
    { "astronomy.planet.1.name", "Venus" },
    { "astronomy.planet.2.archetype", "La Madre \xe2\x80\x94 el mundo vivo que sustenta toda observaci\xc3\xb3n del cosmos" },
    { "astronomy.planet.2.brief", "El punto azul p\xc3\xa1lido \xe2\x80\x94 el \xc3\xbanico planeta que sabemos mira de vuelta al cielo" },
    { "astronomy.planet.2.deity", "Gaia / Terra / Jord" },
    { "astronomy.planet.2.domain", "Hogar, encarnaci\xc3\xb3n, el cuerpo, el suelo que pisamos" },
    { "astronomy.planet.2.name", "Tierra" },
    { "astronomy.planet.3.archetype", "El Guerrero \xe2\x80\x94 la fuerza roja que lucha por lo que importa" },
    { "astronomy.planet.3.brief", "El planeta rojo \xe2\x80\x94 oxidado, color sangre, nombrado por el dios de la guerra" },
    { "astronomy.planet.3.deity", "Ares / Nergal / Tyr" },
    { "astronomy.planet.3.domain", "Acci\xc3\xb3n, \xc3\xadmpetu, conflicto, coraje, la voluntad de afirmar" },
    { "astronomy.planet.3.name", "Marte" },
    { "astronomy.planet.4.archetype", "El Rey \xe2\x80\x94 el cuerpo m\xc3\xa1s grande del sistema solar despu\xc3\xa9s del Sol, protector y juez" },
    { "astronomy.planet.4.brief", "El gran ben\xc3\xa9" "fico \xe2\x80\x94 m\xc3\xa1s masivo que todos los dem\xc3\xa1s planetas juntos" },
    { "astronomy.planet.4.deity", "Zeus / Marduk / Thor" },
    { "astronomy.planet.4.domain", "Expansi\xc3\xb3n, sabidur\xc3\xad" "a, generosidad, ley, el gran ben\xc3\xa9" "fico" },
    { "astronomy.planet.4.name", "J\xc3\xbapiter" },
    { "astronomy.planet.5.archetype", "El Anciano \xe2\x80\x94 el l\xc3\xadmite anillado, la lecci\xc3\xb3n que no puede evitarse" },
    { "astronomy.planet.5.brief", "El maestro anillado \xe2\x80\x94 bello y severo, el se\xc3\xb1or del tiempo y las consecuencias" },
    { "astronomy.planet.5.deity", "Kronos / Ninurta / Loki" },
    { "astronomy.planet.5.domain", "Estructura, limitaci\xc3\xb3n, tiempo, disciplina, el gran maestro" },
    { "astronomy.planet.5.name", "Saturno" },
    { "astronomy.planet.6.archetype", "El Despertador \xe2\x80\x94 el rayo del cambio, la fuerza que perturba para liberar" },
    { "astronomy.planet.6.brief", "El rebelde inclinado \xe2\x80\x94 rodando de lado, el planeta que rompe toda regla" },
    { "astronomy.planet.6.deity", "Ouranos / padre celeste" },
    { "astronomy.planet.6.domain", "Revoluci\xc3\xb3n, originalidad, intuici\xc3\xb3n s\xc3\xba" "bita, lo inesperado" },
    { "astronomy.planet.6.name", "Urano" },
    { "astronomy.planet.7.archetype", "El M\xc3\xadstico \xe2\x80\x94 el oc\xc3\xa9" "ano disolvente donde los l\xc3\xadmites dejan de existir" },
    { "astronomy.planet.7.brief", "El so\xc3\xb1" "ador azul \xe2\x80\x94 el planeta mayor m\xc3\xa1s lejano, donde el sistema solar se desvanece en misterio" },
    { "astronomy.planet.7.deity", "Poseid\xc3\xb3n / Ea / Njord" },
    { "astronomy.planet.7.domain", "Imaginaci\xc3\xb3n, trascendencia, ilusi\xc3\xb3n, el inconsciente oce\xc3\xa1nico" },
    { "astronomy.planet.7.name", "Neptuno" },
    { "astronomy.tpl.detail_moon", " Luna: %1$s \xe2\x80\x94 %2$s." },
    { "astronomy.tpl.detail_planet", "Planeta: %1$s. Deidad: %2$s. Dominio: %3$s. %4$s." },
    { "astronomy.tpl.detail_retro", " RETR\xc3\x93GRADO: movimiento aparente hacia atr\xc3\xa1s \xe2\x80\x94 los temas del planeta se vuelven hacia adentro para revisi\xc3\xb3n." },
    { "astronomy.tpl.glance", "%1$s \xe2\x80\x94 %2$s" },
    { "astronomy.tpl.glance_moon", "%1$s \xe2\x80\x94 %2$s + %3$s" },
    { "astronomy.tpl.glance_retro", "%1$s (retr\xc3\xb3grado) \xe2\x80\x94 %2$s" },
    { "gregorian.day.0.brief", "El d\xc3\xad" "a de la Luna \xe2\x80\x94 intuici\xc3\xb3n, emoci\xc3\xb3n, las mareas interiores" },
    { "gregorian.day.0.name", "Lunes" },
    { "gregorian.day.0.origin", "Del lat\xc3\xadn Lunae dies (d\xc3\xad" "a de la Luna)" },
    { "gregorian.day.0.planet", "Luna" },
    { "gregorian.day.1.brief", "El d\xc3\xad" "a de Marte \xe2\x80\x94 coraje, acci\xc3\xb3n, la determinaci\xc3\xb3n del guerrero" },
    { "gregorian.day.1.name", "Martes" },
    { "gregorian.day.1.origin", "Del lat\xc3\xadn Martis dies (d\xc3\xad" "a de Marte)" },
    { "gregorian.day.1.planet", "Marte" },
    { "gregorian.day.2.brief", "El d\xc3\xad" "a de Mercurio \xe2\x80\x94 comunicaci\xc3\xb3n, ingenio, la astucia del mensajero" },
    { "gregorian.day.2.name", "Mi\xc3\xa9rcoles" },
    { "gregorian.day.2.origin", "Del lat\xc3\xadn Mercurii dies (d\xc3\xad" "a de Mercurio)" },
    { "gregorian.day.2.planet", "Mercurio" },
    { "gregorian.day.3.brief", "El d\xc3\xad" "a de J\xc3\xbapiter \xe2\x80\x94 expansi\xc3\xb3n, abundancia, la generosidad del trueno" },
    { "gregorian.day.3.name", "Jueves" },
    { "gregorian.day.3.origin", "Del lat\xc3\xadn Iovis dies (d\xc3\xad" "a de J\xc3\xbapiter)" },
    { "gregorian.day.3.planet", "J\xc3\xbapiter" },
    { "gregorian.day.4.brief", "El d\xc3\xad" "a de Venus \xe2\x80\x94 amor, belleza, la diosa del deseo" },
    { "gregorian.day.4.name", "Viernes" },
    { "gregorian.day.4.origin", "Del lat\xc3\xadn Veneris dies (d\xc3\xad" "a de Venus)" },
    { "gregorian.day.4.planet", "Venus" },
    { "gregorian.day.5.brief", "El d\xc3\xad" "a de Saturno \xe2\x80\x94 disciplina, estructura, la lecci\xc3\xb3n del maestro" },
    { "gregorian.day.5.name", "S\xc3\xa1" "bado" },
    { "gregorian.day.5.origin", "Del lat\xc3\xadn Sabbatum (d\xc3\xad" "a de descanso)" },
    { "gregorian.day.5.planet", "Saturno" },
    { "gregorian.day.6.brief", "El d\xc3\xad" "a del Sol \xe2\x80\x94 vitalidad, soberan\xc3\xad" "a, el centro de todas las \xc3\xb3rbitas" },
    { "gregorian.day.6.name", "Domingo" },
    { "gregorian.day.6.origin", "Del lat\xc3\xadn Dominicus dies (d\xc3\xad" "a del Se\xc3\xb1or)" },
    { "gregorian.day.6.planet", "Sol" },
    { "gregorian.month.1.brief", "El mes de las puertas \xe2\x80\x94 un rostro mira hacia atr\xc3\xa1s, otro hacia adelante" },
    { "gregorian.month.1.name", "Enero" },
    { "gregorian.month.1.origin", "Janus \xe2\x80\x94 dios bifronte de los comienzos, los umbrales y las transiciones" },
    { "gregorian.month.1.quality", "Pleno invierno, reflexi\xc3\xb3n, nuevos comienzos" },
    { "gregorian.month.10.brief", "El octavo mes \xe2\x80\x94 el mundo se recoge mientras la luz se contrae" },
    { "gregorian.month.10.name", "Octubre" },
    { "gregorian.month.10.origin", "Octo (ocho) \xe2\x80\x94 el octavo mes del antiguo calendario romano" },
    { "gregorian.month.10.quality", "Mediados de oto\xc3\xb1o, profundizaci\xc3\xb3n, transformaci\xc3\xb3n" },
    { "gregorian.month.11.brief", "El noveno mes \xe2\x80\x94 se honra a los muertos mientras el a\xc3\xb1o envejece" },
    { "gregorian.month.11.name", "Noviembre" },
    { "gregorian.month.11.origin", "Novem (nueve) \xe2\x80\x94 el noveno mes del antiguo calendario romano" },
    { "gregorian.month.11.quality", "Fin de oto\xc3\xb1o, memoria, preparaci\xc3\xb3n para la oscuridad" },
    { "gregorian.month.12.brief", "El d\xc3\xa9" "cimo mes \xe2\x80\x94 en la oscuridad m\xc3\xa1s profunda, los romanos festejaban y el sol renac\xc3\xad" "a" },
    { "gregorian.month.12.name", "Diciembre" },
    { "gregorian.month.12.origin", "Decem (diez) \xe2\x80\x94 el d\xc3\xa9" "cimo mes del antiguo calendario romano" },
    { "gregorian.month.12.quality", "Solsticio de invierno, Saturnalia, el retorno de la luz" },
    { "gregorian.month.2.brief", "El mes de la purificaci\xc3\xb3n \xe2\x80\x94 los \xc3\xbaltimos fuegos antes del nuevo crecimiento" },
    { "gregorian.month.2.name", "Febrero" },
    { "gregorian.month.2.origin", "Februa \xe2\x80\x94 festival romano de purificaci\xc3\xb3n (Lupercalia)" },
    { "gregorian.month.2.quality", "Fin de invierno, purificaci\xc3\xb3n, preparaci\xc3\xb3n para la primavera" },
    { "gregorian.month.3.brief", "El mes de Marte \xe2\x80\x94 aqu\xc3\xad comenzaba el a\xc3\xb1o romano, con guerra y siembra por igual" },
    { "gregorian.month.3.name", "Marzo" },
    { "gregorian.month.3.origin", "Mars \xe2\x80\x94 dios de la guerra y la agricultura, el a\xc3\xb1o nuevo romano" },
    { "gregorian.month.3.quality", "Equinoccio de primavera, despertar, crecimiento vigoroso" },
    { "gregorian.month.4.brief", "El mes de la apertura \xe2\x80\x94 todo lo que estaba cerrado comienza a desplegarse" },
    { "gregorian.month.4.name", "Abril" },
    { "gregorian.month.4.origin", "Aperire (abrir) \xe2\x80\x94 la tierra se abre, los brotes se despliegan" },
    { "gregorian.month.4.quality", "Plena primavera, apertura, floraci\xc3\xb3n" },
    { "gregorian.month.5.brief", "El mes del crecimiento \xe2\x80\x94 la diosa de la tierra cuyo nombre significa 'la que es grande'" },
    { "gregorian.month.5.name", "Mayo" },
    { "gregorian.month.5.origin", "Maia \xe2\x80\x94 diosa del crecimiento, madre de Mercurio" },
    { "gregorian.month.5.quality", "Fin de primavera, fertilidad, abundancia naciente" },
    { "gregorian.month.6.brief", "El mes del matrimonio \xe2\x80\x94 la reina del cielo bendice los d\xc3\xad" "as m\xc3\xa1s largos" },
    { "gregorian.month.6.name", "Junio" },
    { "gregorian.month.6.origin", "Juno \xe2\x80\x94 reina de los dioses, patrona del matrimonio" },
    { "gregorian.month.6.quality", "Solsticio de verano, uni\xc3\xb3n, m\xc3\xa1xima luz diurna" },
    { "gregorian.month.7.brief", "El mes de C\xc3\xa9sar \xe2\x80\x94 nombrado por el hombre que rehizo el tiempo mismo" },
    { "gregorian.month.7.name", "Julio" },
    { "gregorian.month.7.origin", "Julius Caesar \xe2\x80\x94 reform\xc3\xb3 el calendario, deificado tras su muerte" },
    { "gregorian.month.7.quality", "Pleno verano, poder, resplandor" },
    { "gregorian.month.8.brief", "El mes de Augusto \xe2\x80\x94 el emperador que exigi\xc3\xb3 un mes tan grandioso como julio" },
    { "gregorian.month.8.name", "Agosto" },
    { "gregorian.month.8.origin", "Augustus Caesar \xe2\x80\x94 primer emperador romano, 'el venerado'" },
    { "gregorian.month.8.quality", "Fin de verano, comienza la cosecha, el imperio en su cenit" },
    { "gregorian.month.9.brief", "El s\xc3\xa9ptimo mes \xe2\x80\x94 a\xc3\xban porta su viejo n\xc3\xbamero aunque ahora es el noveno" },
    { "gregorian.month.9.name", "Septiembre" },
    { "gregorian.month.9.origin", "Septem (siete) \xe2\x80\x94 el s\xc3\xa9ptimo mes del antiguo calendario romano" },
    { "gregorian.month.9.quality", "Equinoccio de oto\xc3\xb1o, equilibrio, recogimiento" },
    { "gregorian.season.0.brief", "La estaci\xc3\xb3n del devenir \xe2\x80\x94 todo lo que dorm\xc3\xad" "a ahora despierta" },
    { "gregorian.season.0.name", "Primavera" },
    { "gregorian.season.0.quality", "Expansiva \xe2\x80\x94 la energ\xc3\xad" "a asciende, las semillas germinan, los d\xc3\xad" "as se alargan" },
    { "gregorian.season.0.theme", "Renacimiento, crecimiento, lo potencial se hace real" },
    { "gregorian.season.1.brief", "La estaci\xc3\xb3n del ser \xe2\x80\x94 el mundo en su m\xc3\xa1ximo esplendor" },
    { "gregorian.season.1.name", "Verano" },
    { "gregorian.season.1.quality", "Radiante \xe2\x80\x94 energ\xc3\xad" "a en su apogeo, la luz domina, la vida en plena floraci\xc3\xb3n" },
    { "gregorian.season.1.theme", "Plenitud, resplandor, m\xc3\xa1xima expresi\xc3\xb3n" },
    { "gregorian.season.2.brief", "La estaci\xc3\xb3n del soltar \xe2\x80\x94 belleza en la ca\xc3\xad" "da, riqueza en la entrega" },
    { "gregorian.season.2.name", "Oto\xc3\xb1o" },
    { "gregorian.season.2.quality", "Contractiva \xe2\x80\x94 la energ\xc3\xad" "a se recoge, el fruto madura, las hojas caen" },
    { "gregorian.season.2.theme", "Cosecha, liberaci\xc3\xb3n, gratitud por lo que creci\xc3\xb3" },
    { "gregorian.season.3.brief", "La estaci\xc3\xb3n del reposo \xe2\x80\x94 lo que parece muerto est\xc3\xa1 so\xc3\xb1" "ando" },
    { "gregorian.season.3.name", "Invierno" },
    { "gregorian.season.3.quality", "Quieta \xe2\x80\x94 energ\xc3\xad" "a recogida en las ra\xc3\xad" "ces, silencio, gestaci\xc3\xb3n en la oscuridad" },
    { "gregorian.season.3.theme", "Descanso, profundidad, la semilla oculta, quietud esencial" },
    { "gregorian.tpl.detail", "%1$s: %2$s. %3$s. Estaci\xc3\xb3n: %4$s \xe2\x80\x94 %5$s. %6$s (%7$s): %8$s." },
    { "gregorian.tpl.glance", "%1$s %2$d (%3$s) \xe2\x80\x94 %4$s" },
    { "hebrew.month.1.brief", "Mes de milagros y liberaci\xc3\xb3n \xe2\x80\x94 Pesaj" },
    { "hebrew.month.1.letter", "Hei" },
    { "hebrew.month.1.name", "Nisan" },
    { "hebrew.month.1.quality", "Redenci\xc3\xb3n" },
    { "hebrew.month.1.sense", "Habla" },
    { "hebrew.month.1.tribe", "Jud\xc3\xa1" },
    { "hebrew.month.10.brief", "El mes m\xc3\xa1s oscuro \xe2\x80\x94 indignaci\xc3\xb3n justa" },
    { "hebrew.month.10.letter", "Ayin" },
    { "hebrew.month.10.name", "Tevet" },
    { "hebrew.month.10.quality", "Transformaci\xc3\xb3n" },
    { "hebrew.month.10.sense", "Ira (justa)" },
    { "hebrew.month.10.tribe", "Dan" },
    { "hebrew.month.11.brief", "A\xc3\xb1o Nuevo de los \xc3\x81rboles \xe2\x80\x94 Tu BiShvat" },
    { "hebrew.month.11.letter", "Tzadi" },
    { "hebrew.month.11.name", "Shevat" },
    { "hebrew.month.11.quality", "Renovaci\xc3\xb3n" },
    { "hebrew.month.11.sense", "Gusto" },
    { "hebrew.month.11.tribe", "Aser" },
    { "hebrew.month.12.brief", "Mes de Purim \xe2\x80\x94 milagros ocultos revelados" },
    { "hebrew.month.12.letter", "Qof" },
    { "hebrew.month.12.name", "Adar" },
    { "hebrew.month.12.quality", "Alegr\xc3\xad" "a y transformaci\xc3\xb3n" },
    { "hebrew.month.12.sense", "Risa" },
    { "hebrew.month.12.tribe", "Neftal\xc3\xad" },
    { "hebrew.month.13.brief", "Mes bisiesto \xe2\x80\x94 Purim se celebra aqu\xc3\xad en a\xc3\xb1os bisiestos" },
    { "hebrew.month.13.letter", "Qof" },
    { "hebrew.month.13.name", "Adar II" },
    { "hebrew.month.13.quality", "Alegr\xc3\xad" "a duplicada" },
    { "hebrew.month.13.sense", "Risa" },
    { "hebrew.month.13.tribe", "Neftal\xc3\xad" },
    { "hebrew.month.2.brief", "Mes de sanaci\xc3\xb3n natural \xe2\x80\x94 la cuenta del \xc3\x93mer" },
    { "hebrew.month.2.letter", "Vav" },
    { "hebrew.month.2.name", "Iyar" },
    { "hebrew.month.2.quality", "Sanaci\xc3\xb3n" },
    { "hebrew.month.2.sense", "Pensamiento" },
    { "hebrew.month.2.tribe", "Isacar" },
    { "hebrew.month.3.brief", "Mes de la entrega de la Tor\xc3\xa1 \xe2\x80\x94 Shavuot" },
    { "hebrew.month.3.letter", "Zayin" },
    { "hebrew.month.3.name", "Sivan" },
    { "hebrew.month.3.quality", "Revelaci\xc3\xb3n" },
    { "hebrew.month.3.sense", "Movimiento" },
    { "hebrew.month.3.tribe", "Zabul\xc3\xb3n" },
    { "hebrew.month.4.brief", "Mes de las tablas rotas \xe2\x80\x94 ver m\xc3\xa1s all\xc3\xa1" },
    { "hebrew.month.4.letter", "Chet" },
    { "hebrew.month.4.name", "Tammuz" },
    { "hebrew.month.4.quality", "Visi\xc3\xb3n en la oscuridad" },
    { "hebrew.month.4.sense", "Vista" },
    { "hebrew.month.4.tribe", "Rub\xc3\xa9n" },
    { "hebrew.month.5.brief", "Mes de destrucci\xc3\xb3n y consolaci\xc3\xb3n" },
    { "hebrew.month.5.letter", "Tet" },
    { "hebrew.month.5.name", "Av" },
    { "hebrew.month.5.quality", "Transformaci\xc3\xb3n del dolor" },
    { "hebrew.month.5.sense", "O\xc3\xad" "do" },
    { "hebrew.month.5.tribe", "Sime\xc3\xb3n" },
    { "hebrew.month.6.brief", "Mes del retorno \xe2\x80\x94 preparaci\xc3\xb3n para el a\xc3\xb1o nuevo" },
    { "hebrew.month.6.letter", "Yod" },
    { "hebrew.month.6.name", "Elul" },
    { "hebrew.month.6.quality", "Arrepentimiento" },
    { "hebrew.month.6.sense", "Acci\xc3\xb3n" },
    { "hebrew.month.6.tribe", "Gad" },
    { "hebrew.month.7.brief", "Mes de las Altas Fiestas \xe2\x80\x94 Rosh Hashan\xc3\xa1, Yom Kipur, Sucot" },
    { "hebrew.month.7.letter", "Lamed" },
    { "hebrew.month.7.name", "Tishrei" },
    { "hebrew.month.7.quality", "Asombro y juicio" },
    { "hebrew.month.7.sense", "Tacto" },
    { "hebrew.month.7.tribe", "Efra\xc3\xadn" },
    { "hebrew.month.8.brief", "El mes amargo \xe2\x80\x94 sin festividades, solo plegarias por lluvia" },
    { "hebrew.month.8.letter", "Nun" },
    { "hebrew.month.8.name", "Cheshvan" },
    { "hebrew.month.8.quality", "Profundidad silenciosa" },
    { "hebrew.month.8.sense", "Olfato" },
    { "hebrew.month.8.tribe", "Manas\xc3\xa9s" },
    { "hebrew.month.9.brief", "Mes de sue\xc3\xb1os y luces \xe2\x80\x94 Januc\xc3\xa1" },
    { "hebrew.month.9.letter", "Samekh" },
    { "hebrew.month.9.name", "Kislev" },
    { "hebrew.month.9.quality", "Confianza y milagros" },
    { "hebrew.month.9.sense", "Sue\xc3\xb1o" },
    { "hebrew.month.9.tribe", "Benjam\xc3\xadn" },
    { "hebrew.tpl.detail", "%2$s es el mes de %1$s. Su letra es %3$s, su tribu es %4$s, su sentido es %5$s. %6$s." },
    { "hebrew.tpl.glance", "%1$d %2$s %3$d \xe2\x80\x94 %4$s" },
    { "hebrew.tpl.sabbatical", " A\xc3\xb1o de Shemit\xc3\xa1 %1$d de 7." },
};

#define GEN_CONTENT_ES_COUNT \
    ((int)(sizeof(gen_content_es) / sizeof(gen_content_es[0])))

#endif /* TIME_CONTENT_GENERATED_H */
