/* content_generated.h — AUTO-GENERATED from data/content JSON files.
 * Do not edit manually. Run: python3 scripts/gen_content.py
 * Content translation arrays for content_i18n.c. */

#ifndef TIME_CONTENT_GENERATED_H
#define TIME_CONTENT_GENERATED_H

#include "i18n.h"

/* ---- EN (642 keys, canonical) ---- */

static const i18n_entry_t gen_content_en[] = {
    { "astrology.element.0.expression", "Through action, inspiration, and enthusiasm" },
    { "astrology.element.0.name", "Fire" },
    { "astrology.element.0.quality", "Will, spirit, creative force" },
    { "astrology.element.1.expression", "Through building, sustaining, and manifesting" },
    { "astrology.element.1.name", "Earth" },
    { "astrology.element.1.quality", "Form, matter, practical wisdom" },
    { "astrology.element.2.expression", "Through thinking, connecting, and exchanging" },
    { "astrology.element.2.name", "Air" },
    { "astrology.element.2.quality", "Mind, communication, relationship" },
    { "astrology.element.3.expression", "Through emotion, empathy, and transformation" },
    { "astrology.element.3.name", "Water" },
    { "astrology.element.3.quality", "Feeling, intuition, the unconscious" },
    { "astrology.modality.0.name", "Cardinal" },
    { "astrology.modality.0.quality", "Initiation, leadership, new beginnings" },
    { "astrology.modality.0.role", "Begins the season \xe2\x80\x94 the spark that starts" },
    { "astrology.modality.1.name", "Fixed" },
    { "astrology.modality.1.quality", "Sustaining, determination, depth" },
    { "astrology.modality.1.role", "Holds the season \xe2\x80\x94 the strength that endures" },
    { "astrology.modality.2.name", "Mutable" },
    { "astrology.modality.2.quality", "Adaptation, flexibility, transition" },
    { "astrology.modality.2.role", "Ends the season \xe2\x80\x94 the wisdom that releases" },
    { "astrology.sign.0.abbr", "Ari" },
    { "astrology.sign.0.archetype", "The Warrior" },
    { "astrology.sign.0.brief", "The spark that begins \xe2\x80\x94 raw courage to exist" },
    { "astrology.sign.0.element", "Fire" },
    { "astrology.sign.0.keywords", "Courage, initiative, independence" },
    { "astrology.sign.0.modality", "Cardinal" },
    { "astrology.sign.0.name", "Aries" },
    { "astrology.sign.0.ruler", "Mars" },
    { "astrology.sign.0.shadow", "Impatience, aggression, selfishness" },
    { "astrology.sign.1.abbr", "Tau" },
    { "astrology.sign.1.archetype", "The Builder" },
    { "astrology.sign.1.brief", "The earth that endures \xe2\x80\x94 patient cultivation of beauty" },
    { "astrology.sign.1.element", "Earth" },
    { "astrology.sign.1.keywords", "Stability, sensuality, persistence" },
    { "astrology.sign.1.modality", "Fixed" },
    { "astrology.sign.1.name", "Taurus" },
    { "astrology.sign.1.ruler", "Venus" },
    { "astrology.sign.1.shadow", "Stubbornness, possessiveness, inertia" },
    { "astrology.sign.10.abbr", "Aqu" },
    { "astrology.sign.10.archetype", "The Visionary" },
    { "astrology.sign.10.brief", "The wave that carries \xe2\x80\x94 freedom in service of all" },
    { "astrology.sign.10.element", "Air" },
    { "astrology.sign.10.keywords", "Innovation, humanity, independence" },
    { "astrology.sign.10.modality", "Fixed" },
    { "astrology.sign.10.name", "Aquarius" },
    { "astrology.sign.10.ruler", "Uranus" },
    { "astrology.sign.10.shadow", "Detachment, rebellion, eccentricity" },
    { "astrology.sign.11.abbr", "Pis" },
    { "astrology.sign.11.archetype", "The Mystic" },
    { "astrology.sign.11.brief", "The ocean that dissolves \xe2\x80\x94 unity beyond separation" },
    { "astrology.sign.11.element", "Water" },
    { "astrology.sign.11.keywords", "Compassion, imagination, transcendence" },
    { "astrology.sign.11.modality", "Mutable" },
    { "astrology.sign.11.name", "Pisces" },
    { "astrology.sign.11.ruler", "Neptune" },
    { "astrology.sign.11.shadow", "Escapism, confusion, martyrdom" },
    { "astrology.sign.2.abbr", "Gem" },
    { "astrology.sign.2.archetype", "The Messenger" },
    { "astrology.sign.2.brief", "The breath between \xe2\x80\x94 connecting through language" },
    { "astrology.sign.2.element", "Air" },
    { "astrology.sign.2.keywords", "Communication, curiosity, adaptability" },
    { "astrology.sign.2.modality", "Mutable" },
    { "astrology.sign.2.name", "Gemini" },
    { "astrology.sign.2.ruler", "Mercury" },
    { "astrology.sign.2.shadow", "Superficiality, restlessness, duplicity" },
    { "astrology.sign.3.abbr", "Can" },
    { "astrology.sign.3.archetype", "The Mother" },
    { "astrology.sign.3.brief", "The shell that protects \xe2\x80\x94 feeling as a form of knowing" },
    { "astrology.sign.3.element", "Water" },
    { "astrology.sign.3.keywords", "Nurture, emotion, protection" },
    { "astrology.sign.3.modality", "Cardinal" },
    { "astrology.sign.3.name", "Cancer" },
    { "astrology.sign.3.ruler", "Moon" },
    { "astrology.sign.3.shadow", "Clinginess, moodiness, manipulation" },
    { "astrology.sign.4.abbr", "Leo" },
    { "astrology.sign.4.archetype", "The King" },
    { "astrology.sign.4.brief", "The fire that sustains \xe2\x80\x94 the courage to shine" },
    { "astrology.sign.4.element", "Fire" },
    { "astrology.sign.4.keywords", "Creativity, generosity, self-expression" },
    { "astrology.sign.4.modality", "Fixed" },
    { "astrology.sign.4.name", "Leo" },
    { "astrology.sign.4.ruler", "Sun" },
    { "astrology.sign.4.shadow", "Pride, drama, dominance" },
    { "astrology.sign.5.abbr", "Vir" },
    { "astrology.sign.5.archetype", "The Healer" },
    { "astrology.sign.5.brief", "The hand that mends \xe2\x80\x94 wholeness through discernment" },
    { "astrology.sign.5.element", "Earth" },
    { "astrology.sign.5.keywords", "Analysis, service, refinement" },
    { "astrology.sign.5.modality", "Mutable" },
    { "astrology.sign.5.name", "Virgo" },
    { "astrology.sign.5.ruler", "Mercury" },
    { "astrology.sign.5.shadow", "Criticism, anxiety, perfectionism" },
    { "astrology.sign.6.abbr", "Lib" },
    { "astrology.sign.6.archetype", "The Diplomat" },
    { "astrology.sign.6.brief", "The scales that balance \xe2\x80\x94 beauty as equilibrium" },
    { "astrology.sign.6.element", "Air" },
    { "astrology.sign.6.keywords", "Harmony, partnership, justice" },
    { "astrology.sign.6.modality", "Cardinal" },
    { "astrology.sign.6.name", "Libra" },
    { "astrology.sign.6.ruler", "Venus" },
    { "astrology.sign.6.shadow", "Indecision, people-pleasing, avoidance" },
    { "astrology.sign.7.abbr", "Sco" },
    { "astrology.sign.7.archetype", "The Alchemist" },
    { "astrology.sign.7.brief", "The depth that transforms \xe2\x80\x94 death as doorway" },
    { "astrology.sign.7.element", "Water" },
    { "astrology.sign.7.keywords", "Transformation, intensity, depth" },
    { "astrology.sign.7.modality", "Fixed" },
    { "astrology.sign.7.name", "Scorpio" },
    { "astrology.sign.7.ruler", "Pluto" },
    { "astrology.sign.7.shadow", "Obsession, jealousy, destruction" },
    { "astrology.sign.8.abbr", "Sag" },
    { "astrology.sign.8.archetype", "The Explorer" },
    { "astrology.sign.8.brief", "The arrow that seeks \xe2\x80\x94 meaning beyond the horizon" },
    { "astrology.sign.8.element", "Fire" },
    { "astrology.sign.8.keywords", "Philosophy, adventure, truth-seeking" },
    { "astrology.sign.8.modality", "Mutable" },
    { "astrology.sign.8.name", "Sagittarius" },
    { "astrology.sign.8.ruler", "Jupiter" },
    { "astrology.sign.8.shadow", "Excess, dogmatism, restlessness" },
    { "astrology.sign.9.abbr", "Cap" },
    { "astrology.sign.9.archetype", "The Elder" },
    { "astrology.sign.9.brief", "The mountain that stands \xe2\x80\x94 authority earned through time" },
    { "astrology.sign.9.element", "Earth" },
    { "astrology.sign.9.keywords", "Ambition, discipline, mastery" },
    { "astrology.sign.9.modality", "Cardinal" },
    { "astrology.sign.9.name", "Capricorn" },
    { "astrology.sign.9.ruler", "Saturn" },
    { "astrology.sign.9.shadow", "Coldness, rigidity, ruthlessness" },
    { "astrology.tpl.detail", "%1$s Sun: %2$s. %3$s. Keywords: %4$s. Shadow: %5$s. Element: %6$s (%7$s). Modality: %8$s (%9$s). Moon in %10$s: emotional nature is %11$s." },
    { "astrology.tpl.detail_asc", " Ascendant in %1$s: the mask is %2$s." },
    { "astrology.tpl.glance", "Sun in %1$s \xc2\xb7 Moon in %2$s" },
    { "astrology.tpl.glance_asc", "Sun in %1$s \xc2\xb7 Moon in %2$s \xc2\xb7 %3$s Rising" },
    { "astronomy.phase.0.brief", "The dark seed \xe2\x80\x94 invisible, full of potential, everything begins here" },
    { "astronomy.phase.0.guidance", "Set intentions, start projects, rest and reflect in the darkness" },
    { "astronomy.phase.0.name", "New Moon" },
    { "astronomy.phase.0.theme", "Beginnings, seed planting, intention setting, the dark of renewal" },
    { "astronomy.phase.1.brief", "The first sliver \xe2\x80\x94 intention made visible, the young light gathering strength" },
    { "astronomy.phase.1.guidance", "Take the first step, gather resources, push through initial resistance" },
    { "astronomy.phase.1.name", "Waxing Crescent" },
    { "astronomy.phase.1.theme", "Emerging intention, first commitment, the courage to begin" },
    { "astronomy.phase.2.brief", "The half-lit choice \xe2\x80\x94 light and dark in equal measure, the crossroads" },
    { "astronomy.phase.2.guidance", "Make decisions, overcome obstacles, commit to the direction chosen" },
    { "astronomy.phase.2.name", "First Quarter" },
    { "astronomy.phase.2.theme", "Challenge, decision, the crisis of action" },
    { "astronomy.phase.3.brief", "Almost full \xe2\x80\x94 the final preparation, polishing before the peak" },
    { "astronomy.phase.3.guidance", "Refine the plan, adjust based on feedback, trust the process" },
    { "astronomy.phase.3.name", "Waxing Gibbous" },
    { "astronomy.phase.3.theme", "Refinement, adjustment, patience before fulfillment" },
    { "astronomy.phase.4.brief", "The full light \xe2\x80\x94 everything illuminated, nothing hidden, the peak" },
    { "astronomy.phase.4.guidance", "Celebrate completion, see clearly, harvest what was planted at the new moon" },
    { "astronomy.phase.4.name", "Full Moon" },
    { "astronomy.phase.4.theme", "Culmination, illumination, harvest, revelation" },
    { "astronomy.phase.5.brief", "The generous decline \xe2\x80\x94 the light begins to give itself away" },
    { "astronomy.phase.5.guidance", "Share what you've learned, give back, express gratitude for the harvest" },
    { "astronomy.phase.5.name", "Waning Gibbous" },
    { "astronomy.phase.5.theme", "Gratitude, sharing, teaching, distribution" },
    { "astronomy.phase.6.brief", "The half-lit release \xe2\x80\x94 light and dark again equal, but now the light is leaving" },
    { "astronomy.phase.6.guidance", "Let go of what no longer serves, forgive, clear space for the new" },
    { "astronomy.phase.6.name", "Last Quarter" },
    { "astronomy.phase.6.theme", "Release, forgiveness, clearing, the crisis of letting go" },
    { "astronomy.phase.7.brief", "The last whisper \xe2\x80\x94 the thinnest light before the dark, the wisdom of surrender" },
    { "astronomy.phase.7.guidance", "Rest deeply, surrender control, prepare for the coming darkness" },
    { "astronomy.phase.7.name", "Waning Crescent" },
    { "astronomy.phase.7.theme", "Surrender, rest, preparation for the void, the balsamic phase" },
    { "astronomy.planet.0.archetype", "The Trickster-Messenger \xe2\x80\x94 quicksilver mind, the psychopomp who bridges realms" },
    { "astronomy.planet.0.brief", "The swift messenger \xe2\x80\x94 closest to the Sun, never far from the source of light" },
    { "astronomy.planet.0.deity", "Hermes / Nabu / Thoth" },
    { "astronomy.planet.0.domain", "Communication, intellect, commerce, the messenger between worlds" },
    { "astronomy.planet.0.name", "Mercury" },
    { "astronomy.planet.1.archetype", "The Beloved \xe2\x80\x94 the mirror of desire, beauty as a force that civilizes" },
    { "astronomy.planet.1.brief", "The morning and evening star \xe2\x80\x94 the brightest planet, whose light is borrowed" },
    { "astronomy.planet.1.deity", "Aphrodite / Ishtar / Freya" },
    { "astronomy.planet.1.domain", "Love, beauty, harmony, values, artistic creation" },
    { "astronomy.planet.1.name", "Venus" },
    { "astronomy.planet.2.archetype", "The Mother \xe2\x80\x94 the living world that sustains all observation of the cosmos" },
    { "astronomy.planet.2.brief", "The pale blue dot \xe2\x80\x94 the only planet we know that looks back at the sky" },
    { "astronomy.planet.2.deity", "Gaia / Terra / Jord" },
    { "astronomy.planet.2.domain", "Home, embodiment, the body, the ground we stand on" },
    { "astronomy.planet.2.name", "Earth" },
    { "astronomy.planet.3.archetype", "The Warrior \xe2\x80\x94 the red force that fights for what matters" },
    { "astronomy.planet.3.brief", "The red planet \xe2\x80\x94 iron-rusted, blood-colored, named for the god of war" },
    { "astronomy.planet.3.deity", "Ares / Nergal / Tyr" },
    { "astronomy.planet.3.domain", "Action, drive, conflict, courage, the will to assert" },
    { "astronomy.planet.3.name", "Mars" },
    { "astronomy.planet.4.archetype", "The King \xe2\x80\x94 the largest body in the solar system after the Sun, protector and judge" },
    { "astronomy.planet.4.brief", "The great benefic \xe2\x80\x94 more massive than all other planets combined" },
    { "astronomy.planet.4.deity", "Zeus / Marduk / Thor" },
    { "astronomy.planet.4.domain", "Expansion, wisdom, generosity, law, the great benefic" },
    { "astronomy.planet.4.name", "Jupiter" },
    { "astronomy.planet.5.archetype", "The Elder \xe2\x80\x94 the ringed boundary, the lesson that cannot be avoided" },
    { "astronomy.planet.5.brief", "The ringed teacher \xe2\x80\x94 beautiful and severe, the lord of time and consequence" },
    { "astronomy.planet.5.deity", "Kronos / Ninurta / Loki" },
    { "astronomy.planet.5.domain", "Structure, limitation, time, discipline, the great teacher" },
    { "astronomy.planet.5.name", "Saturn" },
    { "astronomy.planet.6.archetype", "The Awakener \xe2\x80\x94 the lightning bolt of change, the force that disrupts to liberate" },
    { "astronomy.planet.6.brief", "The tilted rebel \xe2\x80\x94 rolling on its side, the planet that breaks every rule" },
    { "astronomy.planet.6.deity", "Ouranos / sky father" },
    { "astronomy.planet.6.domain", "Revolution, originality, sudden insight, the unexpected" },
    { "astronomy.planet.6.name", "Uranus" },
    { "astronomy.planet.7.archetype", "The Mystic \xe2\x80\x94 the dissolving ocean where boundaries cease to exist" },
    { "astronomy.planet.7.brief", "The blue dreamer \xe2\x80\x94 farthest major planet, where the solar system fades into mystery" },
    { "astronomy.planet.7.deity", "Poseidon / Ea / Njord" },
    { "astronomy.planet.7.domain", "Imagination, transcendence, illusion, the oceanic unconscious" },
    { "astronomy.planet.7.name", "Neptune" },
    { "astronomy.tpl.detail", "Planet: %1$s. Deity: %2$s. Domain: %3$s. %4$s." },
    { "astronomy.tpl.detail_moon", " Moon: %1$s \xe2\x80\x94 %2$s." },
    { "astronomy.tpl.detail_planet", "Planet: %1$s. Deity: %2$s. Domain: %3$s. %4$s." },
    { "astronomy.tpl.detail_retro", " RETROGRADE: apparent backward motion \xe2\x80\x94 the planet's themes turn inward for review." },
    { "astronomy.tpl.detail_retrograde", " RETROGRADE: apparent backward motion \xe2\x80\x94 the planet's themes turn inward for review." },
    { "astronomy.tpl.glance", "%1$s \xe2\x80\x94 %2$s" },
    { "astronomy.tpl.glance_moon", "%1$s \xe2\x80\x94 %2$s + %3$s" },
    { "astronomy.tpl.glance_phase", "%1$s \xe2\x80\x94 %2$s + %3$s" },
    { "astronomy.tpl.glance_retro", "%1$s (retrograde) \xe2\x80\x94 %2$s" },
    { "astronomy.tpl.glance_retrograde", "%1$s (retrograde) \xe2\x80\x94 %2$s" },
    { "buddhist.kalpa.0.description", "Worlds arise from emptiness \xe2\x80\x94 matter condenses, beings take form" },
    { "buddhist.kalpa.0.meaning", "The cosmic breath inward \xe2\x80\x94 creation as inevitable arising" },
    { "buddhist.kalpa.0.name", "Formation" },
    { "buddhist.kalpa.0.pali", "Vivatta" },
    { "buddhist.kalpa.1.description", "Beings live, die, and are reborn \xe2\x80\x94 the wheel turns" },
    { "buddhist.kalpa.1.meaning", "The present era \xe2\x80\x94 sentient experience in all its suffering and beauty" },
    { "buddhist.kalpa.1.name", "Existence" },
    { "buddhist.kalpa.1.pali", "Vivattathaayi" },
    { "buddhist.kalpa.2.description", "Worlds dissolve through fire, water, or wind" },
    { "buddhist.kalpa.2.meaning", "The cosmic breath outward \xe2\x80\x94 all conditioned things are impermanent" },
    { "buddhist.kalpa.2.name", "Destruction" },
    { "buddhist.kalpa.2.pali", "Samvatta" },
    { "buddhist.kalpa.3.description", "Vast darkness between worlds \xe2\x80\x94 nothing remains" },
    { "buddhist.kalpa.3.meaning", "The great rest \xe2\x80\x94 potential without form, like dreamless sleep" },
    { "buddhist.kalpa.3.name", "Emptiness" },
    { "buddhist.kalpa.3.pali", "Samvattathaayi" },
    { "buddhist.month.1.meaning", "Month of awakening \xe2\x80\x94 nature stirs" },
    { "buddhist.month.1.observance", "Songkran/New Year in some traditions" },
    { "buddhist.month.1.pali_name", "Citta" },
    { "buddhist.month.1.season", "Hot" },
    { "buddhist.month.10.meaning", "Month of nourishment" },
    { "buddhist.month.10.observance", "" },
    { "buddhist.month.10.pali_name", "Phussa" },
    { "buddhist.month.10.season", "Cool" },
    { "buddhist.month.11.meaning", "Month of the Sangha \xe2\x80\x94 community of awakening" },
    { "buddhist.month.11.observance", "Magha Puja \xe2\x80\x94 Sangha Day, 1250 monks gathered" },
    { "buddhist.month.11.pali_name", "Magha" },
    { "buddhist.month.11.season", "Cool" },
    { "buddhist.month.12.meaning", "Month of completion \xe2\x80\x94 cycle prepares to renew" },
    { "buddhist.month.12.observance", "" },
    { "buddhist.month.12.pali_name", "Phalguna" },
    { "buddhist.month.12.season", "Hot" },
    { "buddhist.month.2.meaning", "The most sacred month \xe2\x80\x94 triple anniversary" },
    { "buddhist.month.2.observance", "Vesak \xe2\x80\x94 Buddha's birth, enlightenment, parinibbana" },
    { "buddhist.month.2.pali_name", "Vesakha" },
    { "buddhist.month.2.season", "Hot" },
    { "buddhist.month.3.meaning", "Month of endurance through heat" },
    { "buddhist.month.3.observance", "" },
    { "buddhist.month.3.pali_name", "Jettha" },
    { "buddhist.month.3.season", "Hot" },
    { "buddhist.month.4.meaning", "Month of the first teaching \xe2\x80\x94 the Wheel turns" },
    { "buddhist.month.4.observance", "Asalha Puja \xe2\x80\x94 First Sermon, Dhammacakkappavattana" },
    { "buddhist.month.4.pali_name", "Asalha" },
    { "buddhist.month.4.season", "Rainy" },
    { "buddhist.month.5.meaning", "Month of withdrawal \xe2\x80\x94 monastics enter retreat" },
    { "buddhist.month.5.observance", "Vassa begins \xe2\x80\x94 Rain Retreat starts" },
    { "buddhist.month.5.pali_name", "Savana" },
    { "buddhist.month.5.season", "Rainy" },
    { "buddhist.month.6.meaning", "Month of devoted practice" },
    { "buddhist.month.6.observance", "Vassa continues" },
    { "buddhist.month.6.pali_name", "Bhaddapada" },
    { "buddhist.month.6.season", "Rainy" },
    { "buddhist.month.7.meaning", "Month of invitation \xe2\x80\x94 community reconciliation" },
    { "buddhist.month.7.observance", "Vassa ends \xe2\x80\x94 Pavarana ceremony" },
    { "buddhist.month.7.pali_name", "Assayuja" },
    { "buddhist.month.7.season", "Rainy" },
    { "buddhist.month.8.meaning", "Month of generosity \xe2\x80\x94 dana and gratitude" },
    { "buddhist.month.8.observance", "Kathina \xe2\x80\x94 robe offering to monastics" },
    { "buddhist.month.8.pali_name", "Kattika" },
    { "buddhist.month.8.season", "Cool" },
    { "buddhist.month.9.meaning", "Month of the path \xe2\x80\x94 quiet walking" },
    { "buddhist.month.9.observance", "" },
    { "buddhist.month.9.pali_name", "Maggasira" },
    { "buddhist.month.9.season", "Cool" },
    { "buddhist.tpl.detail", "%1$s: %2$s." },
    { "buddhist.tpl.detail_kalpa", " %1$s phase (%2$s): %3$s." },
    { "buddhist.tpl.detail_uposatha", " %1$s. %2$s." },
    { "buddhist.tpl.glance", "BE %1$d \xc2\xb7 %2$s \xc2\xb7 %3$s" },
    { "buddhist.tpl.glance_uposatha", "BE %1$d \xc2\xb7 %2$s \xc2\xb7 %3$s" },
    { "buddhist.uposatha.0.meaning", "An ordinary day in the cycle" },
    { "buddhist.uposatha.0.name", "No Observance" },
    { "buddhist.uposatha.0.practice", "Regular day" },
    { "buddhist.uposatha.1.meaning", "Darkness as potential \xe2\x80\x94 the seed moment before renewal" },
    { "buddhist.uposatha.1.name", "New Moon Observance" },
    { "buddhist.uposatha.1.practice", "Monastics recite Patimokkha; laity observe 8 precepts" },
    { "buddhist.uposatha.2.meaning", "Illumination \xe2\x80\x94 the Buddha's birth, enlightenment, and parinibbana all on full moons" },
    { "buddhist.uposatha.2.name", "Full Moon Observance" },
    { "buddhist.uposatha.2.practice", "Most important \xe2\x80\x94 full Patimokkha recital, intensive practice" },
    { "buddhist.uposatha.3.meaning", "Growing light \xe2\x80\x94 effort and aspiration building" },
    { "buddhist.uposatha.3.name", "Waxing Half-Moon" },
    { "buddhist.uposatha.3.practice", "Lighter observance, meditation and reflection" },
    { "buddhist.uposatha.4.meaning", "Releasing \xe2\x80\x94 wisdom of impermanence, letting go" },
    { "buddhist.uposatha.4.name", "Waning Half-Moon" },
    { "buddhist.uposatha.4.practice", "Lighter observance, letting go practice" },
    { "chinese.animal.0.archetype", "The Strategist" },
    { "chinese.animal.0.brief", "First in the cycle \xe2\x80\x94 the clever mind that finds opportunity in chaos" },
    { "chinese.animal.0.challenges", "Cunning, restless, manipulative" },
    { "chinese.animal.0.compatibility", "Dragon, Monkey, Ox" },
    { "chinese.animal.0.name", "Rat" },
    { "chinese.animal.0.strengths", "Resourceful, quick-witted, adaptable" },
    { "chinese.animal.1.archetype", "The Steadfast" },
    { "chinese.animal.1.brief", "The strength that plows through \xe2\x80\x94 patient endurance conquers all" },
    { "chinese.animal.1.challenges", "Stubborn, rigid, slow to change" },
    { "chinese.animal.1.compatibility", "Rat, Snake, Rooster" },
    { "chinese.animal.1.name", "Ox" },
    { "chinese.animal.1.strengths", "Patient, reliable, methodical" },
    { "chinese.animal.10.archetype", "The Guardian" },
    { "chinese.animal.10.brief", "The faithfulness that anchors \xe2\x80\x94 loyalty as the highest virtue" },
    { "chinese.animal.10.challenges", "Anxious, stubborn, judgmental" },
    { "chinese.animal.10.compatibility", "Tiger, Rabbit, Horse" },
    { "chinese.animal.10.name", "Dog" },
    { "chinese.animal.10.strengths", "Loyal, honest, protective" },
    { "chinese.animal.11.archetype", "The Generous" },
    { "chinese.animal.11.brief", "The abundance that overflows \xe2\x80\x94 generosity without calculation" },
    { "chinese.animal.11.challenges", "Naive, indulgent, gullible" },
    { "chinese.animal.11.compatibility", "Rabbit, Goat, Tiger" },
    { "chinese.animal.11.name", "Pig" },
    { "chinese.animal.11.strengths", "Kind, generous, optimistic" },
    { "chinese.animal.2.archetype", "The Brave" },
    { "chinese.animal.2.brief", "The roar that awakens \xe2\x80\x94 fearless action in service of justice" },
    { "chinese.animal.2.challenges", "Reckless, volatile, domineering" },
    { "chinese.animal.2.compatibility", "Horse, Dog, Pig" },
    { "chinese.animal.2.name", "Tiger" },
    { "chinese.animal.2.strengths", "Courageous, passionate, confident" },
    { "chinese.animal.3.archetype", "The Diplomat" },
    { "chinese.animal.3.brief", "The grace that disarms \xe2\x80\x94 softness as a form of power" },
    { "chinese.animal.3.challenges", "Timid, superficial, escapist" },
    { "chinese.animal.3.compatibility", "Goat, Pig, Dog" },
    { "chinese.animal.3.name", "Rabbit" },
    { "chinese.animal.3.strengths", "Elegant, gentle, compassionate" },
    { "chinese.animal.4.archetype", "The Emperor" },
    { "chinese.animal.4.brief", "The only mythical animal \xe2\x80\x94 the dream of transcendence made manifest" },
    { "chinese.animal.4.challenges", "Arrogant, demanding, impulsive" },
    { "chinese.animal.4.compatibility", "Rat, Monkey, Rooster" },
    { "chinese.animal.4.name", "Dragon" },
    { "chinese.animal.4.strengths", "Charismatic, ambitious, visionary" },
    { "chinese.animal.5.archetype", "The Philosopher" },
    { "chinese.animal.5.brief", "The coil that strikes true \xe2\x80\x94 deep wisdom beneath a still surface" },
    { "chinese.animal.5.challenges", "Secretive, suspicious, possessive" },
    { "chinese.animal.5.compatibility", "Ox, Rooster, Dragon" },
    { "chinese.animal.5.name", "Snake" },
    { "chinese.animal.5.strengths", "Wise, intuitive, graceful" },
    { "chinese.animal.6.archetype", "The Free Spirit" },
    { "chinese.animal.6.brief", "The gallop that liberates \xe2\x80\x94 freedom as a way of being" },
    { "chinese.animal.6.challenges", "Impatient, irresponsible, anxious" },
    { "chinese.animal.6.compatibility", "Tiger, Goat, Dog" },
    { "chinese.animal.6.name", "Horse" },
    { "chinese.animal.6.strengths", "Energetic, independent, adventurous" },
    { "chinese.animal.7.archetype", "The Artist" },
    { "chinese.animal.7.brief", "The heart that creates \xe2\x80\x94 beauty born from sensitivity" },
    { "chinese.animal.7.challenges", "Indecisive, pessimistic, dependent" },
    { "chinese.animal.7.compatibility", "Rabbit, Horse, Pig" },
    { "chinese.animal.7.name", "Goat" },
    { "chinese.animal.7.strengths", "Creative, gentle, empathetic" },
    { "chinese.animal.8.archetype", "The Inventor" },
    { "chinese.animal.8.brief", "The mind that plays \xe2\x80\x94 genius disguised as mischief" },
    { "chinese.animal.8.challenges", "Tricky, arrogant, unreliable" },
    { "chinese.animal.8.compatibility", "Rat, Dragon, Snake" },
    { "chinese.animal.8.name", "Monkey" },
    { "chinese.animal.8.strengths", "Clever, playful, versatile" },
    { "chinese.animal.9.archetype", "The Observer" },
    { "chinese.animal.9.brief", "The voice that calls truth \xe2\x80\x94 precision in all things" },
    { "chinese.animal.9.challenges", "Critical, abrasive, vain" },
    { "chinese.animal.9.compatibility", "Ox, Snake, Dragon" },
    { "chinese.animal.9.name", "Rooster" },
    { "chinese.animal.9.strengths", "Honest, diligent, perceptive" },
    { "chinese.element.0.expression", "Through creativity, vision, and upward movement" },
    { "chinese.element.0.name", "Wood" },
    { "chinese.element.0.nature", "Growth, expansion, benevolence" },
    { "chinese.element.0.season", "Spring" },
    { "chinese.element.1.expression", "Through enthusiasm, warmth, and illumination" },
    { "chinese.element.1.name", "Fire" },
    { "chinese.element.1.nature", "Passion, transformation, brilliance" },
    { "chinese.element.1.season", "Summer" },
    { "chinese.element.2.expression", "Through grounding, nurture, and practical care" },
    { "chinese.element.2.name", "Earth" },
    { "chinese.element.2.nature", "Stability, nourishment, centering" },
    { "chinese.element.2.season", "Late Summer" },
    { "chinese.element.3.expression", "Through refinement, letting go, and sharp focus" },
    { "chinese.element.3.name", "Metal" },
    { "chinese.element.3.nature", "Precision, clarity, righteousness" },
    { "chinese.element.3.season", "Autumn" },
    { "chinese.element.4.expression", "Through flow, stillness, and the power of yielding" },
    { "chinese.element.4.name", "Water" },
    { "chinese.element.4.nature", "Wisdom, depth, adaptability" },
    { "chinese.element.4.season", "Winter" },
    { "chinese.polarity.yang", "Yang" },
    { "chinese.polarity.yin", "Yin" },
    { "chinese.tpl.detail", "%1$s %2$s: %3$s. Strengths: %4$s. Challenges: %5$s. Best with: %6$s. Element: %7$s (%8$s) \xe2\x80\x94 %9$s. Year %10$d of 60." },
    { "chinese.tpl.glance", "%1$s %2$s (%3$s) \xe2\x80\x94 %4$s" },
    { "gregorian.day.0.brief", "The Moon's day \xe2\x80\x94 intuition, emotion, the tides within" },
    { "gregorian.day.0.name", "Monday" },
    { "gregorian.day.0.origin", "Old English Monandaeg (Moon's day)" },
    { "gregorian.day.0.planet", "Moon" },
    { "gregorian.day.1.brief", "Mars' day \xe2\x80\x94 courage, action, the warrior's resolve" },
    { "gregorian.day.1.name", "Tuesday" },
    { "gregorian.day.1.origin", "Old English Tiwesdaeg (Tyr's day, Norse Mars)" },
    { "gregorian.day.1.planet", "Mars" },
    { "gregorian.day.2.brief", "Mercury's day \xe2\x80\x94 communication, craft, the trickster's wit" },
    { "gregorian.day.2.name", "Wednesday" },
    { "gregorian.day.2.origin", "Old English Wodnesdaeg (Woden's day, Norse Mercury)" },
    { "gregorian.day.2.planet", "Mercury" },
    { "gregorian.day.3.brief", "Jupiter's day \xe2\x80\x94 expansion, abundance, the thunder god's generosity" },
    { "gregorian.day.3.name", "Thursday" },
    { "gregorian.day.3.origin", "Old English Thunresdaeg (Thor's day, Norse Jupiter)" },
    { "gregorian.day.3.planet", "Jupiter" },
    { "gregorian.day.4.brief", "Venus' day \xe2\x80\x94 love, beauty, the goddess of desire" },
    { "gregorian.day.4.name", "Friday" },
    { "gregorian.day.4.origin", "Old English Frigedaeg (Freya's day, Norse Venus)" },
    { "gregorian.day.4.planet", "Venus" },
    { "gregorian.day.5.brief", "Saturn's day \xe2\x80\x94 discipline, structure, the taskmaster's lesson" },
    { "gregorian.day.5.name", "Saturday" },
    { "gregorian.day.5.origin", "Latin Saturni dies (Saturn's day)" },
    { "gregorian.day.5.planet", "Saturn" },
    { "gregorian.day.6.brief", "The Sun's day \xe2\x80\x94 vitality, sovereignty, the center of all orbits" },
    { "gregorian.day.6.name", "Sunday" },
    { "gregorian.day.6.origin", "Old English Sunnandaeg (Sun's day)" },
    { "gregorian.day.6.planet", "Sun" },
    { "gregorian.month.1.brief", "The month of doorways \xe2\x80\x94 one face looks back, one looks forward" },
    { "gregorian.month.1.name", "January" },
    { "gregorian.month.1.origin", "Janus \xe2\x80\x94 two-faced god of beginnings, gates, and transitions" },
    { "gregorian.month.1.quality", "Deep winter, reflection, fresh starts" },
    { "gregorian.month.10.brief", "The eighth month \xe2\x80\x94 the world turns inward as the light contracts" },
    { "gregorian.month.10.name", "October" },
    { "gregorian.month.10.origin", "Octo (eight) \xe2\x80\x94 the eighth month of the old Roman calendar" },
    { "gregorian.month.10.quality", "Mid-autumn, deepening, transformation" },
    { "gregorian.month.11.brief", "The ninth month \xe2\x80\x94 the dead are honored as the year grows old" },
    { "gregorian.month.11.name", "November" },
    { "gregorian.month.11.origin", "Novem (nine) \xe2\x80\x94 the ninth month of the old Roman calendar" },
    { "gregorian.month.11.quality", "Late autumn, remembrance, preparation for dark" },
    { "gregorian.month.12.brief", "The tenth month \xe2\x80\x94 in the deepest dark, the ancient Romans feasted and the sun was reborn" },
    { "gregorian.month.12.name", "December" },
    { "gregorian.month.12.origin", "Decem (ten) \xe2\x80\x94 the tenth month of the old Roman calendar" },
    { "gregorian.month.12.quality", "Winter solstice, Saturnalia, the return of light" },
    { "gregorian.month.2.brief", "The month of cleansing \xe2\x80\x94 the last fires of purification before new growth" },
    { "gregorian.month.2.name", "February" },
    { "gregorian.month.2.origin", "Februa \xe2\x80\x94 Roman purification festival (Lupercalia)" },
    { "gregorian.month.2.quality", "Late winter, purification, preparation for spring" },
    { "gregorian.month.3.brief", "The month of Mars \xe2\x80\x94 the old Roman year began here, with war and planting alike" },
    { "gregorian.month.3.name", "March" },
    { "gregorian.month.3.origin", "Mars \xe2\x80\x94 god of war and agriculture, the Roman new year" },
    { "gregorian.month.3.quality", "Spring equinox, awakening, aggressive new growth" },
    { "gregorian.month.4.brief", "The month of opening \xe2\x80\x94 everything that was closed begins to unfold" },
    { "gregorian.month.4.name", "April" },
    { "gregorian.month.4.origin", "Aperire (to open) \xe2\x80\x94 the earth opens, buds unfold" },
    { "gregorian.month.4.quality", "Full spring, opening, blossoming" },
    { "gregorian.month.5.brief", "The month of growth \xe2\x80\x94 the earth goddess whose name means 'she who is great'" },
    { "gregorian.month.5.name", "May" },
    { "gregorian.month.5.origin", "Maia \xe2\x80\x94 goddess of growth, mother of Mercury" },
    { "gregorian.month.5.quality", "Late spring, fertility, abundance beginning" },
    { "gregorian.month.6.brief", "The month of marriage \xe2\x80\x94 the queen of heaven blesses the longest days" },
    { "gregorian.month.6.name", "June" },
    { "gregorian.month.6.origin", "Juno \xe2\x80\x94 queen of the gods, patron of marriage" },
    { "gregorian.month.6.quality", "Summer solstice, union, peak daylight" },
    { "gregorian.month.7.brief", "The month of Caesar \xe2\x80\x94 named for the man who remade time itself" },
    { "gregorian.month.7.name", "July" },
    { "gregorian.month.7.origin", "Julius Caesar \xe2\x80\x94 reformed the calendar, deified after death" },
    { "gregorian.month.7.quality", "High summer, power, radiance" },
    { "gregorian.month.8.brief", "The month of Augustus \xe2\x80\x94 the emperor who demanded a month as grand as July" },
    { "gregorian.month.8.name", "August" },
    { "gregorian.month.8.origin", "Augustus Caesar \xe2\x80\x94 first Roman emperor, 'the revered one'" },
    { "gregorian.month.8.quality", "Late summer, harvest begins, empire at zenith" },
    { "gregorian.month.9.brief", "The seventh month \xe2\x80\x94 still carrying its old number though it is now the ninth" },
    { "gregorian.month.9.name", "September" },
    { "gregorian.month.9.origin", "Septem (seven) \xe2\x80\x94 the seventh month of the old Roman calendar" },
    { "gregorian.month.9.quality", "Autumn equinox, balance, gathering in" },
    { "gregorian.season.0.brief", "The season of becoming \xe2\x80\x94 everything that slept now wakes" },
    { "gregorian.season.0.name", "Spring" },
    { "gregorian.season.0.quality", "Expansive \xe2\x80\x94 energy rises, seeds germinate, days lengthen" },
    { "gregorian.season.0.theme", "Rebirth, growth, potential becoming actual" },
    { "gregorian.season.1.brief", "The season of being \xe2\x80\x94 the world at maximum brilliance" },
    { "gregorian.season.1.name", "Summer" },
    { "gregorian.season.1.quality", "Radiant \xe2\x80\x94 energy at peak, light dominates, life in full bloom" },
    { "gregorian.season.1.theme", "Fullness, radiance, maximum expression" },
    { "gregorian.season.2.brief", "The season of letting go \xe2\x80\x94 beauty in decay, richness in release" },
    { "gregorian.season.2.name", "Autumn" },
    { "gregorian.season.2.quality", "Contracting \xe2\x80\x94 energy turns inward, fruit ripens, leaves fall" },
    { "gregorian.season.2.theme", "Harvest, release, gratitude for what grew" },
    { "gregorian.season.3.brief", "The season of rest \xe2\x80\x94 what appears dead is dreaming" },
    { "gregorian.season.3.name", "Winter" },
    { "gregorian.season.3.quality", "Still \xe2\x80\x94 energy withdrawn to roots, silence, gestation in darkness" },
    { "gregorian.season.3.theme", "Rest, depth, the hidden seed, essential stillness" },
    { "gregorian.tpl.detail", "%1$s: %2$s. %3$s. Season: %4$s \xe2\x80\x94 %5$s. %6$s (%7$s): %8$s." },
    { "gregorian.tpl.glance", "%1$s %2$d (%3$s) \xe2\x80\x94 %4$s" },
    { "hebrew.month.1.brief", "Month of miracles and liberation \xe2\x80\x94 Passover" },
    { "hebrew.month.1.letter", "Hei" },
    { "hebrew.month.1.name", "Nisan" },
    { "hebrew.month.1.quality", "Redemption" },
    { "hebrew.month.1.sense", "Speech" },
    { "hebrew.month.1.tribe", "Judah" },
    { "hebrew.month.10.brief", "The darkest month \xe2\x80\x94 righteous indignation" },
    { "hebrew.month.10.letter", "Ayin" },
    { "hebrew.month.10.name", "Tevet" },
    { "hebrew.month.10.quality", "Transformation" },
    { "hebrew.month.10.sense", "Anger (righteous)" },
    { "hebrew.month.10.tribe", "Dan" },
    { "hebrew.month.11.brief", "New Year of Trees \xe2\x80\x94 Tu B'Shevat" },
    { "hebrew.month.11.letter", "Tzadi" },
    { "hebrew.month.11.name", "Shevat" },
    { "hebrew.month.11.quality", "Renewal" },
    { "hebrew.month.11.sense", "Taste" },
    { "hebrew.month.11.tribe", "Asher" },
    { "hebrew.month.12.brief", "Month of Purim \xe2\x80\x94 hidden miracles revealed" },
    { "hebrew.month.12.letter", "Qof" },
    { "hebrew.month.12.name", "Adar" },
    { "hebrew.month.12.quality", "Joy and reversal" },
    { "hebrew.month.12.sense", "Laughter" },
    { "hebrew.month.12.tribe", "Naphtali" },
    { "hebrew.month.13.brief", "Leap month \xe2\x80\x94 Purim celebrated here in leap years" },
    { "hebrew.month.13.letter", "Qof" },
    { "hebrew.month.13.name", "Adar II" },
    { "hebrew.month.13.quality", "Joy doubled" },
    { "hebrew.month.13.sense", "Laughter" },
    { "hebrew.month.13.tribe", "Naphtali" },
    { "hebrew.month.2.brief", "Month of natural healing \xe2\x80\x94 counting the Omer" },
    { "hebrew.month.2.letter", "Vav" },
    { "hebrew.month.2.name", "Iyar" },
    { "hebrew.month.2.quality", "Healing" },
    { "hebrew.month.2.sense", "Thought" },
    { "hebrew.month.2.tribe", "Issachar" },
    { "hebrew.month.3.brief", "Month of Torah giving \xe2\x80\x94 Shavuot" },
    { "hebrew.month.3.letter", "Zayin" },
    { "hebrew.month.3.name", "Sivan" },
    { "hebrew.month.3.quality", "Revelation" },
    { "hebrew.month.3.sense", "Motion" },
    { "hebrew.month.3.tribe", "Zebulun" },
    { "hebrew.month.4.brief", "Month of the broken tablets \xe2\x80\x94 seeing beyond" },
    { "hebrew.month.4.letter", "Chet" },
    { "hebrew.month.4.name", "Tammuz" },
    { "hebrew.month.4.quality", "Vision through darkness" },
    { "hebrew.month.4.sense", "Sight" },
    { "hebrew.month.4.tribe", "Reuben" },
    { "hebrew.month.5.brief", "Month of destruction and consolation" },
    { "hebrew.month.5.letter", "Tet" },
    { "hebrew.month.5.name", "Av" },
    { "hebrew.month.5.quality", "Transformation of sorrow" },
    { "hebrew.month.5.sense", "Hearing" },
    { "hebrew.month.5.tribe", "Simeon" },
    { "hebrew.month.6.brief", "Month of returning \xe2\x80\x94 preparation for the new year" },
    { "hebrew.month.6.letter", "Yod" },
    { "hebrew.month.6.name", "Elul" },
    { "hebrew.month.6.quality", "Repentance" },
    { "hebrew.month.6.sense", "Action" },
    { "hebrew.month.6.tribe", "Gad" },
    { "hebrew.month.7.brief", "Month of the High Holidays \xe2\x80\x94 Rosh Hashanah, Yom Kippur, Sukkot" },
    { "hebrew.month.7.letter", "Lamed" },
    { "hebrew.month.7.name", "Tishrei" },
    { "hebrew.month.7.quality", "Awe and judgment" },
    { "hebrew.month.7.sense", "Touch" },
    { "hebrew.month.7.tribe", "Ephraim" },
    { "hebrew.month.8.brief", "The bitter month \xe2\x80\x94 no holidays, only rain prayers" },
    { "hebrew.month.8.letter", "Nun" },
    { "hebrew.month.8.name", "Cheshvan" },
    { "hebrew.month.8.quality", "Quiet depth" },
    { "hebrew.month.8.sense", "Smell" },
    { "hebrew.month.8.tribe", "Manasseh" },
    { "hebrew.month.9.brief", "Month of dreams and lights \xe2\x80\x94 Hanukkah" },
    { "hebrew.month.9.letter", "Samekh" },
    { "hebrew.month.9.name", "Kislev" },
    { "hebrew.month.9.quality", "Trust and miracles" },
    { "hebrew.month.9.sense", "Sleep" },
    { "hebrew.month.9.tribe", "Benjamin" },
    { "hebrew.tpl.detail", "%1$s is the month of %2$s. Its letter is %3$s, its tribe is %4$s, its sense is %5$s. %6$s." },
    { "hebrew.tpl.glance", "%1$d %2$s %3$d \xe2\x80\x94 %4$s" },
    { "hebrew.tpl.sabbatical", " Shemitah year %1$d of 7." },
    { "islamic.month.1.brief", "Sacred month of mourning and remembrance" },
    { "islamic.month.1.event", "Ashura (10th) -- Moses delivered from Pharaoh" },
    { "islamic.month.1.name", "Muharram" },
    { "islamic.month.1.significance", "First month, month of Allah" },
    { "islamic.month.10.brief", "Month of celebration and voluntary fasting" },
    { "islamic.month.10.event", "Eid al-Fitr (1st) -- Festival of Breaking Fast" },
    { "islamic.month.10.name", "Shawwal" },
    { "islamic.month.10.significance", "Month of upliftment" },
    { "islamic.month.11.brief", "Sacred month of truce and preparation for Hajj" },
    { "islamic.month.11.event", "" },
    { "islamic.month.11.name", "Dhul Qa'dah" },
    { "islamic.month.11.significance", "Month of rest" },
    { "islamic.month.12.brief", "Sacred month of pilgrimage and sacrifice" },
    { "islamic.month.12.event", "Hajj (8th-12th), Eid al-Adha (10th) -- Festival of Sacrifice" },
    { "islamic.month.12.name", "Dhul Hijjah" },
    { "islamic.month.12.significance", "Month of pilgrimage" },
    { "islamic.month.2.brief", "Month of travel -- traditionally considered difficult" },
    { "islamic.month.2.event", "" },
    { "islamic.month.2.name", "Safar" },
    { "islamic.month.2.significance", "Month of journeying" },
    { "islamic.month.3.brief", "Month of joy and prophetic celebration" },
    { "islamic.month.3.event", "Mawlid (12th) -- birthday of Prophet Muhammad" },
    { "islamic.month.3.name", "Rabi al-Awwal" },
    { "islamic.month.3.significance", "Month of the Prophet's birth" },
    { "islamic.month.4.brief", "Quiet month of reflection and growth" },
    { "islamic.month.4.event", "" },
    { "islamic.month.4.name", "Rabi al-Thani" },
    { "islamic.month.4.significance", "Month of spring's continuation" },
    { "islamic.month.5.brief", "Month of endurance through hardship" },
    { "islamic.month.5.event", "" },
    { "islamic.month.5.name", "Jumada al-Ula" },
    { "islamic.month.5.significance", "Month of frozen water" },
    { "islamic.month.6.brief", "Month of preparation and anticipation" },
    { "islamic.month.6.event", "" },
    { "islamic.month.6.name", "Jumada al-Thani" },
    { "islamic.month.6.significance", "Month of summer's approach" },
    { "islamic.month.7.brief", "Sacred month of spiritual ascent" },
    { "islamic.month.7.event", "Isra and Mi'raj (27th) -- Night Journey" },
    { "islamic.month.7.name", "Rajab" },
    { "islamic.month.7.significance", "Month of respect" },
    { "islamic.month.8.brief", "Month of preparation for Ramadan" },
    { "islamic.month.8.event", "Laylat al-Bara'ah (15th) -- Night of Fortune" },
    { "islamic.month.8.name", "Sha'ban" },
    { "islamic.month.8.significance", "Month of division/separation" },
    { "islamic.month.9.brief", "Month of fasting, revelation, and spiritual renewal" },
    { "islamic.month.9.event", "Entire month: Sawm (fasting), Laylat al-Qadr (27th)" },
    { "islamic.month.9.name", "Ramadan" },
    { "islamic.month.9.significance", "Month of burning heat/fasting" },
    { "islamic.prayer.0.arabic", "al-Fajr" },
    { "islamic.prayer.0.meaning", "Awakening -- beginning before the world stirs" },
    { "islamic.prayer.0.name", "Fajr" },
    { "islamic.prayer.0.time_desc", "Pre-dawn, first light" },
    { "islamic.prayer.1.arabic", "al-Zuhr" },
    { "islamic.prayer.1.meaning", "Remembrance -- pausing at the day's peak" },
    { "islamic.prayer.1.name", "Dhuhr" },
    { "islamic.prayer.1.time_desc", "Midday, after zenith" },
    { "islamic.prayer.2.arabic", "al-'Asr" },
    { "islamic.prayer.2.meaning", "Reflection -- awareness as time passes" },
    { "islamic.prayer.2.name", "Asr" },
    { "islamic.prayer.2.time_desc", "Afternoon, declining sun" },
    { "islamic.prayer.3.arabic", "al-Maghrib" },
    { "islamic.prayer.3.meaning", "Gratitude -- marking the day's completion" },
    { "islamic.prayer.3.name", "Maghrib" },
    { "islamic.prayer.3.time_desc", "Just after sunset" },
    { "islamic.prayer.4.arabic", "al-'Isha" },
    { "islamic.prayer.4.meaning", "Surrender -- trust in the darkness" },
    { "islamic.prayer.4.name", "Isha" },
    { "islamic.prayer.4.time_desc", "Night, after twilight fades" },
    { "islamic.tpl.detail", "%1$s (%2$s)." },
    { "islamic.tpl.detail_event", " %1$s." },
    { "islamic.tpl.detail_sacred", " This is one of the four sacred months." },
    { "islamic.tpl.glance", "%1$d %2$s %3$d -- %4$s" },
};

#define GEN_CONTENT_EN_COUNT \
    ((int)(sizeof(gen_content_en) / sizeof(gen_content_en[0])))

/* ---- ES (642 keys) ---- */

static const i18n_entry_t gen_content_es[] = {
    { "astrology.element.0.expression", "A trav\xc3\xa9s de la acci\xc3\xb3n, la inspiraci\xc3\xb3n y el entusiasmo" },
    { "astrology.element.0.name", "Fuego" },
    { "astrology.element.0.quality", "Voluntad, esp\xc3\xadritu, fuerza creativa" },
    { "astrology.element.1.expression", "A trav\xc3\xa9s de construir, sostener y manifestar" },
    { "astrology.element.1.name", "Tierra" },
    { "astrology.element.1.quality", "Forma, materia, sabidur\xc3\xad" "a pr\xc3\xa1" "ctica" },
    { "astrology.element.2.expression", "A trav\xc3\xa9s del pensamiento, la conexi\xc3\xb3n y el intercambio" },
    { "astrology.element.2.name", "Aire" },
    { "astrology.element.2.quality", "Mente, comunicaci\xc3\xb3n, relaci\xc3\xb3n" },
    { "astrology.element.3.expression", "A trav\xc3\xa9s de la emoci\xc3\xb3n, la empat\xc3\xad" "a y la transformaci\xc3\xb3n" },
    { "astrology.element.3.name", "Agua" },
    { "astrology.element.3.quality", "Sentimiento, intuici\xc3\xb3n, el inconsciente" },
    { "astrology.modality.0.name", "Cardinal" },
    { "astrology.modality.0.quality", "Iniciaci\xc3\xb3n, liderazgo, nuevos comienzos" },
    { "astrology.modality.0.role", "Inicia la estaci\xc3\xb3n \xe2\x80\x94 la chispa que enciende" },
    { "astrology.modality.1.name", "Fijo" },
    { "astrology.modality.1.quality", "Sostenimiento, determinaci\xc3\xb3n, profundidad" },
    { "astrology.modality.1.role", "Sostiene la estaci\xc3\xb3n \xe2\x80\x94 la fuerza que perdura" },
    { "astrology.modality.2.name", "Mutable" },
    { "astrology.modality.2.quality", "Adaptaci\xc3\xb3n, flexibilidad, transici\xc3\xb3n" },
    { "astrology.modality.2.role", "Cierra la estaci\xc3\xb3n \xe2\x80\x94 la sabidur\xc3\xad" "a que libera" },
    { "astrology.sign.0.abbr", "Ari" },
    { "astrology.sign.0.archetype", "El Guerrero" },
    { "astrology.sign.0.brief", "La chispa que inicia \xe2\x80\x94 el coraje crudo de existir" },
    { "astrology.sign.0.element", "Fuego" },
    { "astrology.sign.0.keywords", "Coraje, iniciativa, independencia" },
    { "astrology.sign.0.modality", "Cardinal" },
    { "astrology.sign.0.name", "Aries" },
    { "astrology.sign.0.ruler", "Marte" },
    { "astrology.sign.0.shadow", "Impaciencia, agresi\xc3\xb3n, ego\xc3\xadsmo" },
    { "astrology.sign.1.abbr", "Tau" },
    { "astrology.sign.1.archetype", "El Constructor" },
    { "astrology.sign.1.brief", "La tierra que perdura \xe2\x80\x94 cultivo paciente de la belleza" },
    { "astrology.sign.1.element", "Tierra" },
    { "astrology.sign.1.keywords", "Estabilidad, sensualidad, persistencia" },
    { "astrology.sign.1.modality", "Fijo" },
    { "astrology.sign.1.name", "Tauro" },
    { "astrology.sign.1.ruler", "Venus" },
    { "astrology.sign.1.shadow", "Terquedad, posesividad, inercia" },
    { "astrology.sign.10.abbr", "Aqu" },
    { "astrology.sign.10.archetype", "El Visionario" },
    { "astrology.sign.10.brief", "La ola que lleva \xe2\x80\x94 libertad al servicio de todos" },
    { "astrology.sign.10.element", "Aire" },
    { "astrology.sign.10.keywords", "Innovaci\xc3\xb3n, humanidad, independencia" },
    { "astrology.sign.10.modality", "Fijo" },
    { "astrology.sign.10.name", "Acuario" },
    { "astrology.sign.10.ruler", "Urano" },
    { "astrology.sign.10.shadow", "Desapego, rebeld\xc3\xad" "a, excentricidad" },
    { "astrology.sign.11.abbr", "Pis" },
    { "astrology.sign.11.archetype", "El M\xc3\xadstico" },
    { "astrology.sign.11.brief", "El oc\xc3\xa9" "ano que disuelve \xe2\x80\x94 unidad m\xc3\xa1s all\xc3\xa1 de la separaci\xc3\xb3n" },
    { "astrology.sign.11.element", "Agua" },
    { "astrology.sign.11.keywords", "Compasi\xc3\xb3n, imaginaci\xc3\xb3n, trascendencia" },
    { "astrology.sign.11.modality", "Mutable" },
    { "astrology.sign.11.name", "Piscis" },
    { "astrology.sign.11.ruler", "Neptuno" },
    { "astrology.sign.11.shadow", "Escapismo, confusi\xc3\xb3n, martirio" },
    { "astrology.sign.2.abbr", "Gem" },
    { "astrology.sign.2.archetype", "El Mensajero" },
    { "astrology.sign.2.brief", "El aliento entre \xe2\x80\x94 conectar a trav\xc3\xa9s del lenguaje" },
    { "astrology.sign.2.element", "Aire" },
    { "astrology.sign.2.keywords", "Comunicaci\xc3\xb3n, curiosidad, adaptabilidad" },
    { "astrology.sign.2.modality", "Mutable" },
    { "astrology.sign.2.name", "G\xc3\xa9minis" },
    { "astrology.sign.2.ruler", "Mercurio" },
    { "astrology.sign.2.shadow", "Superficialidad, inquietud, duplicidad" },
    { "astrology.sign.3.abbr", "Can" },
    { "astrology.sign.3.archetype", "La Madre" },
    { "astrology.sign.3.brief", "La concha que protege \xe2\x80\x94 el sentir como forma de conocer" },
    { "astrology.sign.3.element", "Agua" },
    { "astrology.sign.3.keywords", "Nutrir, emoci\xc3\xb3n, protecci\xc3\xb3n" },
    { "astrology.sign.3.modality", "Cardinal" },
    { "astrology.sign.3.name", "C\xc3\xa1ncer" },
    { "astrology.sign.3.ruler", "Luna" },
    { "astrology.sign.3.shadow", "Apego, cambios de humor, manipulaci\xc3\xb3n" },
    { "astrology.sign.4.abbr", "Leo" },
    { "astrology.sign.4.archetype", "El Rey" },
    { "astrology.sign.4.brief", "El fuego que sostiene \xe2\x80\x94 el coraje de brillar" },
    { "astrology.sign.4.element", "Fuego" },
    { "astrology.sign.4.keywords", "Creatividad, generosidad, autoexpresi\xc3\xb3n" },
    { "astrology.sign.4.modality", "Fijo" },
    { "astrology.sign.4.name", "Leo" },
    { "astrology.sign.4.ruler", "Sol" },
    { "astrology.sign.4.shadow", "Orgullo, drama, dominaci\xc3\xb3n" },
    { "astrology.sign.5.abbr", "Vir" },
    { "astrology.sign.5.archetype", "El Sanador" },
    { "astrology.sign.5.brief", "La mano que repara \xe2\x80\x94 plenitud a trav\xc3\xa9s del discernimiento" },
    { "astrology.sign.5.element", "Tierra" },
    { "astrology.sign.5.keywords", "An\xc3\xa1lisis, servicio, refinamiento" },
    { "astrology.sign.5.modality", "Mutable" },
    { "astrology.sign.5.name", "Virgo" },
    { "astrology.sign.5.ruler", "Mercurio" },
    { "astrology.sign.5.shadow", "Cr\xc3\xadtica, ansiedad, perfeccionismo" },
    { "astrology.sign.6.abbr", "Lib" },
    { "astrology.sign.6.archetype", "El Diplom\xc3\xa1tico" },
    { "astrology.sign.6.brief", "La balanza que equilibra \xe2\x80\x94 la belleza como equilibrio" },
    { "astrology.sign.6.element", "Aire" },
    { "astrology.sign.6.keywords", "Armon\xc3\xad" "a, asociaci\xc3\xb3n, justicia" },
    { "astrology.sign.6.modality", "Cardinal" },
    { "astrology.sign.6.name", "Libra" },
    { "astrology.sign.6.ruler", "Venus" },
    { "astrology.sign.6.shadow", "Indecisi\xc3\xb3n, complacencia, evasi\xc3\xb3n" },
    { "astrology.sign.7.abbr", "Sco" },
    { "astrology.sign.7.archetype", "El Alquimista" },
    { "astrology.sign.7.brief", "La profundidad que transforma \xe2\x80\x94 la muerte como portal" },
    { "astrology.sign.7.element", "Agua" },
    { "astrology.sign.7.keywords", "Transformaci\xc3\xb3n, intensidad, profundidad" },
    { "astrology.sign.7.modality", "Fijo" },
    { "astrology.sign.7.name", "Escorpio" },
    { "astrology.sign.7.ruler", "Plut\xc3\xb3n" },
    { "astrology.sign.7.shadow", "Obsesi\xc3\xb3n, celos, destrucci\xc3\xb3n" },
    { "astrology.sign.8.abbr", "Sag" },
    { "astrology.sign.8.archetype", "El Explorador" },
    { "astrology.sign.8.brief", "La flecha que busca \xe2\x80\x94 significado m\xc3\xa1s all\xc3\xa1 del horizonte" },
    { "astrology.sign.8.element", "Fuego" },
    { "astrology.sign.8.keywords", "Filosof\xc3\xad" "a, aventura, b\xc3\xbasqueda de verdad" },
    { "astrology.sign.8.modality", "Mutable" },
    { "astrology.sign.8.name", "Sagitario" },
    { "astrology.sign.8.ruler", "J\xc3\xbapiter" },
    { "astrology.sign.8.shadow", "Exceso, dogmatismo, inquietud" },
    { "astrology.sign.9.abbr", "Cap" },
    { "astrology.sign.9.archetype", "El Anciano" },
    { "astrology.sign.9.brief", "La monta\xc3\xb1" "a que permanece \xe2\x80\x94 autoridad ganada con el tiempo" },
    { "astrology.sign.9.element", "Tierra" },
    { "astrology.sign.9.keywords", "Ambici\xc3\xb3n, disciplina, maestr\xc3\xad" "a" },
    { "astrology.sign.9.modality", "Cardinal" },
    { "astrology.sign.9.name", "Capricornio" },
    { "astrology.sign.9.ruler", "Saturno" },
    { "astrology.sign.9.shadow", "Frialdad, rigidez, crueldad" },
    { "astrology.tpl.detail", "Sol en %1$s: %2$s. %3$s. Palabras clave: %4$s. Sombra: %5$s. Elemento: %6$s (%7$s). Modalidad: %8$s (%9$s). Luna en %10$s: la naturaleza emocional es %11$s." },
    { "astrology.tpl.detail_asc", " Ascendente en %1$s: la m\xc3\xa1scara es %2$s." },
    { "astrology.tpl.glance", "Sol en %1$s \xc2\xb7 Luna en %2$s" },
    { "astrology.tpl.glance_asc", "Sol en %1$s \xc2\xb7 Luna en %2$s \xc2\xb7 %3$s Ascendente" },
    { "astronomy.phase.0.brief", "La semilla oscura \xe2\x80\x94 invisible, llena de potencial, todo comienza aqu\xc3\xad" },
    { "astronomy.phase.0.guidance", "Fijar intenciones, iniciar proyectos, descansar y reflexionar en la oscuridad" },
    { "astronomy.phase.0.name", "Luna Nueva" },
    { "astronomy.phase.0.theme", "Comienzos, siembra de semillas, fijaci\xc3\xb3n de intenciones, la oscuridad de la renovaci\xc3\xb3n" },
    { "astronomy.phase.1.brief", "La primera astilla \xe2\x80\x94 la intenci\xc3\xb3n hecha visible, la luz joven ganando fuerza" },
    { "astronomy.phase.1.guidance", "Dar el primer paso, reunir recursos, atravesar la resistencia inicial" },
    { "astronomy.phase.1.name", "Cuarto Creciente Inicial" },
    { "astronomy.phase.1.theme", "Intenci\xc3\xb3n emergente, primer compromiso, el coraje de empezar" },
    { "astronomy.phase.2.brief", "La elecci\xc3\xb3n a media luz \xe2\x80\x94 luz y oscuridad en igual medida, la encrucijada" },
    { "astronomy.phase.2.guidance", "Tomar decisiones, superar obst\xc3\xa1" "culos, comprometerse con la direcci\xc3\xb3n elegida" },
    { "astronomy.phase.2.name", "Cuarto Creciente" },
    { "astronomy.phase.2.theme", "Desaf\xc3\xado, decisi\xc3\xb3n, la crisis de la acci\xc3\xb3n" },
    { "astronomy.phase.3.brief", "Casi llena \xe2\x80\x94 la preparaci\xc3\xb3n final, el pulido antes de la cumbre" },
    { "astronomy.phase.3.guidance", "Refinar el plan, ajustar seg\xc3\xban la retroalimentaci\xc3\xb3n, confiar en el proceso" },
    { "astronomy.phase.3.name", "Luna Gibosa Creciente" },
    { "astronomy.phase.3.theme", "Refinamiento, ajuste, paciencia antes de la plenitud" },
    { "astronomy.phase.4.brief", "La luz plena \xe2\x80\x94 todo iluminado, nada oculto, la cima" },
    { "astronomy.phase.4.guidance", "Celebrar la culminaci\xc3\xb3n, ver con claridad, cosechar lo sembrado en la luna nueva" },
    { "astronomy.phase.4.name", "Luna Llena" },
    { "astronomy.phase.4.theme", "Culminaci\xc3\xb3n, iluminaci\xc3\xb3n, cosecha, revelaci\xc3\xb3n" },
    { "astronomy.phase.5.brief", "El declive generoso \xe2\x80\x94 la luz comienza a entregarse" },
    { "astronomy.phase.5.guidance", "Compartir lo aprendido, devolver, expresar gratitud por la cosecha" },
    { "astronomy.phase.5.name", "Luna Gibosa Menguante" },
    { "astronomy.phase.5.theme", "Gratitud, compartir, ense\xc3\xb1" "ar, distribuci\xc3\xb3n" },
    { "astronomy.phase.6.brief", "La liberaci\xc3\xb3n a media luz \xe2\x80\x94 luz y oscuridad de nuevo iguales, pero ahora la luz se va" },
    { "astronomy.phase.6.guidance", "Soltar lo que ya no sirve, perdonar, abrir espacio para lo nuevo" },
    { "astronomy.phase.6.name", "Cuarto Menguante" },
    { "astronomy.phase.6.theme", "Liberaci\xc3\xb3n, perd\xc3\xb3n, limpieza, la crisis de soltar" },
    { "astronomy.phase.7.brief", "El \xc3\xbaltimo susurro \xe2\x80\x94 la luz m\xc3\xa1s tenue antes de la oscuridad, la sabidur\xc3\xad" "a de la entrega" },
    { "astronomy.phase.7.guidance", "Descansar profundamente, soltar el control, prepararse para la oscuridad que viene" },
    { "astronomy.phase.7.name", "Luna Menguante" },
    { "astronomy.phase.7.theme", "Entrega, descanso, preparaci\xc3\xb3n para el vac\xc3\xado, la fase bals\xc3\xa1mica" },
    { "astronomy.planet.0.archetype", "El Embaucador-Mensajero \xe2\x80\x94 mente de mercurio, el psicopompo que une reinos" },
    { "astronomy.planet.0.brief", "El mensajero veloz \xe2\x80\x94 el m\xc3\xa1s cercano al Sol, nunca lejos de la fuente de luz" },
    { "astronomy.planet.0.deity", "Hermes / Nabu / Thoth" },
    { "astronomy.planet.0.domain", "Comunicaci\xc3\xb3n, intelecto, comercio, el mensajero entre mundos" },
    { "astronomy.planet.0.name", "Mercurio" },
    { "astronomy.planet.1.archetype", "La Amada \xe2\x80\x94 el espejo del deseo, la belleza como fuerza civilizadora" },
    { "astronomy.planet.1.brief", "El lucero del alba y del ocaso \xe2\x80\x94 el planeta m\xc3\xa1s brillante, cuya luz es prestada" },
    { "astronomy.planet.1.deity", "Afrodita / Ishtar / Freya" },
    { "astronomy.planet.1.domain", "Amor, belleza, armon\xc3\xad" "a, valores, creaci\xc3\xb3n art\xc3\xadstica" },
    { "astronomy.planet.1.name", "Venus" },
    { "astronomy.planet.2.archetype", "La Madre \xe2\x80\x94 el mundo vivo que sostiene toda observaci\xc3\xb3n del cosmos" },
    { "astronomy.planet.2.brief", "El punto azul p\xc3\xa1lido \xe2\x80\x94 el \xc3\xbanico planeta que conocemos que devuelve la mirada al cielo" },
    { "astronomy.planet.2.deity", "Gaia / Terra / Jord" },
    { "astronomy.planet.2.domain", "Hogar, encarnaci\xc3\xb3n, el cuerpo, el suelo que pisamos" },
    { "astronomy.planet.2.name", "Tierra" },
    { "astronomy.planet.3.archetype", "El Guerrero \xe2\x80\x94 la fuerza roja que lucha por lo que importa" },
    { "astronomy.planet.3.brief", "El planeta rojo \xe2\x80\x94 oxidado por el hierro, color sangre, nombrado por el dios de la guerra" },
    { "astronomy.planet.3.deity", "Ares / Nergal / Tyr" },
    { "astronomy.planet.3.domain", "Acci\xc3\xb3n, impulso, conflicto, coraje, la voluntad de afirmar" },
    { "astronomy.planet.3.name", "Marte" },
    { "astronomy.planet.4.archetype", "El Rey \xe2\x80\x94 el cuerpo m\xc3\xa1s grande del sistema solar despu\xc3\xa9s del Sol, protector y juez" },
    { "astronomy.planet.4.brief", "El gran ben\xc3\xa9" "fico \xe2\x80\x94 m\xc3\xa1s masivo que todos los dem\xc3\xa1s planetas juntos" },
    { "astronomy.planet.4.deity", "Zeus / Marduk / Thor" },
    { "astronomy.planet.4.domain", "Expansi\xc3\xb3n, sabidur\xc3\xad" "a, generosidad, ley, el gran ben\xc3\xa9" "fico" },
    { "astronomy.planet.4.name", "J\xc3\xbapiter" },
    { "astronomy.planet.5.archetype", "El Anciano \xe2\x80\x94 el l\xc3\xadmite anillado, la lecci\xc3\xb3n que no puede evitarse" },
    { "astronomy.planet.5.brief", "El maestro anillado \xe2\x80\x94 bello y severo, el se\xc3\xb1or del tiempo y la consecuencia" },
    { "astronomy.planet.5.deity", "Kronos / Ninurta / Loki" },
    { "astronomy.planet.5.domain", "Estructura, limitaci\xc3\xb3n, tiempo, disciplina, el gran maestro" },
    { "astronomy.planet.5.name", "Saturno" },
    { "astronomy.planet.6.archetype", "El Despertador \xe2\x80\x94 el rayo del cambio, la fuerza que rompe para liberar" },
    { "astronomy.planet.6.brief", "El rebelde inclinado \xe2\x80\x94 rodando de costado, el planeta que rompe toda regla" },
    { "astronomy.planet.6.deity", "Ouranos / padre del cielo" },
    { "astronomy.planet.6.domain", "Revoluci\xc3\xb3n, originalidad, percepci\xc3\xb3n s\xc3\xba" "bita, lo inesperado" },
    { "astronomy.planet.6.name", "Urano" },
    { "astronomy.planet.7.archetype", "El M\xc3\xadstico \xe2\x80\x94 el oc\xc3\xa9" "ano que disuelve donde las fronteras dejan de existir" },
    { "astronomy.planet.7.brief", "El so\xc3\xb1" "ador azul \xe2\x80\x94 el planeta mayor m\xc3\xa1s lejano, donde el sistema solar se desvanece en misterio" },
    { "astronomy.planet.7.deity", "Poseid\xc3\xb3n / Ea / Njord" },
    { "astronomy.planet.7.domain", "Imaginaci\xc3\xb3n, trascendencia, ilusi\xc3\xb3n, el inconsciente oce\xc3\xa1nico" },
    { "astronomy.planet.7.name", "Neptuno" },
    { "astronomy.tpl.detail", "Planeta: %1$s. Deidad: %2$s. Dominio: %3$s. %4$s." },
    { "astronomy.tpl.detail_moon", " Luna: %1$s \xe2\x80\x94 %2$s." },
    { "astronomy.tpl.detail_planet", "Planeta: %1$s. Deidad: %2$s. Dominio: %3$s. %4$s." },
    { "astronomy.tpl.detail_retro", " RETR\xc3\x93GRADO: movimiento aparente hacia atr\xc3\xa1s \xe2\x80\x94 los temas del planeta se vuelven hacia adentro para revisi\xc3\xb3n." },
    { "astronomy.tpl.detail_retrograde", " RETR\xc3\x93GRADO: movimiento aparente hacia atr\xc3\xa1s \xe2\x80\x94 los temas del planeta se vuelven hacia adentro para revisi\xc3\xb3n." },
    { "astronomy.tpl.glance", "%1$s \xe2\x80\x94 %2$s" },
    { "astronomy.tpl.glance_moon", "%1$s \xe2\x80\x94 %2$s + %3$s" },
    { "astronomy.tpl.glance_phase", "%1$s \xe2\x80\x94 %2$s + %3$s" },
    { "astronomy.tpl.glance_retro", "%1$s (retr\xc3\xb3grado) \xe2\x80\x94 %2$s" },
    { "astronomy.tpl.glance_retrograde", "%1$s (retr\xc3\xb3grado) \xe2\x80\x94 %2$s" },
    { "buddhist.kalpa.0.description", "Mundos surgen de la vacuidad \xe2\x80\x94 la materia se condensa, los seres toman forma" },
    { "buddhist.kalpa.0.meaning", "La respiraci\xc3\xb3n c\xc3\xb3smica hacia adentro \xe2\x80\x94 la creaci\xc3\xb3n como surgimiento inevitable" },
    { "buddhist.kalpa.0.name", "Formaci\xc3\xb3n" },
    { "buddhist.kalpa.0.pali", "Vivatta" },
    { "buddhist.kalpa.1.description", "Los seres viven, mueren y renacen \xe2\x80\x94 la rueda gira" },
    { "buddhist.kalpa.1.meaning", "La era presente \xe2\x80\x94 la experiencia sintiente en todo su sufrimiento y belleza" },
    { "buddhist.kalpa.1.name", "Existencia" },
    { "buddhist.kalpa.1.pali", "Vivattathaayi" },
    { "buddhist.kalpa.2.description", "Los mundos se disuelven por fuego, agua o viento" },
    { "buddhist.kalpa.2.meaning", "La respiraci\xc3\xb3n c\xc3\xb3smica hacia afuera \xe2\x80\x94 todo lo condicionado es impermanente" },
    { "buddhist.kalpa.2.name", "Destrucci\xc3\xb3n" },
    { "buddhist.kalpa.2.pali", "Samvatta" },
    { "buddhist.kalpa.3.description", "Vasta oscuridad entre mundos \xe2\x80\x94 nada permanece" },
    { "buddhist.kalpa.3.meaning", "El gran reposo \xe2\x80\x94 potencial sin forma, como un sue\xc3\xb1o sin sue\xc3\xb1os" },
    { "buddhist.kalpa.3.name", "Vacuidad" },
    { "buddhist.kalpa.3.pali", "Samvattathaayi" },
    { "buddhist.month.1.meaning", "Mes del despertar \xe2\x80\x94 la naturaleza se agita" },
    { "buddhist.month.1.observance", "Songkran/A\xc3\xb1o Nuevo en algunas tradiciones" },
    { "buddhist.month.1.pali_name", "Citta" },
    { "buddhist.month.1.season", "Calurosa" },
    { "buddhist.month.10.meaning", "Mes del alimento" },
    { "buddhist.month.10.observance", "" },
    { "buddhist.month.10.pali_name", "Phussa" },
    { "buddhist.month.10.season", "Fresca" },
    { "buddhist.month.11.meaning", "Mes de la Sangha \xe2\x80\x94 comunidad del despertar" },
    { "buddhist.month.11.observance", "Magha Puja \xe2\x80\x94 D\xc3\xad" "a de la Sangha, 1250 monjes reunidos" },
    { "buddhist.month.11.pali_name", "Magha" },
    { "buddhist.month.11.season", "Fresca" },
    { "buddhist.month.12.meaning", "Mes de la completud \xe2\x80\x94 el ciclo se prepara para renovarse" },
    { "buddhist.month.12.observance", "" },
    { "buddhist.month.12.pali_name", "Phalguna" },
    { "buddhist.month.12.season", "Calurosa" },
    { "buddhist.month.2.meaning", "El mes m\xc3\xa1s sagrado \xe2\x80\x94 triple aniversario" },
    { "buddhist.month.2.observance", "Vesak \xe2\x80\x94 nacimiento, iluminaci\xc3\xb3n y parinibbana del Buda" },
    { "buddhist.month.2.pali_name", "Vesakha" },
    { "buddhist.month.2.season", "Calurosa" },
    { "buddhist.month.3.meaning", "Mes de resistencia ante el calor" },
    { "buddhist.month.3.observance", "" },
    { "buddhist.month.3.pali_name", "Jettha" },
    { "buddhist.month.3.season", "Calurosa" },
    { "buddhist.month.4.meaning", "Mes de la primera ense\xc3\xb1" "anza \xe2\x80\x94 la Rueda gira" },
    { "buddhist.month.4.observance", "Asalha Puja \xe2\x80\x94 Primer Serm\xc3\xb3n, Dhammacakkappavattana" },
    { "buddhist.month.4.pali_name", "Asalha" },
    { "buddhist.month.4.season", "Lluviosa" },
    { "buddhist.month.5.meaning", "Mes de recogimiento \xe2\x80\x94 los mon\xc3\xa1sticos entran en retiro" },
    { "buddhist.month.5.observance", "Comienza Vassa \xe2\x80\x94 inicio del Retiro de Lluvias" },
    { "buddhist.month.5.pali_name", "Savana" },
    { "buddhist.month.5.season", "Lluviosa" },
    { "buddhist.month.6.meaning", "Mes de pr\xc3\xa1" "ctica devota" },
    { "buddhist.month.6.observance", "Vassa contin\xc3\xba" "a" },
    { "buddhist.month.6.pali_name", "Bhaddapada" },
    { "buddhist.month.6.season", "Lluviosa" },
    { "buddhist.month.7.meaning", "Mes de la invitaci\xc3\xb3n \xe2\x80\x94 reconciliaci\xc3\xb3n comunitaria" },
    { "buddhist.month.7.observance", "Vassa termina \xe2\x80\x94 ceremonia de Pavarana" },
    { "buddhist.month.7.pali_name", "Assayuja" },
    { "buddhist.month.7.season", "Lluviosa" },
    { "buddhist.month.8.meaning", "Mes de la generosidad \xe2\x80\x94 dana y gratitud" },
    { "buddhist.month.8.observance", "Kathina \xe2\x80\x94 ofrenda de t\xc3\xbanicas a los mon\xc3\xa1sticos" },
    { "buddhist.month.8.pali_name", "Kattika" },
    { "buddhist.month.8.season", "Fresca" },
    { "buddhist.month.9.meaning", "Mes del sendero \xe2\x80\x94 caminar en silencio" },
    { "buddhist.month.9.observance", "" },
    { "buddhist.month.9.pali_name", "Maggasira" },
    { "buddhist.month.9.season", "Fresca" },
    { "buddhist.tpl.detail", "%1$s: %2$s." },
    { "buddhist.tpl.detail_kalpa", " Fase de %1$s (%2$s): %3$s." },
    { "buddhist.tpl.detail_uposatha", " %1$s. %2$s." },
    { "buddhist.tpl.glance", "EB %1$d \xc2\xb7 %2$s \xc2\xb7 %3$s" },
    { "buddhist.tpl.glance_uposatha", "EB %1$d \xc2\xb7 %2$s \xc2\xb7 %3$s" },
    { "buddhist.uposatha.0.meaning", "Un d\xc3\xad" "a ordinario en el ciclo" },
    { "buddhist.uposatha.0.name", "Sin Observancia" },
    { "buddhist.uposatha.0.practice", "D\xc3\xad" "a regular" },
    { "buddhist.uposatha.1.meaning", "La oscuridad como potencial \xe2\x80\x94 el momento semilla antes de la renovaci\xc3\xb3n" },
    { "buddhist.uposatha.1.name", "Observancia de Luna Nueva" },
    { "buddhist.uposatha.1.practice", "Los mon\xc3\xa1sticos recitan el Patimokkha; los laicos observan 8 preceptos" },
    { "buddhist.uposatha.2.meaning", "Iluminaci\xc3\xb3n \xe2\x80\x94 el nacimiento, la iluminaci\xc3\xb3n y el parinibbana del Buda, todos en lunas llenas" },
    { "buddhist.uposatha.2.name", "Observancia de Luna Llena" },
    { "buddhist.uposatha.2.practice", "La m\xc3\xa1s importante \xe2\x80\x94 recitaci\xc3\xb3n completa del Patimokkha, pr\xc3\xa1" "ctica intensiva" },
    { "buddhist.uposatha.3.meaning", "Luz creciente \xe2\x80\x94 esfuerzo y aspiraci\xc3\xb3n en construcci\xc3\xb3n" },
    { "buddhist.uposatha.3.name", "Media Luna Creciente" },
    { "buddhist.uposatha.3.practice", "Observancia menor, meditaci\xc3\xb3n y reflexi\xc3\xb3n" },
    { "buddhist.uposatha.4.meaning", "Liberaci\xc3\xb3n \xe2\x80\x94 sabidur\xc3\xad" "a de la impermanencia, soltar" },
    { "buddhist.uposatha.4.name", "Media Luna Menguante" },
    { "buddhist.uposatha.4.practice", "Observancia menor, pr\xc3\xa1" "ctica de soltar" },
    { "chinese.animal.0.archetype", "El Estratega" },
    { "chinese.animal.0.brief", "Primero en el ciclo \xe2\x80\x94 la mente astuta que encuentra oportunidad en el caos" },
    { "chinese.animal.0.challenges", "Astuto, inquieto, manipulador" },
    { "chinese.animal.0.compatibility", "Drag\xc3\xb3n, Mono, Buey" },
    { "chinese.animal.0.name", "Rata" },
    { "chinese.animal.0.strengths", "Ingenioso, agudo, adaptable" },
    { "chinese.animal.1.archetype", "El Constante" },
    { "chinese.animal.1.brief", "La fuerza que ara \xe2\x80\x94 la resistencia paciente conquista todo" },
    { "chinese.animal.1.challenges", "Terco, r\xc3\xadgido, lento al cambio" },
    { "chinese.animal.1.compatibility", "Rata, Serpiente, Gallo" },
    { "chinese.animal.1.name", "Buey" },
    { "chinese.animal.1.strengths", "Paciente, confiable, met\xc3\xb3" "dico" },
    { "chinese.animal.10.archetype", "El Guardi\xc3\xa1n" },
    { "chinese.animal.10.brief", "La fidelidad que ancla \xe2\x80\x94 la lealtad como la virtud m\xc3\xa1s alta" },
    { "chinese.animal.10.challenges", "Ansioso, terco, cr\xc3\xadtico" },
    { "chinese.animal.10.compatibility", "Tigre, Conejo, Caballo" },
    { "chinese.animal.10.name", "Perro" },
    { "chinese.animal.10.strengths", "Leal, honesto, protector" },
    { "chinese.animal.11.archetype", "El Generoso" },
    { "chinese.animal.11.brief", "La abundancia que desborda \xe2\x80\x94 generosidad sin c\xc3\xa1lculo" },
    { "chinese.animal.11.challenges", "Ingenuo, indulgente, cr\xc3\xa9" "dulo" },
    { "chinese.animal.11.compatibility", "Conejo, Cabra, Tigre" },
    { "chinese.animal.11.name", "Cerdo" },
    { "chinese.animal.11.strengths", "Amable, generoso, optimista" },
    { "chinese.animal.2.archetype", "El Valiente" },
    { "chinese.animal.2.brief", "El rugido que despierta \xe2\x80\x94 acci\xc3\xb3n sin miedo al servicio de la justicia" },
    { "chinese.animal.2.challenges", "Temerario, vol\xc3\xa1til, dominante" },
    { "chinese.animal.2.compatibility", "Caballo, Perro, Cerdo" },
    { "chinese.animal.2.name", "Tigre" },
    { "chinese.animal.2.strengths", "Valiente, apasionado, seguro" },
    { "chinese.animal.3.archetype", "El Diplom\xc3\xa1tico" },
    { "chinese.animal.3.brief", "La gracia que desarma \xe2\x80\x94 la suavidad como forma de poder" },
    { "chinese.animal.3.challenges", "T\xc3\xadmido, superficial, escapista" },
    { "chinese.animal.3.compatibility", "Cabra, Cerdo, Perro" },
    { "chinese.animal.3.name", "Conejo" },
    { "chinese.animal.3.strengths", "Elegante, gentil, compasivo" },
    { "chinese.animal.4.archetype", "El Emperador" },
    { "chinese.animal.4.brief", "El \xc3\xbanico animal m\xc3\xadtico \xe2\x80\x94 el sue\xc3\xb1o de trascendencia hecho manifiesto" },
    { "chinese.animal.4.challenges", "Arrogante, exigente, impulsivo" },
    { "chinese.animal.4.compatibility", "Rata, Mono, Gallo" },
    { "chinese.animal.4.name", "Drag\xc3\xb3n" },
    { "chinese.animal.4.strengths", "Carism\xc3\xa1tico, ambicioso, visionario" },
    { "chinese.animal.5.archetype", "El Fil\xc3\xb3sofo" },
    { "chinese.animal.5.brief", "La espiral que acierta \xe2\x80\x94 sabidur\xc3\xad" "a profunda bajo una superficie quieta" },
    { "chinese.animal.5.challenges", "Secreto, suspicaz, posesivo" },
    { "chinese.animal.5.compatibility", "Buey, Gallo, Drag\xc3\xb3n" },
    { "chinese.animal.5.name", "Serpiente" },
    { "chinese.animal.5.strengths", "Sabio, intuitivo, elegante" },
    { "chinese.animal.6.archetype", "El Esp\xc3\xadritu Libre" },
    { "chinese.animal.6.brief", "El galope que libera \xe2\x80\x94 la libertad como forma de ser" },
    { "chinese.animal.6.challenges", "Impaciente, irresponsable, ansioso" },
    { "chinese.animal.6.compatibility", "Tigre, Cabra, Perro" },
    { "chinese.animal.6.name", "Caballo" },
    { "chinese.animal.6.strengths", "En\xc3\xa9rgico, independiente, aventurero" },
    { "chinese.animal.7.archetype", "El Artista" },
    { "chinese.animal.7.brief", "El coraz\xc3\xb3n que crea \xe2\x80\x94 belleza nacida de la sensibilidad" },
    { "chinese.animal.7.challenges", "Indeciso, pesimista, dependiente" },
    { "chinese.animal.7.compatibility", "Conejo, Caballo, Cerdo" },
    { "chinese.animal.7.name", "Cabra" },
    { "chinese.animal.7.strengths", "Creativo, gentil, emp\xc3\xa1tico" },
    { "chinese.animal.8.archetype", "El Inventor" },
    { "chinese.animal.8.brief", "La mente que juega \xe2\x80\x94 genialidad disfrazada de travesura" },
    { "chinese.animal.8.challenges", "Tramposo, arrogante, poco fiable" },
    { "chinese.animal.8.compatibility", "Rata, Drag\xc3\xb3n, Serpiente" },
    { "chinese.animal.8.name", "Mono" },
    { "chinese.animal.8.strengths", "Astuto, juguet\xc3\xb3n, vers\xc3\xa1til" },
    { "chinese.animal.9.archetype", "El Observador" },
    { "chinese.animal.9.brief", "La voz que proclama verdad \xe2\x80\x94 precisi\xc3\xb3n en todas las cosas" },
    { "chinese.animal.9.challenges", "Cr\xc3\xadtico, \xc3\xa1spero, vanidoso" },
    { "chinese.animal.9.compatibility", "Buey, Serpiente, Drag\xc3\xb3n" },
    { "chinese.animal.9.name", "Gallo" },
    { "chinese.animal.9.strengths", "Honesto, diligente, perceptivo" },
    { "chinese.element.0.expression", "A trav\xc3\xa9s de la creatividad, la visi\xc3\xb3n y el movimiento ascendente" },
    { "chinese.element.0.name", "Madera" },
    { "chinese.element.0.nature", "Crecimiento, expansi\xc3\xb3n, benevolencia" },
    { "chinese.element.0.season", "Primavera" },
    { "chinese.element.1.expression", "A trav\xc3\xa9s del entusiasmo, la calidez y la iluminaci\xc3\xb3n" },
    { "chinese.element.1.name", "Fuego" },
    { "chinese.element.1.nature", "Pasi\xc3\xb3n, transformaci\xc3\xb3n, brillantez" },
    { "chinese.element.1.season", "Verano" },
    { "chinese.element.2.expression", "A trav\xc3\xa9s del arraigo, el cuidado y la atenci\xc3\xb3n pr\xc3\xa1" "ctica" },
    { "chinese.element.2.name", "Tierra" },
    { "chinese.element.2.nature", "Estabilidad, alimento, centramiento" },
    { "chinese.element.2.season", "Final del Verano" },
    { "chinese.element.3.expression", "A trav\xc3\xa9s del refinamiento, el soltar y el enfoque agudo" },
    { "chinese.element.3.name", "Metal" },
    { "chinese.element.3.nature", "Precisi\xc3\xb3n, claridad, rectitud" },
    { "chinese.element.3.season", "Oto\xc3\xb1o" },
    { "chinese.element.4.expression", "A trav\xc3\xa9s del fluir, la quietud y el poder de ceder" },
    { "chinese.element.4.name", "Agua" },
    { "chinese.element.4.nature", "Sabidur\xc3\xad" "a, profundidad, adaptabilidad" },
    { "chinese.element.4.season", "Invierno" },
    { "chinese.polarity.yang", "Yang" },
    { "chinese.polarity.yin", "Yin" },
    { "chinese.tpl.detail", "%1$s %2$s: %3$s. Fortalezas: %4$s. Desaf\xc3\xados: %5$s. Mejor con: %6$s. Elemento: %7$s (%8$s) \xe2\x80\x94 %9$s. A\xc3\xb1o %10$d de 60." },
    { "chinese.tpl.glance", "%1$s %2$s (%3$s) \xe2\x80\x94 %4$s" },
    { "gregorian.day.0.brief", "El d\xc3\xad" "a de la Luna \xe2\x80\x94 intuici\xc3\xb3n, emoci\xc3\xb3n, las mareas interiores" },
    { "gregorian.day.0.name", "Lunes" },
    { "gregorian.day.0.origin", "Del lat\xc3\xadn Lunae dies (d\xc3\xad" "a de la Luna)" },
    { "gregorian.day.0.planet", "Luna" },
    { "gregorian.day.1.brief", "El d\xc3\xad" "a de Marte \xe2\x80\x94 coraje, acci\xc3\xb3n, la determinaci\xc3\xb3n del guerrero" },
    { "gregorian.day.1.name", "Martes" },
    { "gregorian.day.1.origin", "Del lat\xc3\xadn Martis dies (d\xc3\xad" "a de Marte)" },
    { "gregorian.day.1.planet", "Marte" },
    { "gregorian.day.2.brief", "El d\xc3\xad" "a de Mercurio \xe2\x80\x94 comunicaci\xc3\xb3n, ingenio, la astucia del mensajero" },
    { "gregorian.day.2.name", "Mi\xc3\xa9rcoles" },
    { "gregorian.day.2.origin", "Del lat\xc3\xadn Mercurii dies (d\xc3\xad" "a de Mercurio)" },
    { "gregorian.day.2.planet", "Mercurio" },
    { "gregorian.day.3.brief", "El d\xc3\xad" "a de J\xc3\xbapiter \xe2\x80\x94 expansi\xc3\xb3n, abundancia, la generosidad del trueno" },
    { "gregorian.day.3.name", "Jueves" },
    { "gregorian.day.3.origin", "Del lat\xc3\xadn Iovis dies (d\xc3\xad" "a de J\xc3\xbapiter)" },
    { "gregorian.day.3.planet", "J\xc3\xbapiter" },
    { "gregorian.day.4.brief", "El d\xc3\xad" "a de Venus \xe2\x80\x94 amor, belleza, la diosa del deseo" },
    { "gregorian.day.4.name", "Viernes" },
    { "gregorian.day.4.origin", "Del lat\xc3\xadn Veneris dies (d\xc3\xad" "a de Venus)" },
    { "gregorian.day.4.planet", "Venus" },
    { "gregorian.day.5.brief", "El d\xc3\xad" "a de Saturno \xe2\x80\x94 disciplina, estructura, la lecci\xc3\xb3n del maestro" },
    { "gregorian.day.5.name", "S\xc3\xa1" "bado" },
    { "gregorian.day.5.origin", "Del lat\xc3\xadn Sabbatum (d\xc3\xad" "a de descanso)" },
    { "gregorian.day.5.planet", "Saturno" },
    { "gregorian.day.6.brief", "El d\xc3\xad" "a del Sol \xe2\x80\x94 vitalidad, soberan\xc3\xad" "a, el centro de todas las \xc3\xb3rbitas" },
    { "gregorian.day.6.name", "Domingo" },
    { "gregorian.day.6.origin", "Del lat\xc3\xadn Dominicus dies (d\xc3\xad" "a del Se\xc3\xb1or)" },
    { "gregorian.day.6.planet", "Sol" },
    { "gregorian.month.1.brief", "El mes de las puertas \xe2\x80\x94 un rostro mira hacia atr\xc3\xa1s, otro hacia adelante" },
    { "gregorian.month.1.name", "Enero" },
    { "gregorian.month.1.origin", "Janus \xe2\x80\x94 dios bifronte de los comienzos, los umbrales y las transiciones" },
    { "gregorian.month.1.quality", "Pleno invierno, reflexi\xc3\xb3n, nuevos comienzos" },
    { "gregorian.month.10.brief", "El octavo mes \xe2\x80\x94 el mundo se recoge mientras la luz se contrae" },
    { "gregorian.month.10.name", "Octubre" },
    { "gregorian.month.10.origin", "Octo (ocho) \xe2\x80\x94 el octavo mes del antiguo calendario romano" },
    { "gregorian.month.10.quality", "Mediados de oto\xc3\xb1o, profundizaci\xc3\xb3n, transformaci\xc3\xb3n" },
    { "gregorian.month.11.brief", "El noveno mes \xe2\x80\x94 se honra a los muertos mientras el a\xc3\xb1o envejece" },
    { "gregorian.month.11.name", "Noviembre" },
    { "gregorian.month.11.origin", "Novem (nueve) \xe2\x80\x94 el noveno mes del antiguo calendario romano" },
    { "gregorian.month.11.quality", "Fin de oto\xc3\xb1o, memoria, preparaci\xc3\xb3n para la oscuridad" },
    { "gregorian.month.12.brief", "El d\xc3\xa9" "cimo mes \xe2\x80\x94 en la oscuridad m\xc3\xa1s profunda, los romanos festejaban y el sol renac\xc3\xad" "a" },
    { "gregorian.month.12.name", "Diciembre" },
    { "gregorian.month.12.origin", "Decem (diez) \xe2\x80\x94 el d\xc3\xa9" "cimo mes del antiguo calendario romano" },
    { "gregorian.month.12.quality", "Solsticio de invierno, Saturnalia, el retorno de la luz" },
    { "gregorian.month.2.brief", "El mes de la purificaci\xc3\xb3n \xe2\x80\x94 los \xc3\xbaltimos fuegos antes del nuevo crecimiento" },
    { "gregorian.month.2.name", "Febrero" },
    { "gregorian.month.2.origin", "Februa \xe2\x80\x94 festival romano de purificaci\xc3\xb3n (Lupercalia)" },
    { "gregorian.month.2.quality", "Fin de invierno, purificaci\xc3\xb3n, preparaci\xc3\xb3n para la primavera" },
    { "gregorian.month.3.brief", "El mes de Marte \xe2\x80\x94 aqu\xc3\xad comenzaba el a\xc3\xb1o romano, con guerra y siembra por igual" },
    { "gregorian.month.3.name", "Marzo" },
    { "gregorian.month.3.origin", "Mars \xe2\x80\x94 dios de la guerra y la agricultura, el a\xc3\xb1o nuevo romano" },
    { "gregorian.month.3.quality", "Equinoccio de primavera, despertar, crecimiento vigoroso" },
    { "gregorian.month.4.brief", "El mes de la apertura \xe2\x80\x94 todo lo que estaba cerrado comienza a desplegarse" },
    { "gregorian.month.4.name", "Abril" },
    { "gregorian.month.4.origin", "Aperire (abrir) \xe2\x80\x94 la tierra se abre, los brotes se despliegan" },
    { "gregorian.month.4.quality", "Plena primavera, apertura, floraci\xc3\xb3n" },
    { "gregorian.month.5.brief", "El mes del crecimiento \xe2\x80\x94 la diosa de la tierra cuyo nombre significa 'la que es grande'" },
    { "gregorian.month.5.name", "Mayo" },
    { "gregorian.month.5.origin", "Maia \xe2\x80\x94 diosa del crecimiento, madre de Mercurio" },
    { "gregorian.month.5.quality", "Fin de primavera, fertilidad, abundancia naciente" },
    { "gregorian.month.6.brief", "El mes del matrimonio \xe2\x80\x94 la reina del cielo bendice los d\xc3\xad" "as m\xc3\xa1s largos" },
    { "gregorian.month.6.name", "Junio" },
    { "gregorian.month.6.origin", "Juno \xe2\x80\x94 reina de los dioses, patrona del matrimonio" },
    { "gregorian.month.6.quality", "Solsticio de verano, uni\xc3\xb3n, m\xc3\xa1xima luz diurna" },
    { "gregorian.month.7.brief", "El mes de C\xc3\xa9sar \xe2\x80\x94 nombrado por el hombre que rehizo el tiempo mismo" },
    { "gregorian.month.7.name", "Julio" },
    { "gregorian.month.7.origin", "Julius Caesar \xe2\x80\x94 reform\xc3\xb3 el calendario, deificado tras su muerte" },
    { "gregorian.month.7.quality", "Pleno verano, poder, resplandor" },
    { "gregorian.month.8.brief", "El mes de Augusto \xe2\x80\x94 el emperador que exigi\xc3\xb3 un mes tan grandioso como julio" },
    { "gregorian.month.8.name", "Agosto" },
    { "gregorian.month.8.origin", "Augustus Caesar \xe2\x80\x94 primer emperador romano, 'el venerado'" },
    { "gregorian.month.8.quality", "Fin de verano, comienza la cosecha, el imperio en su cenit" },
    { "gregorian.month.9.brief", "El s\xc3\xa9ptimo mes \xe2\x80\x94 a\xc3\xban porta su viejo n\xc3\xbamero aunque ahora es el noveno" },
    { "gregorian.month.9.name", "Septiembre" },
    { "gregorian.month.9.origin", "Septem (siete) \xe2\x80\x94 el s\xc3\xa9ptimo mes del antiguo calendario romano" },
    { "gregorian.month.9.quality", "Equinoccio de oto\xc3\xb1o, equilibrio, recogimiento" },
    { "gregorian.season.0.brief", "La estaci\xc3\xb3n del devenir \xe2\x80\x94 todo lo que dorm\xc3\xad" "a ahora despierta" },
    { "gregorian.season.0.name", "Primavera" },
    { "gregorian.season.0.quality", "Expansiva \xe2\x80\x94 la energ\xc3\xad" "a asciende, las semillas germinan, los d\xc3\xad" "as se alargan" },
    { "gregorian.season.0.theme", "Renacimiento, crecimiento, lo potencial se hace real" },
    { "gregorian.season.1.brief", "La estaci\xc3\xb3n del ser \xe2\x80\x94 el mundo en su m\xc3\xa1ximo esplendor" },
    { "gregorian.season.1.name", "Verano" },
    { "gregorian.season.1.quality", "Radiante \xe2\x80\x94 energ\xc3\xad" "a en su apogeo, la luz domina, la vida en plena floraci\xc3\xb3n" },
    { "gregorian.season.1.theme", "Plenitud, resplandor, m\xc3\xa1xima expresi\xc3\xb3n" },
    { "gregorian.season.2.brief", "La estaci\xc3\xb3n del soltar \xe2\x80\x94 belleza en la ca\xc3\xad" "da, riqueza en la entrega" },
    { "gregorian.season.2.name", "Oto\xc3\xb1o" },
    { "gregorian.season.2.quality", "Contractiva \xe2\x80\x94 la energ\xc3\xad" "a se recoge, el fruto madura, las hojas caen" },
    { "gregorian.season.2.theme", "Cosecha, liberaci\xc3\xb3n, gratitud por lo que creci\xc3\xb3" },
    { "gregorian.season.3.brief", "La estaci\xc3\xb3n del reposo \xe2\x80\x94 lo que parece muerto est\xc3\xa1 so\xc3\xb1" "ando" },
    { "gregorian.season.3.name", "Invierno" },
    { "gregorian.season.3.quality", "Quieta \xe2\x80\x94 energ\xc3\xad" "a recogida en las ra\xc3\xad" "ces, silencio, gestaci\xc3\xb3n en la oscuridad" },
    { "gregorian.season.3.theme", "Descanso, profundidad, la semilla oculta, quietud esencial" },
    { "gregorian.tpl.detail", "%1$s: %2$s. %3$s. Estaci\xc3\xb3n: %4$s \xe2\x80\x94 %5$s. %6$s (%7$s): %8$s." },
    { "gregorian.tpl.glance", "%1$s %2$d (%3$s) \xe2\x80\x94 %4$s" },
    { "hebrew.month.1.brief", "Mes de milagros y liberaci\xc3\xb3n \xe2\x80\x94 Pesaj" },
    { "hebrew.month.1.letter", "Hei" },
    { "hebrew.month.1.name", "Nisan" },
    { "hebrew.month.1.quality", "Redenci\xc3\xb3n" },
    { "hebrew.month.1.sense", "Habla" },
    { "hebrew.month.1.tribe", "Jud\xc3\xa1" },
    { "hebrew.month.10.brief", "El mes m\xc3\xa1s oscuro \xe2\x80\x94 indignaci\xc3\xb3n justa" },
    { "hebrew.month.10.letter", "Ayin" },
    { "hebrew.month.10.name", "Tevet" },
    { "hebrew.month.10.quality", "Transformaci\xc3\xb3n" },
    { "hebrew.month.10.sense", "Ira (justa)" },
    { "hebrew.month.10.tribe", "Dan" },
    { "hebrew.month.11.brief", "A\xc3\xb1o Nuevo de los \xc3\x81rboles \xe2\x80\x94 Tu BiShvat" },
    { "hebrew.month.11.letter", "Tzadi" },
    { "hebrew.month.11.name", "Shevat" },
    { "hebrew.month.11.quality", "Renovaci\xc3\xb3n" },
    { "hebrew.month.11.sense", "Gusto" },
    { "hebrew.month.11.tribe", "Aser" },
    { "hebrew.month.12.brief", "Mes de Purim \xe2\x80\x94 milagros ocultos revelados" },
    { "hebrew.month.12.letter", "Qof" },
    { "hebrew.month.12.name", "Adar" },
    { "hebrew.month.12.quality", "Alegr\xc3\xad" "a y transformaci\xc3\xb3n" },
    { "hebrew.month.12.sense", "Risa" },
    { "hebrew.month.12.tribe", "Neftal\xc3\xad" },
    { "hebrew.month.13.brief", "Mes bisiesto \xe2\x80\x94 Purim se celebra aqu\xc3\xad en a\xc3\xb1os bisiestos" },
    { "hebrew.month.13.letter", "Qof" },
    { "hebrew.month.13.name", "Adar II" },
    { "hebrew.month.13.quality", "Alegr\xc3\xad" "a duplicada" },
    { "hebrew.month.13.sense", "Risa" },
    { "hebrew.month.13.tribe", "Neftal\xc3\xad" },
    { "hebrew.month.2.brief", "Mes de sanaci\xc3\xb3n natural \xe2\x80\x94 la cuenta del \xc3\x93mer" },
    { "hebrew.month.2.letter", "Vav" },
    { "hebrew.month.2.name", "Iyar" },
    { "hebrew.month.2.quality", "Sanaci\xc3\xb3n" },
    { "hebrew.month.2.sense", "Pensamiento" },
    { "hebrew.month.2.tribe", "Isacar" },
    { "hebrew.month.3.brief", "Mes de la entrega de la Tor\xc3\xa1 \xe2\x80\x94 Shavuot" },
    { "hebrew.month.3.letter", "Zayin" },
    { "hebrew.month.3.name", "Sivan" },
    { "hebrew.month.3.quality", "Revelaci\xc3\xb3n" },
    { "hebrew.month.3.sense", "Movimiento" },
    { "hebrew.month.3.tribe", "Zabul\xc3\xb3n" },
    { "hebrew.month.4.brief", "Mes de las tablas rotas \xe2\x80\x94 ver m\xc3\xa1s all\xc3\xa1" },
    { "hebrew.month.4.letter", "Chet" },
    { "hebrew.month.4.name", "Tammuz" },
    { "hebrew.month.4.quality", "Visi\xc3\xb3n en la oscuridad" },
    { "hebrew.month.4.sense", "Vista" },
    { "hebrew.month.4.tribe", "Rub\xc3\xa9n" },
    { "hebrew.month.5.brief", "Mes de destrucci\xc3\xb3n y consolaci\xc3\xb3n" },
    { "hebrew.month.5.letter", "Tet" },
    { "hebrew.month.5.name", "Av" },
    { "hebrew.month.5.quality", "Transformaci\xc3\xb3n del dolor" },
    { "hebrew.month.5.sense", "O\xc3\xad" "do" },
    { "hebrew.month.5.tribe", "Sime\xc3\xb3n" },
    { "hebrew.month.6.brief", "Mes del retorno \xe2\x80\x94 preparaci\xc3\xb3n para el a\xc3\xb1o nuevo" },
    { "hebrew.month.6.letter", "Yod" },
    { "hebrew.month.6.name", "Elul" },
    { "hebrew.month.6.quality", "Arrepentimiento" },
    { "hebrew.month.6.sense", "Acci\xc3\xb3n" },
    { "hebrew.month.6.tribe", "Gad" },
    { "hebrew.month.7.brief", "Mes de las Altas Fiestas \xe2\x80\x94 Rosh Hashan\xc3\xa1, Yom Kipur, Sucot" },
    { "hebrew.month.7.letter", "Lamed" },
    { "hebrew.month.7.name", "Tishrei" },
    { "hebrew.month.7.quality", "Asombro y juicio" },
    { "hebrew.month.7.sense", "Tacto" },
    { "hebrew.month.7.tribe", "Efra\xc3\xadn" },
    { "hebrew.month.8.brief", "El mes amargo \xe2\x80\x94 sin festividades, solo plegarias por lluvia" },
    { "hebrew.month.8.letter", "Nun" },
    { "hebrew.month.8.name", "Cheshvan" },
    { "hebrew.month.8.quality", "Profundidad silenciosa" },
    { "hebrew.month.8.sense", "Olfato" },
    { "hebrew.month.8.tribe", "Manas\xc3\xa9s" },
    { "hebrew.month.9.brief", "Mes de sue\xc3\xb1os y luces \xe2\x80\x94 Januc\xc3\xa1" },
    { "hebrew.month.9.letter", "Samekh" },
    { "hebrew.month.9.name", "Kislev" },
    { "hebrew.month.9.quality", "Confianza y milagros" },
    { "hebrew.month.9.sense", "Sue\xc3\xb1o" },
    { "hebrew.month.9.tribe", "Benjam\xc3\xadn" },
    { "hebrew.tpl.detail", "%2$s es el mes de %1$s. Su letra es %3$s, su tribu es %4$s, su sentido es %5$s. %6$s." },
    { "hebrew.tpl.glance", "%1$d %2$s %3$d \xe2\x80\x94 %4$s" },
    { "hebrew.tpl.sabbatical", " A\xc3\xb1o de Shemit\xc3\xa1 %1$d de 7." },
    { "islamic.month.1.brief", "Mes sagrado de luto y remembranza" },
    { "islamic.month.1.event", "Ashura (10) -- Mois\xc3\xa9s liberado del Fara\xc3\xb3n" },
    { "islamic.month.1.name", "Muharram" },
    { "islamic.month.1.significance", "Primer mes, mes de Al\xc3\xa1" },
    { "islamic.month.10.brief", "Mes de celebraci\xc3\xb3n y ayuno voluntario" },
    { "islamic.month.10.event", "Eid al-Fitr (1) -- Festival de la Ruptura del Ayuno" },
    { "islamic.month.10.name", "Shawwal" },
    { "islamic.month.10.significance", "Mes de la elevaci\xc3\xb3n" },
    { "islamic.month.11.brief", "Mes sagrado de tregua y preparaci\xc3\xb3n para el Hajj" },
    { "islamic.month.11.event", "" },
    { "islamic.month.11.name", "Dhul Qa'dah" },
    { "islamic.month.11.significance", "Mes del descanso" },
    { "islamic.month.12.brief", "Mes sagrado de peregrinaci\xc3\xb3n y sacrificio" },
    { "islamic.month.12.event", "Hajj (8-12), Eid al-Adha (10) -- Festival del Sacrificio" },
    { "islamic.month.12.name", "Dhul Hijjah" },
    { "islamic.month.12.significance", "Mes de la peregrinaci\xc3\xb3n" },
    { "islamic.month.2.brief", "Mes de viajes -- tradicionalmente considerado dif\xc3\xad" "cil" },
    { "islamic.month.2.event", "" },
    { "islamic.month.2.name", "Safar" },
    { "islamic.month.2.significance", "Mes de los viajes" },
    { "islamic.month.3.brief", "Mes de alegr\xc3\xad" "a y celebraci\xc3\xb3n prof\xc3\xa9tica" },
    { "islamic.month.3.event", "Mawlid (12) -- nacimiento del Profeta Muhammad" },
    { "islamic.month.3.name", "Rabi al-Awwal" },
    { "islamic.month.3.significance", "Mes del nacimiento del Profeta" },
    { "islamic.month.4.brief", "Mes tranquilo de reflexi\xc3\xb3n y crecimiento" },
    { "islamic.month.4.event", "" },
    { "islamic.month.4.name", "Rabi al-Thani" },
    { "islamic.month.4.significance", "Mes de la continuaci\xc3\xb3n de la primavera" },
    { "islamic.month.5.brief", "Mes de resistencia ante la adversidad" },
    { "islamic.month.5.event", "" },
    { "islamic.month.5.name", "Jumada al-Ula" },
    { "islamic.month.5.significance", "Mes del agua helada" },
    { "islamic.month.6.brief", "Mes de preparaci\xc3\xb3n y anticipaci\xc3\xb3n" },
    { "islamic.month.6.event", "" },
    { "islamic.month.6.name", "Jumada al-Thani" },
    { "islamic.month.6.significance", "Mes de la llegada del verano" },
    { "islamic.month.7.brief", "Mes sagrado de ascenso espiritual" },
    { "islamic.month.7.event", "Isra y Mi'raj (27) -- el Viaje Nocturno" },
    { "islamic.month.7.name", "Rajab" },
    { "islamic.month.7.significance", "Mes del respeto" },
    { "islamic.month.8.brief", "Mes de preparaci\xc3\xb3n para el Ramad\xc3\xa1n" },
    { "islamic.month.8.event", "Laylat al-Bara'ah (15) -- Noche de la Fortuna" },
    { "islamic.month.8.name", "Sha'ban" },
    { "islamic.month.8.significance", "Mes de divisi\xc3\xb3n/separaci\xc3\xb3n" },
    { "islamic.month.9.brief", "Mes de ayuno, revelaci\xc3\xb3n y renovaci\xc3\xb3n espiritual" },
    { "islamic.month.9.event", "Todo el mes: Sawm (ayuno), Laylat al-Qadr (27)" },
    { "islamic.month.9.name", "Ramad\xc3\xa1n" },
    { "islamic.month.9.significance", "Mes del calor ardiente/ayuno" },
    { "islamic.prayer.0.arabic", "al-Fajr" },
    { "islamic.prayer.0.meaning", "Despertar -- comenzar antes de que el mundo se agite" },
    { "islamic.prayer.0.name", "Fajr" },
    { "islamic.prayer.0.time_desc", "Pre-amanecer, primera luz" },
    { "islamic.prayer.1.arabic", "al-Zuhr" },
    { "islamic.prayer.1.meaning", "Remembranza -- pausar en el apogeo del d\xc3\xad" "a" },
    { "islamic.prayer.1.name", "Dhuhr" },
    { "islamic.prayer.1.time_desc", "Mediod\xc3\xad" "a, despu\xc3\xa9s del cenit" },
    { "islamic.prayer.2.arabic", "al-'Asr" },
    { "islamic.prayer.2.meaning", "Reflexi\xc3\xb3n -- conciencia del paso del tiempo" },
    { "islamic.prayer.2.name", "Asr" },
    { "islamic.prayer.2.time_desc", "Tarde, sol declinante" },
    { "islamic.prayer.3.arabic", "al-Maghrib" },
    { "islamic.prayer.3.meaning", "Gratitud -- marcar la plenitud del d\xc3\xad" "a" },
    { "islamic.prayer.3.name", "Maghrib" },
    { "islamic.prayer.3.time_desc", "Justo despu\xc3\xa9s del ocaso" },
    { "islamic.prayer.4.arabic", "al-'Isha" },
    { "islamic.prayer.4.meaning", "Entrega -- confianza en la oscuridad" },
    { "islamic.prayer.4.name", "Isha" },
    { "islamic.prayer.4.time_desc", "Noche, cuando el crep\xc3\xbasculo se desvanece" },
    { "islamic.tpl.detail", "%1$s (%2$s)." },
    { "islamic.tpl.detail_event", " %1$s." },
    { "islamic.tpl.detail_sacred", " Este es uno de los cuatro meses sagrados." },
    { "islamic.tpl.glance", "%1$d %2$s %3$d -- %4$s" },
};

#define GEN_CONTENT_ES_COUNT \
    ((int)(sizeof(gen_content_es) / sizeof(gen_content_es[0])))

#endif /* TIME_CONTENT_GENERATED_H */
