/* content_generated.h — AUTO-GENERATED from data/content JSON files.
 * Do not edit manually. Run: python3 scripts/gen_content.py
 * Content translation arrays for content_i18n.c. */

#ifndef TIME_CONTENT_GENERATED_H
#define TIME_CONTENT_GENERATED_H

#include "i18n.h"

/* ---- EN (175 keys, canonical) ---- */

static const i18n_entry_t gen_content_en[] = {
    { "gregorian.day.0.brief", "The Moon's day \xe2\x80\x94 intuition, emotion, the tides within" },
    { "gregorian.day.0.name", "Monday" },
    { "gregorian.day.0.origin", "Old English Monandaeg (Moon's day)" },
    { "gregorian.day.0.planet", "Moon" },
    { "gregorian.day.1.brief", "Mars' day \xe2\x80\x94 courage, action, the warrior's resolve" },
    { "gregorian.day.1.name", "Tuesday" },
    { "gregorian.day.1.origin", "Old English Tiwesdaeg (Tyr's day, Norse Mars)" },
    { "gregorian.day.1.planet", "Mars" },
    { "gregorian.day.2.brief", "Mercury's day \xe2\x80\x94 communication, craft, the trickster's wit" },
    { "gregorian.day.2.name", "Wednesday" },
    { "gregorian.day.2.origin", "Old English Wodnesdaeg (Woden's day, Norse Mercury)" },
    { "gregorian.day.2.planet", "Mercury" },
    { "gregorian.day.3.brief", "Jupiter's day \xe2\x80\x94 expansion, abundance, the thunder god's generosity" },
    { "gregorian.day.3.name", "Thursday" },
    { "gregorian.day.3.origin", "Old English Thunresdaeg (Thor's day, Norse Jupiter)" },
    { "gregorian.day.3.planet", "Jupiter" },
    { "gregorian.day.4.brief", "Venus' day \xe2\x80\x94 love, beauty, the goddess of desire" },
    { "gregorian.day.4.name", "Friday" },
    { "gregorian.day.4.origin", "Old English Frigedaeg (Freya's day, Norse Venus)" },
    { "gregorian.day.4.planet", "Venus" },
    { "gregorian.day.5.brief", "Saturn's day \xe2\x80\x94 discipline, structure, the taskmaster's lesson" },
    { "gregorian.day.5.name", "Saturday" },
    { "gregorian.day.5.origin", "Latin Saturni dies (Saturn's day)" },
    { "gregorian.day.5.planet", "Saturn" },
    { "gregorian.day.6.brief", "The Sun's day \xe2\x80\x94 vitality, sovereignty, the center of all orbits" },
    { "gregorian.day.6.name", "Sunday" },
    { "gregorian.day.6.origin", "Old English Sunnandaeg (Sun's day)" },
    { "gregorian.day.6.planet", "Sun" },
    { "gregorian.month.1.brief", "The month of doorways \xe2\x80\x94 one face looks back, one looks forward" },
    { "gregorian.month.1.name", "January" },
    { "gregorian.month.1.origin", "Janus \xe2\x80\x94 two-faced god of beginnings, gates, and transitions" },
    { "gregorian.month.1.quality", "Deep winter, reflection, fresh starts" },
    { "gregorian.month.10.brief", "The eighth month \xe2\x80\x94 the world turns inward as the light contracts" },
    { "gregorian.month.10.name", "October" },
    { "gregorian.month.10.origin", "Octo (eight) \xe2\x80\x94 the eighth month of the old Roman calendar" },
    { "gregorian.month.10.quality", "Mid-autumn, deepening, transformation" },
    { "gregorian.month.11.brief", "The ninth month \xe2\x80\x94 the dead are honored as the year grows old" },
    { "gregorian.month.11.name", "November" },
    { "gregorian.month.11.origin", "Novem (nine) \xe2\x80\x94 the ninth month of the old Roman calendar" },
    { "gregorian.month.11.quality", "Late autumn, remembrance, preparation for dark" },
    { "gregorian.month.12.brief", "The tenth month \xe2\x80\x94 in the deepest dark, the ancient Romans feasted and the sun was reborn" },
    { "gregorian.month.12.name", "December" },
    { "gregorian.month.12.origin", "Decem (ten) \xe2\x80\x94 the tenth month of the old Roman calendar" },
    { "gregorian.month.12.quality", "Winter solstice, Saturnalia, the return of light" },
    { "gregorian.month.2.brief", "The month of cleansing \xe2\x80\x94 the last fires of purification before new growth" },
    { "gregorian.month.2.name", "February" },
    { "gregorian.month.2.origin", "Februa \xe2\x80\x94 Roman purification festival (Lupercalia)" },
    { "gregorian.month.2.quality", "Late winter, purification, preparation for spring" },
    { "gregorian.month.3.brief", "The month of Mars \xe2\x80\x94 the old Roman year began here, with war and planting alike" },
    { "gregorian.month.3.name", "March" },
    { "gregorian.month.3.origin", "Mars \xe2\x80\x94 god of war and agriculture, the Roman new year" },
    { "gregorian.month.3.quality", "Spring equinox, awakening, aggressive new growth" },
    { "gregorian.month.4.brief", "The month of opening \xe2\x80\x94 everything that was closed begins to unfold" },
    { "gregorian.month.4.name", "April" },
    { "gregorian.month.4.origin", "Aperire (to open) \xe2\x80\x94 the earth opens, buds unfold" },
    { "gregorian.month.4.quality", "Full spring, opening, blossoming" },
    { "gregorian.month.5.brief", "The month of growth \xe2\x80\x94 the earth goddess whose name means 'she who is great'" },
    { "gregorian.month.5.name", "May" },
    { "gregorian.month.5.origin", "Maia \xe2\x80\x94 goddess of growth, mother of Mercury" },
    { "gregorian.month.5.quality", "Late spring, fertility, abundance beginning" },
    { "gregorian.month.6.brief", "The month of marriage \xe2\x80\x94 the queen of heaven blesses the longest days" },
    { "gregorian.month.6.name", "June" },
    { "gregorian.month.6.origin", "Juno \xe2\x80\x94 queen of the gods, patron of marriage" },
    { "gregorian.month.6.quality", "Summer solstice, union, peak daylight" },
    { "gregorian.month.7.brief", "The month of Caesar \xe2\x80\x94 named for the man who remade time itself" },
    { "gregorian.month.7.name", "July" },
    { "gregorian.month.7.origin", "Julius Caesar \xe2\x80\x94 reformed the calendar, deified after death" },
    { "gregorian.month.7.quality", "High summer, power, radiance" },
    { "gregorian.month.8.brief", "The month of Augustus \xe2\x80\x94 the emperor who demanded a month as grand as July" },
    { "gregorian.month.8.name", "August" },
    { "gregorian.month.8.origin", "Augustus Caesar \xe2\x80\x94 first Roman emperor, 'the revered one'" },
    { "gregorian.month.8.quality", "Late summer, harvest begins, empire at zenith" },
    { "gregorian.month.9.brief", "The seventh month \xe2\x80\x94 still carrying its old number though it is now the ninth" },
    { "gregorian.month.9.name", "September" },
    { "gregorian.month.9.origin", "Septem (seven) \xe2\x80\x94 the seventh month of the old Roman calendar" },
    { "gregorian.month.9.quality", "Autumn equinox, balance, gathering in" },
    { "gregorian.season.0.brief", "The season of becoming \xe2\x80\x94 everything that slept now wakes" },
    { "gregorian.season.0.name", "Spring" },
    { "gregorian.season.0.quality", "Expansive \xe2\x80\x94 energy rises, seeds germinate, days lengthen" },
    { "gregorian.season.0.theme", "Rebirth, growth, potential becoming actual" },
    { "gregorian.season.1.brief", "The season of being \xe2\x80\x94 the world at maximum brilliance" },
    { "gregorian.season.1.name", "Summer" },
    { "gregorian.season.1.quality", "Radiant \xe2\x80\x94 energy at peak, light dominates, life in full bloom" },
    { "gregorian.season.1.theme", "Fullness, radiance, maximum expression" },
    { "gregorian.season.2.brief", "The season of letting go \xe2\x80\x94 beauty in decay, richness in release" },
    { "gregorian.season.2.name", "Autumn" },
    { "gregorian.season.2.quality", "Contracting \xe2\x80\x94 energy turns inward, fruit ripens, leaves fall" },
    { "gregorian.season.2.theme", "Harvest, release, gratitude for what grew" },
    { "gregorian.season.3.brief", "The season of rest \xe2\x80\x94 what appears dead is dreaming" },
    { "gregorian.season.3.name", "Winter" },
    { "gregorian.season.3.quality", "Still \xe2\x80\x94 energy withdrawn to roots, silence, gestation in darkness" },
    { "gregorian.season.3.theme", "Rest, depth, the hidden seed, essential stillness" },
    { "gregorian.tpl.detail", "%1$s: %2$s. %3$s. Season: %4$s \xe2\x80\x94 %5$s. %6$s (%7$s): %8$s." },
    { "gregorian.tpl.glance", "%1$s %2$d (%3$s) \xe2\x80\x94 %4$s" },
    { "hebrew.month.1.brief", "Month of miracles and liberation \xe2\x80\x94 Passover" },
    { "hebrew.month.1.letter", "Hei" },
    { "hebrew.month.1.name", "Nisan" },
    { "hebrew.month.1.quality", "Redemption" },
    { "hebrew.month.1.sense", "Speech" },
    { "hebrew.month.1.tribe", "Judah" },
    { "hebrew.month.10.brief", "The darkest month \xe2\x80\x94 righteous indignation" },
    { "hebrew.month.10.letter", "Ayin" },
    { "hebrew.month.10.name", "Tevet" },
    { "hebrew.month.10.quality", "Transformation" },
    { "hebrew.month.10.sense", "Anger (righteous)" },
    { "hebrew.month.10.tribe", "Dan" },
    { "hebrew.month.11.brief", "New Year of Trees \xe2\x80\x94 Tu B'Shevat" },
    { "hebrew.month.11.letter", "Tzadi" },
    { "hebrew.month.11.name", "Shevat" },
    { "hebrew.month.11.quality", "Renewal" },
    { "hebrew.month.11.sense", "Taste" },
    { "hebrew.month.11.tribe", "Asher" },
    { "hebrew.month.12.brief", "Month of Purim \xe2\x80\x94 hidden miracles revealed" },
    { "hebrew.month.12.letter", "Qof" },
    { "hebrew.month.12.name", "Adar" },
    { "hebrew.month.12.quality", "Joy and reversal" },
    { "hebrew.month.12.sense", "Laughter" },
    { "hebrew.month.12.tribe", "Naphtali" },
    { "hebrew.month.13.brief", "Leap month \xe2\x80\x94 Purim celebrated here in leap years" },
    { "hebrew.month.13.letter", "Qof" },
    { "hebrew.month.13.name", "Adar II" },
    { "hebrew.month.13.quality", "Joy doubled" },
    { "hebrew.month.13.sense", "Laughter" },
    { "hebrew.month.13.tribe", "Naphtali" },
    { "hebrew.month.2.brief", "Month of natural healing \xe2\x80\x94 counting the Omer" },
    { "hebrew.month.2.letter", "Vav" },
    { "hebrew.month.2.name", "Iyar" },
    { "hebrew.month.2.quality", "Healing" },
    { "hebrew.month.2.sense", "Thought" },
    { "hebrew.month.2.tribe", "Issachar" },
    { "hebrew.month.3.brief", "Month of Torah giving \xe2\x80\x94 Shavuot" },
    { "hebrew.month.3.letter", "Zayin" },
    { "hebrew.month.3.name", "Sivan" },
    { "hebrew.month.3.quality", "Revelation" },
    { "hebrew.month.3.sense", "Motion" },
    { "hebrew.month.3.tribe", "Zebulun" },
    { "hebrew.month.4.brief", "Month of the broken tablets \xe2\x80\x94 seeing beyond" },
    { "hebrew.month.4.letter", "Chet" },
    { "hebrew.month.4.name", "Tammuz" },
    { "hebrew.month.4.quality", "Vision through darkness" },
    { "hebrew.month.4.sense", "Sight" },
    { "hebrew.month.4.tribe", "Reuben" },
    { "hebrew.month.5.brief", "Month of destruction and consolation" },
    { "hebrew.month.5.letter", "Tet" },
    { "hebrew.month.5.name", "Av" },
    { "hebrew.month.5.quality", "Transformation of sorrow" },
    { "hebrew.month.5.sense", "Hearing" },
    { "hebrew.month.5.tribe", "Simeon" },
    { "hebrew.month.6.brief", "Month of returning \xe2\x80\x94 preparation for the new year" },
    { "hebrew.month.6.letter", "Yod" },
    { "hebrew.month.6.name", "Elul" },
    { "hebrew.month.6.quality", "Repentance" },
    { "hebrew.month.6.sense", "Action" },
    { "hebrew.month.6.tribe", "Gad" },
    { "hebrew.month.7.brief", "Month of the High Holidays \xe2\x80\x94 Rosh Hashanah, Yom Kippur, Sukkot" },
    { "hebrew.month.7.letter", "Lamed" },
    { "hebrew.month.7.name", "Tishrei" },
    { "hebrew.month.7.quality", "Awe and judgment" },
    { "hebrew.month.7.sense", "Touch" },
    { "hebrew.month.7.tribe", "Ephraim" },
    { "hebrew.month.8.brief", "The bitter month \xe2\x80\x94 no holidays, only rain prayers" },
    { "hebrew.month.8.letter", "Nun" },
    { "hebrew.month.8.name", "Cheshvan" },
    { "hebrew.month.8.quality", "Quiet depth" },
    { "hebrew.month.8.sense", "Smell" },
    { "hebrew.month.8.tribe", "Manasseh" },
    { "hebrew.month.9.brief", "Month of dreams and lights \xe2\x80\x94 Hanukkah" },
    { "hebrew.month.9.letter", "Samekh" },
    { "hebrew.month.9.name", "Kislev" },
    { "hebrew.month.9.quality", "Trust and miracles" },
    { "hebrew.month.9.sense", "Sleep" },
    { "hebrew.month.9.tribe", "Benjamin" },
    { "hebrew.tpl.detail", "%1$s is the month of %2$s. Its letter is %3$s, its tribe is %4$s, its sense is %5$s. %6$s." },
    { "hebrew.tpl.glance", "%1$d %2$s %3$d \xe2\x80\x94 %4$s" },
    { "hebrew.tpl.sabbatical", " Shemitah year %1$d of 7." },
};

#define GEN_CONTENT_EN_COUNT \
    ((int)(sizeof(gen_content_en) / sizeof(gen_content_en[0])))

/* ---- ES (175 keys) ---- */

static const i18n_entry_t gen_content_es[] = {
    { "gregorian.day.0.brief", "El d\xc3\xad" "a de la Luna \xe2\x80\x94 intuici\xc3\xb3n, emoci\xc3\xb3n, las mareas interiores" },
    { "gregorian.day.0.name", "Lunes" },
    { "gregorian.day.0.origin", "Del lat\xc3\xadn Lunae dies (d\xc3\xad" "a de la Luna)" },
    { "gregorian.day.0.planet", "Luna" },
    { "gregorian.day.1.brief", "El d\xc3\xad" "a de Marte \xe2\x80\x94 coraje, acci\xc3\xb3n, la determinaci\xc3\xb3n del guerrero" },
    { "gregorian.day.1.name", "Martes" },
    { "gregorian.day.1.origin", "Del lat\xc3\xadn Martis dies (d\xc3\xad" "a de Marte)" },
    { "gregorian.day.1.planet", "Marte" },
    { "gregorian.day.2.brief", "El d\xc3\xad" "a de Mercurio \xe2\x80\x94 comunicaci\xc3\xb3n, ingenio, la astucia del mensajero" },
    { "gregorian.day.2.name", "Mi\xc3\xa9rcoles" },
    { "gregorian.day.2.origin", "Del lat\xc3\xadn Mercurii dies (d\xc3\xad" "a de Mercurio)" },
    { "gregorian.day.2.planet", "Mercurio" },
    { "gregorian.day.3.brief", "El d\xc3\xad" "a de J\xc3\xbapiter \xe2\x80\x94 expansi\xc3\xb3n, abundancia, la generosidad del trueno" },
    { "gregorian.day.3.name", "Jueves" },
    { "gregorian.day.3.origin", "Del lat\xc3\xadn Iovis dies (d\xc3\xad" "a de J\xc3\xbapiter)" },
    { "gregorian.day.3.planet", "J\xc3\xbapiter" },
    { "gregorian.day.4.brief", "El d\xc3\xad" "a de Venus \xe2\x80\x94 amor, belleza, la diosa del deseo" },
    { "gregorian.day.4.name", "Viernes" },
    { "gregorian.day.4.origin", "Del lat\xc3\xadn Veneris dies (d\xc3\xad" "a de Venus)" },
    { "gregorian.day.4.planet", "Venus" },
    { "gregorian.day.5.brief", "El d\xc3\xad" "a de Saturno \xe2\x80\x94 disciplina, estructura, la lecci\xc3\xb3n del maestro" },
    { "gregorian.day.5.name", "S\xc3\xa1" "bado" },
    { "gregorian.day.5.origin", "Del lat\xc3\xadn Sabbatum (d\xc3\xad" "a de descanso)" },
    { "gregorian.day.5.planet", "Saturno" },
    { "gregorian.day.6.brief", "El d\xc3\xad" "a del Sol \xe2\x80\x94 vitalidad, soberan\xc3\xad" "a, el centro de todas las \xc3\xb3rbitas" },
    { "gregorian.day.6.name", "Domingo" },
    { "gregorian.day.6.origin", "Del lat\xc3\xadn Dominicus dies (d\xc3\xad" "a del Se\xc3\xb1or)" },
    { "gregorian.day.6.planet", "Sol" },
    { "gregorian.month.1.brief", "El mes de las puertas \xe2\x80\x94 un rostro mira hacia atr\xc3\xa1s, otro hacia adelante" },
    { "gregorian.month.1.name", "Enero" },
    { "gregorian.month.1.origin", "Janus \xe2\x80\x94 dios bifronte de los comienzos, los umbrales y las transiciones" },
    { "gregorian.month.1.quality", "Pleno invierno, reflexi\xc3\xb3n, nuevos comienzos" },
    { "gregorian.month.10.brief", "El octavo mes \xe2\x80\x94 el mundo se recoge mientras la luz se contrae" },
    { "gregorian.month.10.name", "Octubre" },
    { "gregorian.month.10.origin", "Octo (ocho) \xe2\x80\x94 el octavo mes del antiguo calendario romano" },
    { "gregorian.month.10.quality", "Mediados de oto\xc3\xb1o, profundizaci\xc3\xb3n, transformaci\xc3\xb3n" },
    { "gregorian.month.11.brief", "El noveno mes \xe2\x80\x94 se honra a los muertos mientras el a\xc3\xb1o envejece" },
    { "gregorian.month.11.name", "Noviembre" },
    { "gregorian.month.11.origin", "Novem (nueve) \xe2\x80\x94 el noveno mes del antiguo calendario romano" },
    { "gregorian.month.11.quality", "Fin de oto\xc3\xb1o, memoria, preparaci\xc3\xb3n para la oscuridad" },
    { "gregorian.month.12.brief", "El d\xc3\xa9" "cimo mes \xe2\x80\x94 en la oscuridad m\xc3\xa1s profunda, los romanos festejaban y el sol renac\xc3\xad" "a" },
    { "gregorian.month.12.name", "Diciembre" },
    { "gregorian.month.12.origin", "Decem (diez) \xe2\x80\x94 el d\xc3\xa9" "cimo mes del antiguo calendario romano" },
    { "gregorian.month.12.quality", "Solsticio de invierno, Saturnalia, el retorno de la luz" },
    { "gregorian.month.2.brief", "El mes de la purificaci\xc3\xb3n \xe2\x80\x94 los \xc3\xbaltimos fuegos antes del nuevo crecimiento" },
    { "gregorian.month.2.name", "Febrero" },
    { "gregorian.month.2.origin", "Februa \xe2\x80\x94 festival romano de purificaci\xc3\xb3n (Lupercalia)" },
    { "gregorian.month.2.quality", "Fin de invierno, purificaci\xc3\xb3n, preparaci\xc3\xb3n para la primavera" },
    { "gregorian.month.3.brief", "El mes de Marte \xe2\x80\x94 aqu\xc3\xad comenzaba el a\xc3\xb1o romano, con guerra y siembra por igual" },
    { "gregorian.month.3.name", "Marzo" },
    { "gregorian.month.3.origin", "Mars \xe2\x80\x94 dios de la guerra y la agricultura, el a\xc3\xb1o nuevo romano" },
    { "gregorian.month.3.quality", "Equinoccio de primavera, despertar, crecimiento vigoroso" },
    { "gregorian.month.4.brief", "El mes de la apertura \xe2\x80\x94 todo lo que estaba cerrado comienza a desplegarse" },
    { "gregorian.month.4.name", "Abril" },
    { "gregorian.month.4.origin", "Aperire (abrir) \xe2\x80\x94 la tierra se abre, los brotes se despliegan" },
    { "gregorian.month.4.quality", "Plena primavera, apertura, floraci\xc3\xb3n" },
    { "gregorian.month.5.brief", "El mes del crecimiento \xe2\x80\x94 la diosa de la tierra cuyo nombre significa 'la que es grande'" },
    { "gregorian.month.5.name", "Mayo" },
    { "gregorian.month.5.origin", "Maia \xe2\x80\x94 diosa del crecimiento, madre de Mercurio" },
    { "gregorian.month.5.quality", "Fin de primavera, fertilidad, abundancia naciente" },
    { "gregorian.month.6.brief", "El mes del matrimonio \xe2\x80\x94 la reina del cielo bendice los d\xc3\xad" "as m\xc3\xa1s largos" },
    { "gregorian.month.6.name", "Junio" },
    { "gregorian.month.6.origin", "Juno \xe2\x80\x94 reina de los dioses, patrona del matrimonio" },
    { "gregorian.month.6.quality", "Solsticio de verano, uni\xc3\xb3n, m\xc3\xa1xima luz diurna" },
    { "gregorian.month.7.brief", "El mes de C\xc3\xa9sar \xe2\x80\x94 nombrado por el hombre que rehizo el tiempo mismo" },
    { "gregorian.month.7.name", "Julio" },
    { "gregorian.month.7.origin", "Julius Caesar \xe2\x80\x94 reform\xc3\xb3 el calendario, deificado tras su muerte" },
    { "gregorian.month.7.quality", "Pleno verano, poder, resplandor" },
    { "gregorian.month.8.brief", "El mes de Augusto \xe2\x80\x94 el emperador que exigi\xc3\xb3 un mes tan grandioso como julio" },
    { "gregorian.month.8.name", "Agosto" },
    { "gregorian.month.8.origin", "Augustus Caesar \xe2\x80\x94 primer emperador romano, 'el venerado'" },
    { "gregorian.month.8.quality", "Fin de verano, comienza la cosecha, el imperio en su cenit" },
    { "gregorian.month.9.brief", "El s\xc3\xa9ptimo mes \xe2\x80\x94 a\xc3\xban porta su viejo n\xc3\xbamero aunque ahora es el noveno" },
    { "gregorian.month.9.name", "Septiembre" },
    { "gregorian.month.9.origin", "Septem (siete) \xe2\x80\x94 el s\xc3\xa9ptimo mes del antiguo calendario romano" },
    { "gregorian.month.9.quality", "Equinoccio de oto\xc3\xb1o, equilibrio, recogimiento" },
    { "gregorian.season.0.brief", "La estaci\xc3\xb3n del devenir \xe2\x80\x94 todo lo que dorm\xc3\xad" "a ahora despierta" },
    { "gregorian.season.0.name", "Primavera" },
    { "gregorian.season.0.quality", "Expansiva \xe2\x80\x94 la energ\xc3\xad" "a asciende, las semillas germinan, los d\xc3\xad" "as se alargan" },
    { "gregorian.season.0.theme", "Renacimiento, crecimiento, lo potencial se hace real" },
    { "gregorian.season.1.brief", "La estaci\xc3\xb3n del ser \xe2\x80\x94 el mundo en su m\xc3\xa1ximo esplendor" },
    { "gregorian.season.1.name", "Verano" },
    { "gregorian.season.1.quality", "Radiante \xe2\x80\x94 energ\xc3\xad" "a en su apogeo, la luz domina, la vida en plena floraci\xc3\xb3n" },
    { "gregorian.season.1.theme", "Plenitud, resplandor, m\xc3\xa1xima expresi\xc3\xb3n" },
    { "gregorian.season.2.brief", "La estaci\xc3\xb3n del soltar \xe2\x80\x94 belleza en la ca\xc3\xad" "da, riqueza en la entrega" },
    { "gregorian.season.2.name", "Oto\xc3\xb1o" },
    { "gregorian.season.2.quality", "Contractiva \xe2\x80\x94 la energ\xc3\xad" "a se recoge, el fruto madura, las hojas caen" },
    { "gregorian.season.2.theme", "Cosecha, liberaci\xc3\xb3n, gratitud por lo que creci\xc3\xb3" },
    { "gregorian.season.3.brief", "La estaci\xc3\xb3n del reposo \xe2\x80\x94 lo que parece muerto est\xc3\xa1 so\xc3\xb1" "ando" },
    { "gregorian.season.3.name", "Invierno" },
    { "gregorian.season.3.quality", "Quieta \xe2\x80\x94 energ\xc3\xad" "a recogida en las ra\xc3\xad" "ces, silencio, gestaci\xc3\xb3n en la oscuridad" },
    { "gregorian.season.3.theme", "Descanso, profundidad, la semilla oculta, quietud esencial" },
    { "gregorian.tpl.detail", "%1$s: %2$s. %3$s. Estaci\xc3\xb3n: %4$s \xe2\x80\x94 %5$s. %6$s (%7$s): %8$s." },
    { "gregorian.tpl.glance", "%1$s %2$d (%3$s) \xe2\x80\x94 %4$s" },
    { "hebrew.month.1.brief", "Mes de milagros y liberaci\xc3\xb3n \xe2\x80\x94 Pesaj" },
    { "hebrew.month.1.letter", "Hei" },
    { "hebrew.month.1.name", "Nisan" },
    { "hebrew.month.1.quality", "Redenci\xc3\xb3n" },
    { "hebrew.month.1.sense", "Habla" },
    { "hebrew.month.1.tribe", "Jud\xc3\xa1" },
    { "hebrew.month.10.brief", "El mes m\xc3\xa1s oscuro \xe2\x80\x94 indignaci\xc3\xb3n justa" },
    { "hebrew.month.10.letter", "Ayin" },
    { "hebrew.month.10.name", "Tevet" },
    { "hebrew.month.10.quality", "Transformaci\xc3\xb3n" },
    { "hebrew.month.10.sense", "Ira (justa)" },
    { "hebrew.month.10.tribe", "Dan" },
    { "hebrew.month.11.brief", "A\xc3\xb1o Nuevo de los \xc3\x81rboles \xe2\x80\x94 Tu BiShvat" },
    { "hebrew.month.11.letter", "Tzadi" },
    { "hebrew.month.11.name", "Shevat" },
    { "hebrew.month.11.quality", "Renovaci\xc3\xb3n" },
    { "hebrew.month.11.sense", "Gusto" },
    { "hebrew.month.11.tribe", "Aser" },
    { "hebrew.month.12.brief", "Mes de Purim \xe2\x80\x94 milagros ocultos revelados" },
    { "hebrew.month.12.letter", "Qof" },
    { "hebrew.month.12.name", "Adar" },
    { "hebrew.month.12.quality", "Alegr\xc3\xad" "a y transformaci\xc3\xb3n" },
    { "hebrew.month.12.sense", "Risa" },
    { "hebrew.month.12.tribe", "Neftal\xc3\xad" },
    { "hebrew.month.13.brief", "Mes bisiesto \xe2\x80\x94 Purim se celebra aqu\xc3\xad en a\xc3\xb1os bisiestos" },
    { "hebrew.month.13.letter", "Qof" },
    { "hebrew.month.13.name", "Adar II" },
    { "hebrew.month.13.quality", "Alegr\xc3\xad" "a duplicada" },
    { "hebrew.month.13.sense", "Risa" },
    { "hebrew.month.13.tribe", "Neftal\xc3\xad" },
    { "hebrew.month.2.brief", "Mes de sanaci\xc3\xb3n natural \xe2\x80\x94 la cuenta del \xc3\x93mer" },
    { "hebrew.month.2.letter", "Vav" },
    { "hebrew.month.2.name", "Iyar" },
    { "hebrew.month.2.quality", "Sanaci\xc3\xb3n" },
    { "hebrew.month.2.sense", "Pensamiento" },
    { "hebrew.month.2.tribe", "Isacar" },
    { "hebrew.month.3.brief", "Mes de la entrega de la Tor\xc3\xa1 \xe2\x80\x94 Shavuot" },
    { "hebrew.month.3.letter", "Zayin" },
    { "hebrew.month.3.name", "Sivan" },
    { "hebrew.month.3.quality", "Revelaci\xc3\xb3n" },
    { "hebrew.month.3.sense", "Movimiento" },
    { "hebrew.month.3.tribe", "Zabul\xc3\xb3n" },
    { "hebrew.month.4.brief", "Mes de las tablas rotas \xe2\x80\x94 ver m\xc3\xa1s all\xc3\xa1" },
    { "hebrew.month.4.letter", "Chet" },
    { "hebrew.month.4.name", "Tammuz" },
    { "hebrew.month.4.quality", "Visi\xc3\xb3n en la oscuridad" },
    { "hebrew.month.4.sense", "Vista" },
    { "hebrew.month.4.tribe", "Rub\xc3\xa9n" },
    { "hebrew.month.5.brief", "Mes de destrucci\xc3\xb3n y consolaci\xc3\xb3n" },
    { "hebrew.month.5.letter", "Tet" },
    { "hebrew.month.5.name", "Av" },
    { "hebrew.month.5.quality", "Transformaci\xc3\xb3n del dolor" },
    { "hebrew.month.5.sense", "O\xc3\xad" "do" },
    { "hebrew.month.5.tribe", "Sime\xc3\xb3n" },
    { "hebrew.month.6.brief", "Mes del retorno \xe2\x80\x94 preparaci\xc3\xb3n para el a\xc3\xb1o nuevo" },
    { "hebrew.month.6.letter", "Yod" },
    { "hebrew.month.6.name", "Elul" },
    { "hebrew.month.6.quality", "Arrepentimiento" },
    { "hebrew.month.6.sense", "Acci\xc3\xb3n" },
    { "hebrew.month.6.tribe", "Gad" },
    { "hebrew.month.7.brief", "Mes de las Altas Fiestas \xe2\x80\x94 Rosh Hashan\xc3\xa1, Yom Kipur, Sucot" },
    { "hebrew.month.7.letter", "Lamed" },
    { "hebrew.month.7.name", "Tishrei" },
    { "hebrew.month.7.quality", "Asombro y juicio" },
    { "hebrew.month.7.sense", "Tacto" },
    { "hebrew.month.7.tribe", "Efra\xc3\xadn" },
    { "hebrew.month.8.brief", "El mes amargo \xe2\x80\x94 sin festividades, solo plegarias por lluvia" },
    { "hebrew.month.8.letter", "Nun" },
    { "hebrew.month.8.name", "Cheshvan" },
    { "hebrew.month.8.quality", "Profundidad silenciosa" },
    { "hebrew.month.8.sense", "Olfato" },
    { "hebrew.month.8.tribe", "Manas\xc3\xa9s" },
    { "hebrew.month.9.brief", "Mes de sue\xc3\xb1os y luces \xe2\x80\x94 Januc\xc3\xa1" },
    { "hebrew.month.9.letter", "Samekh" },
    { "hebrew.month.9.name", "Kislev" },
    { "hebrew.month.9.quality", "Confianza y milagros" },
    { "hebrew.month.9.sense", "Sue\xc3\xb1o" },
    { "hebrew.month.9.tribe", "Benjam\xc3\xadn" },
    { "hebrew.tpl.detail", "%2$s es el mes de %1$s. Su letra es %3$s, su tribu es %4$s, su sentido es %5$s. %6$s." },
    { "hebrew.tpl.glance", "%1$d %2$s %3$d \xe2\x80\x94 %4$s" },
    { "hebrew.tpl.sabbatical", " A\xc3\xb1o de Shemit\xc3\xa1 %1$d de 7." },
};

#define GEN_CONTENT_ES_COUNT \
    ((int)(sizeof(gen_content_es) / sizeof(gen_content_es[0])))

#endif /* TIME_CONTENT_GENERATED_H */
