/* ui_bridge.c -- C-to-DOM bridge for UI panels.
 *
 * STATEFUL module (S1): uses EM_ASM, static state, Emscripten APIs.
 * Wires pure UI data modules into the browser DOM.
 *
 * All panel content is generated by pure modules (ui_html, help_overlay,
 * command_palette, layer_panel) and injected into DOM elements whose IDs
 * match the structure in web/index.html. */

#ifdef __EMSCRIPTEN__

#include <emscripten.h>
#include <stdio.h>
#include <string.h>

#include "ui_bridge.h"
#include "ui_html.h"
#include "ui_state.h"
#include "command_palette.h"
#include "time_control.h"
#include "theme.h"
#include "theme_css.h"
#include "../systems/gregorian/gregorian.h"

/* ------------------------------------------------------------------ */
/* Module-static state (S1)                                            */
/* ------------------------------------------------------------------ */

static ui_state_t s_ui_state;
static char s_search_buf[256];
static int s_current_theme; /* 0 = Cosmos (dark), 1 = Dawn (light) */

/* ------------------------------------------------------------------ */
/* ui_bridge_init                                                      */
/* ------------------------------------------------------------------ */

/* Inject theme CSS custom properties into :root */
static void inject_theme_css(void) {
    theme_t theme = theme_get((s_current_theme == 0) ? THEME_COSMOS : THEME_DAWN);
    char css_buf[2048];
    theme_css_vars(&theme, css_buf, (int)sizeof(css_buf));
    EM_ASM({
        var id = 'time-theme-vars';
        var el = document.getElementById(id);
        if (!el) {
            el = document.createElement('style');
            el.id = id;
            document.head.appendChild(el);
        }
        el.textContent = ':root {\n' + UTF8ToString($0) + '}';
    }, css_buf);
}

void ui_bridge_init(void) {
    s_ui_state = ui_state_init();
    s_search_buf[0] = '\0';
    /* Read saved theme preference from localStorage (default: Cosmos) */
    s_current_theme = EM_ASM_INT({
        var saved = localStorage.getItem("time_theme");
        return (saved !== null) ? parseInt(saved, 10) : 0;
    });
    if (s_current_theme < 0 || s_current_theme > 1) s_current_theme = 0;

    /* --- Theme CSS: inject custom properties from C theme system --- */
    inject_theme_css();

    /* --- Help panel: generate HTML from help_overlay data --- */
    char help_buf[UI_HTML_BUF_SIZE];
    ui_html_help(help_buf, UI_HTML_BUF_SIZE);
    EM_ASM({
        var el = document.getElementById('help-content');
        if (el) el.innerHTML = UTF8ToString($0);
    }, help_buf);

    /* --- Layer panel: generate HTML from layer_panel data --- */
    char layer_buf[UI_HTML_BUF_SIZE];
    unsigned int default_mask = 0xFFFFFFFFu; /* all layers on initially */
    ui_html_layers(default_mask, layer_buf, UI_HTML_BUF_SIZE);
    EM_ASM({
        var el = document.getElementById('layer-content');
        if (el) el.innerHTML = UTF8ToString($0);
    }, layer_buf);

    /* --- Command palette: generate initial results (all commands) --- */
    char cmd_buf[UI_HTML_BUF_SIZE];
    cmd_result_t all_cmds = cmd_palette_search("");
    ui_html_cmd_results(&all_cmds, cmd_buf, UI_HTML_BUF_SIZE);
    EM_ASM({
        var el = document.getElementById('cmd-results');
        if (el) el.innerHTML = UTF8ToString($0);
    }, cmd_buf);

    /* --- Register command search input handler --- */
    EM_ASM({
        var input = document.getElementById('cmd-search');
        if (input) {
            input.addEventListener('input', function() {
                var str = this.value;
                var buf = Module._ui_get_search_buf();
                Module.stringToUTF8(str, buf, 256);
                Module._ui_do_command_search();
            });
        }
    });
}

/* ------------------------------------------------------------------ */
/* ui_bridge_update_time                                               */
/* ------------------------------------------------------------------ */

void ui_bridge_update_time(double jd, double speed) {
    /* Format date via gregorian pure module */
    char date_buf[64];
    gregorian_format_full(jd, date_buf, sizeof(date_buf));

    /* Format speed display */
    char speed_buf[32];
    double display_speed = speed * 86400.0;

    if (speed == 0.0) {
        snprintf(speed_buf, sizeof(speed_buf), "PAUSED");
    } else if (display_speed == 1.0) {
        snprintf(speed_buf, sizeof(speed_buf), "Real-time");
    } else if (display_speed >= 1.0) {
        snprintf(speed_buf, sizeof(speed_buf), "%.0fx", display_speed);
    } else {
        snprintf(speed_buf, sizeof(speed_buf), "%.2fx", display_speed);
    }

    int is_paused = (speed == 0.0) ? 1 : 0;

    EM_ASM({
        var el;
        el = document.getElementById('tb-date');
        if (el) el.textContent = UTF8ToString($0);
        el = document.getElementById('tb-speed');
        if (el) el.textContent = UTF8ToString($1);
        el = document.getElementById('tb-pause');
        if (el) el.innerHTML = $2 ? '\u25B6' : '\u23F8';
    }, date_buf, speed_buf, is_paused);
}

/* ------------------------------------------------------------------ */
/* KEEPALIVE: Panel toggle functions (called from JS)                   */
/* ------------------------------------------------------------------ */

EMSCRIPTEN_KEEPALIVE void ui_toggle_help(void) {
    s_ui_state = ui_state_toggle_mode(s_ui_state, UI_MODE_HELP);
    int show = ui_state_is_mode(s_ui_state, UI_MODE_HELP);
    EM_ASM({
        var panel = document.getElementById('help-panel');
        var cmd   = document.getElementById('cmd-palette');
        var layer = document.getElementById('layer-panel');
        if (panel) {
            if ($0) panel.classList.remove('hidden');
            else    panel.classList.add('hidden');
        }
        if (cmd)   cmd.classList.add('hidden');
        if (layer) layer.classList.remove('mode-open');
    }, show);
}

EMSCRIPTEN_KEEPALIVE void ui_toggle_command_palette(void) {
    s_ui_state = ui_state_toggle_mode(s_ui_state, UI_MODE_PALETTE);
    int show = ui_state_is_mode(s_ui_state, UI_MODE_PALETTE);
    EM_ASM({
        var panel = document.getElementById('cmd-palette');
        var help  = document.getElementById('help-panel');
        var layer = document.getElementById('layer-panel');
        if (panel) {
            if ($0) panel.classList.remove('hidden');
            else    panel.classList.add('hidden');
        }
        if (help)  help.classList.add('hidden');
        if (layer) layer.classList.remove('mode-open');
    }, show);
}

EMSCRIPTEN_KEEPALIVE void ui_toggle_layer_panel(void) {
    s_ui_state = ui_state_toggle_mode(s_ui_state, UI_MODE_LAYER_PANEL);
    int show = ui_state_is_mode(s_ui_state, UI_MODE_LAYER_PANEL);
    EM_ASM({
        var panel = document.getElementById('layer-panel');
        var help  = document.getElementById('help-panel');
        var cmd   = document.getElementById('cmd-palette');
        if (panel) {
            if ($0) panel.classList.add('mode-open');
            else    panel.classList.remove('mode-open');
        }
        if (help) help.classList.add('hidden');
        if (cmd)  cmd.classList.add('hidden');
    }, show);
}

EMSCRIPTEN_KEEPALIVE void ui_toggle_theme(void) {
    s_current_theme = (s_current_theme == 0) ? 1 : 0;
    inject_theme_css();
    EM_ASM({
        localStorage.setItem("time_theme", $0.toString());
    }, s_current_theme);
}

EMSCRIPTEN_KEEPALIVE void ui_close_panels(void) {
    s_ui_state = ui_state_close(s_ui_state);
    EM_ASM({
        var help  = document.getElementById('help-panel');
        var cmd   = document.getElementById('cmd-palette');
        var layer = document.getElementById('layer-panel');
        if (help)  help.classList.add('hidden');
        if (cmd)   cmd.classList.add('hidden');
        if (layer) layer.classList.remove('mode-open');
    });
}

/* ------------------------------------------------------------------ */
/* KEEPALIVE: Command search (shared buffer approach)                   */
/* ------------------------------------------------------------------ */

EMSCRIPTEN_KEEPALIVE char *ui_get_search_buf(void) {
    return s_search_buf;
}

EMSCRIPTEN_KEEPALIVE void ui_do_command_search(void) {
    cmd_result_t results = cmd_palette_search(s_search_buf);
    char buf[UI_HTML_BUF_SIZE];
    ui_html_cmd_results(&results, buf, UI_HTML_BUF_SIZE);
    EM_ASM({
        var el = document.getElementById('cmd-results');
        if (el) el.innerHTML = UTF8ToString($0);
    }, buf);
}

#else
/* ------------------------------------------------------------------ */
/* Native stubs — no-op when not targeting Emscripten                  */
/* ------------------------------------------------------------------ */

void ui_bridge_init(void) { }
void ui_bridge_update_time(double jd, double speed) {
    (void)jd;
    (void)speed;
}

#endif /* __EMSCRIPTEN__ */
