#!/usr/bin/env python3
"""Add I Ching, Human Design, Kabbalah, Hindu content to en.json and es.json.

Run: python3 scripts/add_system_content.py
"""

import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EN_PATH = os.path.join(BASE, "data", "content", "en.json")
ES_PATH = os.path.join(BASE, "data", "content", "es.json")

# ============================================================
# I CHING — 64 hexagrams × 5 fields + 2 templates = 322 keys
# ============================================================

ICHING_EN = {
    # Templates
    "iching.tpl.glance": "Hexagram %1$d %2$s \xe2\x80\x94 %3$s over %4$s",
    "iching.tpl.detail": "%1$s: %2$s. The Image: %3$s. Keywords: %4$s. Upper trigram: %5$s, Lower: %6$s.",
}

ICHING_ES = {
    "iching.tpl.glance": "Hexagrama %1$d %2$s \xe2\x80\x94 %3$s sobre %4$s",
    "iching.tpl.detail": "%1$s: %2$s. La Imagen: %3$s. Palabras clave: %4$s. Trigrama superior: %5$s, Inferior: %6$s.",
}

# Hexagram data: (name_en, judgment_en, image_en, keywords_en, element_en,
#                  name_es, judgment_es, image_es, keywords_es, element_es)
HEXAGRAMS = [
    # 1
    ("The Creative",
     "Pure creative force initiates all things",
     "Heaven upon heaven \xe2\x80\x94 the sage strengthens himself ceaselessly",
     "Creation, strength, initiative", "Heaven",
     "Lo Creativo",
     "La fuerza creativa pura inicia todas las cosas",
     "Cielo sobre cielo \xe2\x80\x94 el sabio se fortalece sin cesar",
     "Creaci\u00f3n, fuerza, iniciativa", "Cielo"),
    # 2
    ("The Receptive",
     "Pure receptive force nourishes all things",
     "Earth upon earth \xe2\x80\x94 the sage supports all beings with broad virtue",
     "Receptivity, devotion, nurture", "Earth",
     "Lo Receptivo",
     "La fuerza receptiva pura nutre todas las cosas",
     "Tierra sobre tierra \xe2\x80\x94 el sabio sostiene a todos los seres con amplia virtud",
     "Receptividad, devoci\u00f3n, nutrici\u00f3n", "Tierra"),
    # 3
    ("Difficulty at the Beginning",
     "Birth pangs of new endeavors require perseverance",
     "Thunder and rain \xe2\x80\x94 the sage brings order from chaos",
     "Beginning, struggle, growth", "Water/Thunder",
     "La Dificultad Inicial",
     "Los dolores de parto de nuevos emprendimientos requieren perseverancia",
     "Trueno y lluvia \xe2\x80\x94 el sabio trae orden del caos",
     "Comienzo, lucha, crecimiento", "Agua/Trueno"),
    # 4
    ("Youthful Folly",
     "The young fool seeks the teacher, not the teacher the fool",
     "Spring at the foot of the mountain \xe2\x80\x94 the sage cultivates character",
     "Learning, innocence, guidance", "Mountain/Water",
     "La Necedad Juvenil",
     "El joven necio busca al maestro, no el maestro al necio",
     "Manantial al pie de la monta\u00f1a \xe2\x80\x94 el sabio cultiva el car\u00e1cter",
     "Aprendizaje, inocencia, gu\u00eda", "Monta\u00f1a/Agua"),
    # 5
    ("Waiting",
     "Sincerity and patience lead to crossing the great water",
     "Clouds rise to heaven \xe2\x80\x94 the sage eats, drinks, and is joyful",
     "Patience, nourishment, trust", "Water/Heaven",
     "La Espera",
     "La sinceridad y la paciencia conducen a cruzar las grandes aguas",
     "Las nubes ascienden al cielo \xe2\x80\x94 el sabio come, bebe y se alegra",
     "Paciencia, nutrici\u00f3n, confianza", "Agua/Cielo"),
    # 6
    ("Conflict",
     "Inner truth and caution resolve disagreement",
     "Heaven and water move apart \xe2\x80\x94 the sage plans before acting",
     "Conflict, caution, mediation", "Heaven/Water",
     "El Conflicto",
     "La verdad interior y la cautela resuelven el desacuerdo",
     "Cielo y agua se separan \xe2\x80\x94 el sabio planifica antes de actuar",
     "Conflicto, cautela, mediaci\u00f3n", "Cielo/Agua"),
    # 7
    ("The Army",
     "Discipline and just leadership organize the people",
     "Water within the earth \xe2\x80\x94 the sage nurtures the people and gathers strength",
     "Leadership, discipline, strategy", "Earth/Water",
     "El Ej\u00e9rcito",
     "La disciplina y el liderazgo justo organizan al pueblo",
     "Agua dentro de la tierra \xe2\x80\x94 el sabio nutre al pueblo y re\u00fane fuerzas",
     "Liderazgo, disciplina, estrategia", "Tierra/Agua"),
    # 8
    ("Holding Together",
     "Union requires a central figure of sincerity",
     "Water upon the earth \xe2\x80\x94 the ancient kings established their states",
     "Unity, alliance, cooperation", "Water/Earth",
     "La Solidaridad",
     "La uni\u00f3n requiere una figura central de sinceridad",
     "Agua sobre la tierra \xe2\x80\x94 los antiguos reyes establecieron sus estados",
     "Unidad, alianza, cooperaci\u00f3n", "Agua/Tierra"),
    # 9
    ("Small Taming",
     "Gentle restraint achieves what force cannot",
     "Wind over heaven \xe2\x80\x94 the sage refines outward form and virtue",
     "Restraint, refinement, patience", "Wind/Heaven",
     "La Fuerza Domesticadora de lo Peque\u00f1o",
     "La sutil restricci\u00f3n logra lo que la fuerza no puede",
     "Viento sobre cielo \xe2\x80\x94 el sabio refina la forma exterior y la virtud",
     "Restricci\u00f3n, refinamiento, paciencia", "Viento/Cielo"),
    # 10
    ("Treading",
     "Treading upon the tiger's tail with care and propriety brings success",
     "Heaven above the lake \xe2\x80\x94 the sage distinguishes high and low",
     "Conduct, propriety, courage", "Heaven/Lake",
     "El Porte",
     "Pisar la cola del tigre con cuidado y propiedad trae \u00e9xito",
     "Cielo sobre el lago \xe2\x80\x94 el sabio distingue lo alto y lo bajo",
     "Conducta, propiedad, coraje", "Cielo/Lago"),
    # 11
    ("Peace",
     "Heaven and earth unite \xe2\x80\x94 the small departs, the great approaches",
     "Earth above heaven \xe2\x80\x94 the ruler channels the way of heaven for the people",
     "Peace, harmony, prosperity", "Earth/Heaven",
     "La Paz",
     "Cielo y tierra se unen \xe2\x80\x94 lo peque\u00f1o parte, lo grande se acerca",
     "Tierra sobre cielo \xe2\x80\x94 el gobernante canaliza el camino del cielo para el pueblo",
     "Paz, armon\u00eda, prosperidad", "Tierra/Cielo"),
    # 12
    ("Standstill",
     "Heaven and earth do not communicate \xe2\x80\x94 decline and obstruction",
     "Heaven above earth \xe2\x80\x94 the sage withdraws into inner worth",
     "Stagnation, withdrawal, patience", "Heaven/Earth",
     "El Estancamiento",
     "Cielo y tierra no se comunican \xe2\x80\x94 declive y obstrucci\u00f3n",
     "Cielo sobre tierra \xe2\x80\x94 el sabio se retira hacia el valor interior",
     "Estancamiento, retirada, paciencia", "Cielo/Tierra"),
    # 13
    ("Fellowship",
     "True fellowship among people through shared principles",
     "Heaven with fire \xe2\x80\x94 the sage organizes clans and distinguishes things",
     "Community, fellowship, openness", "Heaven/Fire",
     "La Comunidad",
     "La verdadera comunidad entre personas mediante principios compartidos",
     "Cielo con fuego \xe2\x80\x94 el sabio organiza los clanes y distingue las cosas",
     "Comunidad, hermandad, apertura", "Cielo/Fuego"),
    # 14
    ("Great Possession",
     "Fire in heaven \xe2\x80\x94 supreme success through understanding what is great",
     "Fire above heaven \xe2\x80\x94 the sage curbs evil and promotes good",
     "Abundance, responsibility, generosity", "Fire/Heaven",
     "La Gran Posesi\u00f3n",
     "Fuego en el cielo \xe2\x80\x94 supremo \u00e9xito mediante la comprensi\u00f3n de lo grande",
     "Fuego sobre cielo \xe2\x80\x94 el sabio frena el mal y promueve el bien",
     "Abundancia, responsabilidad, generosidad", "Fuego/Cielo"),
    # 15
    ("Modesty",
     "Modesty creates success \xe2\x80\x94 the mountain within the earth",
     "Mountain within earth \xe2\x80\x94 the sage reduces what is too much and increases what is too little",
     "Humility, balance, modesty", "Earth/Mountain",
     "La Modestia",
     "La modestia crea \u00e9xito \xe2\x80\x94 la monta\u00f1a dentro de la tierra",
     "Monta\u00f1a dentro de la tierra \xe2\x80\x94 el sabio reduce lo excesivo y aumenta lo insuficiente",
     "Humildad, equilibrio, modestia", "Tierra/Monta\u00f1a"),
    # 16
    ("Enthusiasm",
     "Thunder over earth \xe2\x80\x94 enthusiasm moves all things",
     "Thunder over earth \xe2\x80\x94 the ancient kings made music to honor merit",
     "Enthusiasm, momentum, inspiration", "Thunder/Earth",
     "El Entusiasmo",
     "Trueno sobre la tierra \xe2\x80\x94 el entusiasmo mueve todas las cosas",
     "Trueno sobre la tierra \xe2\x80\x94 los antiguos reyes hac\u00edan m\u00fasica para honrar el m\u00e9rito",
     "Entusiasmo, impulso, inspiraci\u00f3n", "Trueno/Tierra"),
    # 17
    ("Following",
     "Adapting to the time and following with sincerity brings success",
     "Thunder within the lake \xe2\x80\x94 the sage rests at nightfall",
     "Adaptability, following, service", "Lake/Thunder",
     "El Seguimiento",
     "Adaptarse al tiempo y seguir con sinceridad trae \u00e9xito",
     "Trueno dentro del lago \xe2\x80\x94 el sabio descansa al anochecer",
     "Adaptabilidad, seguimiento, servicio", "Lago/Trueno"),
    # 18
    ("Work on the Decayed",
     "What has been corrupted through neglect can be restored through effort",
     "Wind at the foot of the mountain \xe2\x80\x94 the sage stirs up the people and nourishes virtue",
     "Repair, renewal, responsibility", "Mountain/Wind",
     "El Trabajo sobre lo Corrompido",
     "Lo corrompido por la negligencia puede restaurarse con esfuerzo",
     "Viento al pie de la monta\u00f1a \xe2\x80\x94 el sabio conmueve al pueblo y nutre la virtud",
     "Reparaci\u00f3n, renovaci\u00f3n, responsabilidad", "Monta\u00f1a/Viento"),
    # 19
    ("Approach",
     "The great approaches with willing condescension toward the small",
     "Earth above the lake \xe2\x80\x94 the sage teaches and shelters without limit",
     "Advance, influence, generosity", "Earth/Lake",
     "El Acercamiento",
     "Lo grande se acerca con voluntaria condescendencia hacia lo peque\u00f1o",
     "Tierra sobre el lago \xe2\x80\x94 el sabio ense\u00f1a y protege sin l\u00edmite",
     "Avance, influencia, generosidad", "Tierra/Lago"),
    # 20
    ("Contemplation",
     "The sage gazes upon the divine meaning beneath appearances",
     "Wind over earth \xe2\x80\x94 the ancient kings visited the regions to teach the people",
     "Observation, insight, perspective", "Wind/Earth",
     "La Contemplaci\u00f3n",
     "El sabio contempla el significado divino bajo las apariencias",
     "Viento sobre la tierra \xe2\x80\x94 los antiguos reyes visitaban las regiones para ense\u00f1ar al pueblo",
     "Observaci\u00f3n, visi\u00f3n, perspectiva", "Viento/Tierra"),
    # 21
    ("Biting Through",
     "Energetic biting through obstacles restores unity",
     "Thunder and lightning \xe2\x80\x94 the ancient kings enforced the laws with clarity",
     "Decisiveness, justice, breakthrough", "Fire/Thunder",
     "La Mordedura Tajante",
     "Morder en\u00e9rgicamente a trav\u00e9s de los obst\u00e1culos restaura la unidad",
     "Trueno y rel\u00e1mpago \xe2\x80\x94 los antiguos reyes aplicaban las leyes con claridad",
     "Decisi\u00f3n, justicia, avance", "Fuego/Trueno"),
    # 22
    ("Grace",
     "Beauty adorns form but substance must remain within",
     "Fire at the foot of the mountain \xe2\x80\x94 the sage brightens governance without daring to judge",
     "Beauty, form, adornment", "Mountain/Fire",
     "La Gracia",
     "La belleza adorna la forma pero la sustancia debe permanecer dentro",
     "Fuego al pie de la monta\u00f1a \xe2\x80\x94 el sabio ilumina la gobernanza sin atreverse a juzgar",
     "Belleza, forma, ornamento", "Monta\u00f1a/Fuego"),
    # 23
    ("Splitting Apart",
     "The dark forces peel away what has been built \xe2\x80\x94 accept and wait",
     "Mountain resting on the earth \xe2\x80\x94 the ruler strengthens the foundation of the people",
     "Decay, erosion, acceptance", "Mountain/Earth",
     "La Desintegraci\u00f3n",
     "Las fuerzas oscuras despojan lo construido \xe2\x80\x94 acepta y espera",
     "Monta\u00f1a reposando sobre la tierra \xe2\x80\x94 el gobernante fortalece los cimientos del pueblo",
     "Decadencia, erosi\u00f3n, aceptaci\u00f3n", "Monta\u00f1a/Tierra"),
    # 24
    ("Return",
     "After decay, the turning point \xe2\x80\x94 the one light returns below",
     "Thunder within the earth \xe2\x80\x94 the ancient kings closed the passes at solstice",
     "Renewal, turning point, return", "Earth/Thunder",
     "El Retorno",
     "Tras la decadencia, el punto de retorno \xe2\x80\x94 la \u00fanica luz regresa desde abajo",
     "Trueno dentro de la tierra \xe2\x80\x94 los antiguos reyes cerraban los pasos en el solsticio",
     "Renovaci\u00f3n, punto de retorno, regreso", "Tierra/Trueno"),
    # 25
    ("Innocence",
     "Acting from genuine nature without ulterior motive brings success",
     "Thunder under heaven \xe2\x80\x94 the ancient kings nourished all beings in accord with the season",
     "Innocence, sincerity, spontaneity", "Heaven/Thunder",
     "La Inocencia",
     "Actuar desde la naturaleza genuina sin motivos ocultos trae \u00e9xito",
     "Trueno bajo el cielo \xe2\x80\x94 los antiguos reyes nutr\u00edan a todos los seres de acuerdo con la estaci\u00f3n",
     "Inocencia, sinceridad, espontaneidad", "Cielo/Trueno"),
    # 26
    ("Great Taming",
     "Firm restraint of great creative power builds reserves of strength",
     "Heaven within the mountain \xe2\x80\x94 the sage studies the ancients to cultivate character",
     "Restraint, accumulation, cultivation", "Mountain/Heaven",
     "La Gran Domesticaci\u00f3n",
     "La firme restricci\u00f3n del gran poder creativo construye reservas de fuerza",
     "Cielo dentro de la monta\u00f1a \xe2\x80\x94 el sabio estudia a los antiguos para cultivar el car\u00e1cter",
     "Restricci\u00f3n, acumulaci\u00f3n, cultivo", "Monta\u00f1a/Cielo"),
    # 27
    ("Nourishment",
     "Attending to what nourishes body and mind brings good fortune",
     "Thunder at the foot of the mountain \xe2\x80\x94 the sage is careful with words and temperate in eating",
     "Nourishment, sustenance, care", "Mountain/Thunder",
     "La Nutrici\u00f3n",
     "Atender lo que nutre cuerpo y mente trae buena fortuna",
     "Trueno al pie de la monta\u00f1a \xe2\x80\x94 el sabio es cuidadoso con las palabras y moderado al comer",
     "Nutrici\u00f3n, sustento, cuidado", "Monta\u00f1a/Trueno"),
    # 28
    ("Great Excess",
     "The ridgepole bends \xe2\x80\x94 extraordinary measures are needed in extraordinary times",
     "The lake rises above the trees \xe2\x80\x94 the sage stands alone without fear",
     "Excess, crisis, courage", "Lake/Wind",
     "El Gran Exceso",
     "La viga maestra se dobla \xe2\x80\x94 medidas extraordinarias se necesitan en tiempos extraordinarios",
     "El lago se eleva sobre los \u00e1rboles \xe2\x80\x94 el sabio permanece solo sin temor",
     "Exceso, crisis, coraje", "Lago/Viento"),
    # 29
    ("The Abysmal",
     "Repeated danger teaches sincerity of heart \xe2\x80\x94 flow like water",
     "Water flows on and reaches the goal \xe2\x80\x94 the sage teaches through repeated practice",
     "Danger, depth, perseverance", "Water/Water",
     "Lo Abismal",
     "El peligro repetido ense\u00f1a la sinceridad del coraz\u00f3n \xe2\x80\x94 fluye como el agua",
     "El agua fluye y alcanza la meta \xe2\x80\x94 el sabio ense\u00f1a mediante la pr\u00e1ctica repetida",
     "Peligro, profundidad, perseverancia", "Agua/Agua"),
    # 30
    ("The Clinging",
     "Luminous clarity depends on something to cling to \xe2\x80\x94 accept dependence",
     "Fire doubled produces great brightness \xe2\x80\x94 the sage illuminates all regions",
     "Clarity, dependence, brightness", "Fire/Fire",
     "Lo Adherente",
     "La luminosa claridad depende de algo a qu\u00e9 adherirse \xe2\x80\x94 acepta la dependencia",
     "Fuego duplicado produce gran resplandor \xe2\x80\x94 el sabio ilumina todas las regiones",
     "Claridad, dependencia, resplandor", "Fuego/Fuego"),
    # 31
    ("Influence",
     "Mutual attraction between the yielding and the firm brings union",
     "The lake upon the mountain \xe2\x80\x94 the sage receives others with openness",
     "Attraction, sensitivity, courtship", "Lake/Mountain",
     "La Influencia",
     "La atracci\u00f3n mutua entre lo flexible y lo firme trae uni\u00f3n",
     "El lago sobre la monta\u00f1a \xe2\x80\x94 el sabio recibe a otros con apertura",
     "Atracci\u00f3n, sensibilidad, cortejo", "Lago/Monta\u00f1a"),
    # 32
    ("Duration",
     "Enduring consistency in one's way of life brings success",
     "Thunder and wind reinforce each other \xe2\x80\x94 the sage stands firm in his direction",
     "Endurance, consistency, marriage", "Thunder/Wind",
     "La Duraci\u00f3n",
     "La consistencia perdurable en el modo de vida trae \u00e9xito",
     "Trueno y viento se refuerzan mutuamente \xe2\x80\x94 el sabio se mantiene firme en su direcci\u00f3n",
     "Resistencia, consistencia, matrimonio", "Trueno/Viento"),
    # 33
    ("Retreat",
     "Strategic withdrawal before the advancing dark preserves strength",
     "Mountain under heaven \xe2\x80\x94 the sage keeps the inferior at a distance with dignity",
     "Retreat, strategy, dignity", "Heaven/Mountain",
     "La Retirada",
     "La retirada estrat\u00e9gica ante la oscuridad que avanza preserva la fuerza",
     "Monta\u00f1a bajo el cielo \xe2\x80\x94 el sabio mantiene lo inferior a distancia con dignidad",
     "Retirada, estrategia, dignidad", "Cielo/Monta\u00f1a"),
    # 34
    ("Great Power",
     "Great power combined with righteousness moves heaven and earth",
     "Thunder above heaven \xe2\x80\x94 the sage treads no path contrary to propriety",
     "Power, strength, righteousness", "Thunder/Heaven",
     "El Gran Poder",
     "El gran poder combinado con la rectitud mueve cielo y tierra",
     "Trueno sobre el cielo \xe2\x80\x94 el sabio no recorre ning\u00fan camino contrario a la propiedad",
     "Poder, fuerza, rectitud", "Trueno/Cielo"),
    # 35
    ("Progress",
     "The bright sun rises over the earth \xe2\x80\x94 willing service brings rapid advance",
     "The sun rises over the earth \xe2\x80\x94 the sage brightens his bright virtue",
     "Advancement, recognition, daylight", "Fire/Earth",
     "El Progreso",
     "El brillante sol se eleva sobre la tierra \xe2\x80\x94 el servicio voluntario trae r\u00e1pido avance",
     "El sol se eleva sobre la tierra \xe2\x80\x94 el sabio ilumina su brillante virtud",
     "Avance, reconocimiento, luz del d\u00eda", "Fuego/Tierra"),
    # 36
    ("Darkening of the Light",
     "In times of darkness the sage conceals his light to endure adversity",
     "The sun sinks into the earth \xe2\x80\x94 the sage veils his brightness in dealings with the multitude",
     "Concealment, endurance, prudence", "Earth/Fire",
     "El Oscurecimiento de la Luz",
     "En tiempos de oscuridad el sabio oculta su luz para soportar la adversidad",
     "El sol se hunde en la tierra \xe2\x80\x94 el sabio vela su brillo en el trato con la multitud",
     "Ocultamiento, resistencia, prudencia", "Tierra/Fuego"),
    # 37
    ("The Family",
     "The well-ordered family is the foundation of all social order",
     "Wind comes from fire \xe2\x80\x94 the sage speaks with substance and acts with consistency",
     "Family, order, domestic harmony", "Wind/Fire",
     "La Familia",
     "La familia bien ordenada es el fundamento de todo orden social",
     "El viento proviene del fuego \xe2\x80\x94 el sabio habla con sustancia y act\u00faa con consistencia",
     "Familia, orden, armon\u00eda dom\u00e9stica", "Viento/Fuego"),
    # 38
    ("Opposition",
     "Despite outward opposition, underlying affinity makes small things possible",
     "Fire above the lake \xe2\x80\x94 the sage remains individual within community",
     "Polarity, tension, independence", "Fire/Lake",
     "La Oposici\u00f3n",
     "A pesar de la oposici\u00f3n externa, la afinidad subyacente hace posibles las cosas peque\u00f1as",
     "Fuego sobre el lago \xe2\x80\x94 el sabio permanece individual dentro de la comunidad",
     "Polaridad, tensi\u00f3n, independencia", "Fuego/Lago"),
    # 39
    ("Obstruction",
     "Facing an abyss before and a mountain behind \xe2\x80\x94 turn inward and gather allies",
     "Water on the mountain \xe2\x80\x94 the sage turns attention to self-improvement",
     "Obstacle, introspection, perseverance", "Water/Mountain",
     "La Obstrucci\u00f3n",
     "Frente a un abismo delante y una monta\u00f1a detr\u00e1s \xe2\x80\x94 vu\u00e9lvete hacia adentro y re\u00fane aliados",
     "Agua sobre la monta\u00f1a \xe2\x80\x94 el sabio dirige su atenci\u00f3n a la mejora personal",
     "Obst\u00e1culo, introspecci\u00f3n, perseverancia", "Agua/Monta\u00f1a"),
    # 40
    ("Deliverance",
     "When release from tension comes, return to normalcy swiftly",
     "Thunder and rain arise \xe2\x80\x94 the sage pardons errors and forgives transgressions",
     "Liberation, forgiveness, relief", "Thunder/Water",
     "La Liberaci\u00f3n",
     "Cuando llega la liberaci\u00f3n de la tensi\u00f3n, regresa r\u00e1pidamente a la normalidad",
     "Trueno y lluvia surgen \xe2\x80\x94 el sabio perdona errores y absuelve transgresiones",
     "Liberaci\u00f3n, perd\u00f3n, alivio", "Trueno/Agua"),
    # 41
    ("Decrease",
     "Decrease of the lower enriches the higher \xe2\x80\x94 sincerity in simplicity brings blessings",
     "The lake at the foot of the mountain \xe2\x80\x94 the sage controls anger and restrains instincts",
     "Sacrifice, simplicity, sincerity", "Mountain/Lake",
     "La Merma",
     "La merma de lo inferior enriquece lo superior \xe2\x80\x94 la sinceridad en la sencillez trae bendiciones",
     "El lago al pie de la monta\u00f1a \xe2\x80\x94 el sabio controla la ira y refrena los instintos",
     "Sacrificio, sencillez, sinceridad", "Monta\u00f1a/Lago"),
    # 42
    ("Increase",
     "The ruler decreases self to increase the people \xe2\x80\x94 generous sacrifice brings benefit",
     "Wind and thunder strengthen each other \xe2\x80\x94 the sage moves toward good and corrects faults",
     "Growth, benefit, generosity", "Wind/Thunder",
     "El Aumento",
     "El gobernante se disminuye para aumentar al pueblo \xe2\x80\x94 el sacrificio generoso trae beneficio",
     "Viento y trueno se fortalecen mutuamente \xe2\x80\x94 el sabio avanza hacia el bien y corrige defectos",
     "Crecimiento, beneficio, generosidad", "Viento/Trueno"),
    # 43
    ("Breakthrough",
     "Resolute action brings dark matters to light \xe2\x80\x94 proclaim the danger openly",
     "The lake rises to heaven \xe2\x80\x94 the sage distributes blessings to those below",
     "Resolution, determination, openness", "Lake/Heaven",
     "La Irrupci\u00f3n",
     "La acci\u00f3n resuelta trae los asuntos oscuros a la luz \xe2\x80\x94 proclama el peligro abiertamente",
     "El lago se eleva al cielo \xe2\x80\x94 el sabio distribuye bendiciones a los de abajo",
     "Resoluci\u00f3n, determinaci\u00f3n, apertura", "Lago/Cielo"),
    # 44
    ("Coming to Meet",
     "The dark principle advances from below \xe2\x80\x94 recognize and contain it early",
     "Wind under heaven \xe2\x80\x94 the ruler proclaims his commands to the four quarters",
     "Encounter, temptation, vigilance", "Heaven/Wind",
     "Ir al Encuentro",
     "El principio oscuro avanza desde abajo \xe2\x80\x94 reconoce y cont\u00e9nlo temprano",
     "Viento bajo el cielo \xe2\x80\x94 el gobernante proclama sus mandatos a los cuatro rumbos",
     "Encuentro, tentaci\u00f3n, vigilancia", "Cielo/Viento"),
    # 45
    ("Gathering Together",
     "People gather around a strong leader \xe2\x80\x94 prepare for the unexpected",
     "The lake over the earth \xe2\x80\x94 the sage renews his weapons to meet the unforeseen",
     "Assembly, gathering, preparedness", "Lake/Earth",
     "La Reuni\u00f3n",
     "La gente se re\u00fane alrededor de un l\u00edder fuerte \xe2\x80\x94 prep\u00e1rate para lo inesperado",
     "El lago sobre la tierra \xe2\x80\x94 el sabio renueva sus armas para enfrentar lo imprevisto",
     "Asamblea, reuni\u00f3n, preparaci\u00f3n", "Lago/Tierra"),
    # 46
    ("Pushing Upward",
     "Gentle effort directed steadily upward meets with supreme success",
     "Within the earth wood grows \xe2\x80\x94 the sage builds great things from small beginnings",
     "Ascent, effort, growth", "Earth/Wind",
     "El Empuje hacia Arriba",
     "El esfuerzo suave dirigido constantemente hacia arriba encuentra supremo \u00e9xito",
     "Dentro de la tierra crece la madera \xe2\x80\x94 el sabio construye grandes cosas de peque\u00f1os comienzos",
     "Ascenso, esfuerzo, crecimiento", "Tierra/Viento"),
    # 47
    ("Oppression",
     "Exhaustion of resources tests character \xe2\x80\x94 the sage stakes his life on following his will",
     "The lake has no water \xe2\x80\x94 the sage risks his life to fulfill his purpose",
     "Adversity, exhaustion, resolve", "Lake/Water",
     "La Opresi\u00f3n",
     "El agotamiento de recursos pone a prueba el car\u00e1cter \xe2\x80\x94 el sabio apuesta su vida en seguir su voluntad",
     "El lago no tiene agua \xe2\x80\x94 el sabio arriesga su vida para cumplir su prop\u00f3sito",
     "Adversidad, agotamiento, resoluci\u00f3n", "Lago/Agua"),
    # 48
    ("The Well",
     "The well nourishes all without being exhausted \xe2\x80\x94 seek the unchanging source",
     "Water over wood \xe2\x80\x94 the sage encourages the people and counsels mutual aid",
     "Source, constancy, community", "Water/Wind",
     "El Pozo",
     "El pozo nutre a todos sin agotarse \xe2\x80\x94 busca la fuente inmutable",
     "Agua sobre madera \xe2\x80\x94 el sabio alienta al pueblo y aconseja la ayuda mutua",
     "Fuente, constancia, comunidad", "Agua/Viento"),
    # 49
    ("Revolution",
     "When the time is ripe, revolutionary change commands belief",
     "Fire in the lake \xe2\x80\x94 the sage orders the calendar and clarifies the seasons",
     "Transformation, timing, renewal", "Lake/Fire",
     "La Revoluci\u00f3n",
     "Cuando el tiempo est\u00e1 maduro, el cambio revolucionario impone creencia",
     "Fuego en el lago \xe2\x80\x94 el sabio ordena el calendario y clarifica las estaciones",
     "Transformaci\u00f3n, sincronizaci\u00f3n, renovaci\u00f3n", "Lago/Fuego"),
    # 50
    ("The Cauldron",
     "The sacred vessel transforms raw material into nourishment for the wise",
     "Fire over wood \xe2\x80\x94 the sage consolidates destiny by making his position correct",
     "Transformation, nourishment, culture", "Fire/Wind",
     "El Caldero",
     "El vaso sagrado transforma la materia prima en alimento para el sabio",
     "Fuego sobre madera \xe2\x80\x94 el sabio consolida el destino haciendo correcta su posici\u00f3n",
     "Transformaci\u00f3n, nutrici\u00f3n, cultura", "Fuego/Viento"),
    # 51
    ("The Arousing",
     "Shock and thunder bring fear, then laughter \xe2\x80\x94 the sage examines himself through awe",
     "Repeated thunder \xe2\x80\x94 the sage sets things in order through fearful reflection",
     "Shock, awakening, initiative", "Thunder/Thunder",
     "Lo Suscitativo",
     "El choque y el trueno traen temor, luego risa \xe2\x80\x94 el sabio se examina a trav\u00e9s del asombro",
     "Trueno repetido \xe2\x80\x94 el sabio pone las cosas en orden mediante reflexi\u00f3n temerosa",
     "Choque, despertar, iniciativa", "Trueno/Trueno"),
    # 52
    ("Keeping Still",
     "Stillness of the mountain \xe2\x80\x94 the sage quiets the mind and does not go beyond his position",
     "Mountains joined together \xe2\x80\x94 the sage does not permit thoughts to go beyond the situation",
     "Stillness, meditation, composure", "Mountain/Mountain",
     "El Aquietamiento",
     "La quietud de la monta\u00f1a \xe2\x80\x94 el sabio aquieta la mente y no va m\u00e1s all\u00e1 de su posici\u00f3n",
     "Monta\u00f1as unidas \xe2\x80\x94 el sabio no permite que los pensamientos vayan m\u00e1s all\u00e1 de la situaci\u00f3n",
     "Quietud, meditaci\u00f3n, compostura", "Monta\u00f1a/Monta\u00f1a"),
    # 53
    ("Gradual Progress",
     "Gradual development like a tree on the mountain brings lasting results",
     "A tree on the mountain grows slowly \xe2\x80\x94 the sage abides in dignity and virtue",
     "Patience, development, steady growth", "Wind/Mountain",
     "El Progreso Gradual",
     "El desarrollo gradual como un \u00e1rbol en la monta\u00f1a trae resultados duraderos",
     "Un \u00e1rbol en la monta\u00f1a crece lentamente \xe2\x80\x94 el sabio permanece en dignidad y virtud",
     "Paciencia, desarrollo, crecimiento constante", "Viento/Monta\u00f1a"),
    # 54
    ("The Marrying Maiden",
     "The younger sister follows the elder \xe2\x80\x94 knowing one's place brings eventual good",
     "Thunder over the lake \xe2\x80\x94 the sage understands the transitory in light of eternity",
     "Subordination, propriety, transitions", "Thunder/Lake",
     "La Desposada",
     "La hermana menor sigue a la mayor \xe2\x80\x94 conocer el lugar propio trae el bien eventual",
     "Trueno sobre el lago \xe2\x80\x94 el sabio comprende lo transitorio a la luz de la eternidad",
     "Subordinaci\u00f3n, propiedad, transiciones", "Trueno/Lago"),
    # 55
    ("Abundance",
     "Fullness and abundance at the zenith \xe2\x80\x94 act now for the sun must set",
     "Thunder and lightning together \xe2\x80\x94 the sage decides lawsuits and carries out punishments",
     "Fullness, zenith, decisiveness", "Thunder/Fire",
     "La Abundancia",
     "Plenitud y abundancia en el cenit \xe2\x80\x94 act\u00faa ahora pues el sol debe ponerse",
     "Trueno y rel\u00e1mpago juntos \xe2\x80\x94 el sabio decide pleitos y ejecuta castigos",
     "Plenitud, cenit, decisi\u00f3n", "Trueno/Fuego"),
    # 56
    ("The Wanderer",
     "The traveler succeeds through smallness and adaptability, not grandeur",
     "Fire on the mountain \xe2\x80\x94 the sage is clear and cautious in applying penalties",
     "Travel, impermanence, adaptability", "Fire/Mountain",
     "El Viajero",
     "El viajero triunfa mediante la sencillez y la adaptabilidad, no la grandeza",
     "Fuego sobre la monta\u00f1a \xe2\x80\x94 el sabio es claro y cauteloso al aplicar sanciones",
     "Viaje, impermanencia, adaptabilidad", "Fuego/Monta\u00f1a"),
    # 57
    ("The Gentle",
     "Persistent gentle penetration achieves what aggression cannot",
     "Winds following one another \xe2\x80\x94 the sage spreads his commands and carries out his affairs",
     "Penetration, influence, subtlety", "Wind/Wind",
     "Lo Suave",
     "La suave penetraci\u00f3n persistente logra lo que la agresi\u00f3n no puede",
     "Vientos que se suceden \xe2\x80\x94 el sabio difunde sus mandatos y lleva a cabo sus asuntos",
     "Penetraci\u00f3n, influencia, sutileza", "Viento/Viento"),
    # 58
    ("The Joyous",
     "True joy comes from inner firmness expressed with outward gentleness",
     "Lakes joined together \xe2\x80\x94 the sage joins with friends for discussion and practice",
     "Joy, communication, fellowship", "Lake/Lake",
     "Lo Sereno",
     "La verdadera alegr\u00eda proviene de la firmeza interior expresada con gentileza exterior",
     "Lagos unidos \xe2\x80\x94 el sabio se une con amigos para la discusi\u00f3n y la pr\u00e1ctica",
     "Alegr\u00eda, comunicaci\u00f3n, hermandad", "Lago/Lago"),
    # 59
    ("Dispersion",
     "Wind over water disperses rigid separations \xe2\x80\x94 use gentle means to dissolve barriers",
     "Wind drives over the water \xe2\x80\x94 the ancient kings made offerings and built temples",
     "Dissolution, unity, devotion", "Wind/Water",
     "La Dispersi\u00f3n",
     "Viento sobre agua dispersa las separaciones r\u00edgidas \xe2\x80\x94 usa medios suaves para disolver barreras",
     "El viento sopla sobre el agua \xe2\x80\x94 los antiguos reyes hac\u00edan ofrendas y constru\u00edan templos",
     "Disoluci\u00f3n, unidad, devoci\u00f3n", "Viento/Agua"),
    # 60
    ("Limitation",
     "Proper limits bring structure \xe2\x80\x94 but bitter limitations should not be held to",
     "Water over the lake \xe2\x80\x94 the sage creates number and measure to examine virtue and conduct",
     "Limitation, moderation, structure", "Water/Lake",
     "La Limitaci\u00f3n",
     "Los l\u00edmites apropiados traen estructura \xe2\x80\x94 pero las limitaciones amargas no deben mantenerse",
     "Agua sobre el lago \xe2\x80\x94 el sabio crea n\u00famero y medida para examinar la virtud y la conducta",
     "Limitaci\u00f3n, moderaci\u00f3n, estructura", "Agua/Lago"),
    # 61
    ("Inner Truth",
     "Inner truth reaches even pigs and fish \xe2\x80\x94 sincerity moves all beings",
     "Wind over the lake \xe2\x80\x94 the sage deliberates upon punishments and delays execution",
     "Sincerity, empathy, truth", "Wind/Lake",
     "La Verdad Interior",
     "La verdad interior alcanza incluso a cerdos y peces \xe2\x80\x94 la sinceridad conmueve a todos los seres",
     "Viento sobre el lago \xe2\x80\x94 el sabio delibera sobre los castigos y retrasa la ejecuci\u00f3n",
     "Sinceridad, empat\u00eda, verdad", "Viento/Lago"),
    # 62
    ("Small Excess",
     "In small matters excess is permissible \xe2\x80\x94 the flying bird leaves its song behind",
     "Thunder on the mountain \xe2\x80\x94 the sage is reverent in conduct and sorrowful in mourning",
     "Modesty, detail, caution", "Thunder/Mountain",
     "La Preponderancia de lo Peque\u00f1o",
     "En asuntos peque\u00f1os el exceso es permisible \xe2\x80\x94 el p\u00e1jaro que vuela deja su canto atr\u00e1s",
     "Trueno sobre la monta\u00f1a \xe2\x80\x94 el sabio es reverente en la conducta y compungido en el duelo",
     "Modestia, detalle, cautela", "Trueno/Monta\u00f1a"),
    # 63
    ("After Completion",
     "All lines in their proper place \xe2\x80\x94 success, but vigilance against disorder",
     "Water over fire \xe2\x80\x94 the sage reflects on misfortune and prepares against it",
     "Completion, vigilance, order", "Water/Fire",
     "Despu\u00e9s de la Consumaci\u00f3n",
     "Todas las l\u00edneas en su lugar apropiado \xe2\x80\x94 \u00e9xito, pero vigilancia contra el desorden",
     "Agua sobre fuego \xe2\x80\x94 el sabio reflexiona sobre la desgracia y se prepara contra ella",
     "Consumaci\u00f3n, vigilancia, orden", "Agua/Fuego"),
    # 64
    ("Before Completion",
     "The final crossing is not yet accomplished \xe2\x80\x94 careful discernment of forces is needed",
     "Fire over water \xe2\x80\x94 the sage carefully distinguishes things and puts them in their places",
     "Transition, potential, discernment", "Fire/Water",
     "Antes de la Consumaci\u00f3n",
     "El cruce final a\u00fan no se ha consumado \xe2\x80\x94 se necesita un cuidadoso discernimiento de fuerzas",
     "Fuego sobre agua \xe2\x80\x94 el sabio distingue cuidadosamente las cosas y las pone en su lugar",
     "Transici\u00f3n, potencial, discernimiento", "Fuego/Agua"),
]

for i, h in enumerate(HEXAGRAMS):
    n = i + 1
    ICHING_EN[f"iching.hex.{n}.name"] = h[0]
    ICHING_EN[f"iching.hex.{n}.judgment"] = h[1]
    ICHING_EN[f"iching.hex.{n}.image"] = h[2]
    ICHING_EN[f"iching.hex.{n}.keywords"] = h[3]
    ICHING_EN[f"iching.hex.{n}.element"] = h[4]
    ICHING_ES[f"iching.hex.{n}.name"] = h[5]
    ICHING_ES[f"iching.hex.{n}.judgment"] = h[6]
    ICHING_ES[f"iching.hex.{n}.image"] = h[7]
    ICHING_ES[f"iching.hex.{n}.keywords"] = h[8]
    ICHING_ES[f"iching.hex.{n}.element"] = h[9]


# ============================================================
# HUMAN DESIGN — types + authorities + profiles + centers
# ============================================================

HD_EN = {
    "hd.tpl.glance": "%1$s %2$s \xe2\x80\x94 Gate %3$d: %4$s",
    "hd.tpl.detail": "Type: %1$s. Strategy: %2$s. Signature: %3$s. Not-Self: %4$s. Aura: %5$s. Authority: %6$s \xe2\x80\x94 %7$s. Profile: %8$s (%9$s). %10$s / %11$s. Sun Gate %12$d: %13$s (%14$s). %15$s.",
    # Types
    "hd.type.0.name": "Manifestor", "hd.type.0.strategy": "To Inform",
    "hd.type.0.signature": "Peace", "hd.type.0.not_self": "Anger",
    "hd.type.0.aura": "Closed and repelling \xe2\x80\x94 pushes energy outward to initiate",
    "hd.type.0.brief": "The initiator who sets things in motion \xe2\x80\x94 designed to act independently and inform others",
    "hd.type.0.abbr": "Mft",
    "hd.type.1.name": "Generator", "hd.type.1.strategy": "To Respond",
    "hd.type.1.signature": "Satisfaction", "hd.type.1.not_self": "Frustration",
    "hd.type.1.aura": "Open and enveloping \xe2\x80\x94 draws life toward it magnetically",
    "hd.type.1.brief": "The life force of the planet \xe2\x80\x94 designed to find the right work through gut response",
    "hd.type.1.abbr": "Gen",
    "hd.type.2.name": "Manifesting Generator", "hd.type.2.strategy": "To Respond, Then Inform",
    "hd.type.2.signature": "Satisfaction", "hd.type.2.not_self": "Frustration",
    "hd.type.2.aura": "Open and enveloping \xe2\x80\x94 draws life while accelerating toward action",
    "hd.type.2.brief": "The multi-passionate builder \xe2\x80\x94 responds first, then initiates with sustainable energy",
    "hd.type.2.abbr": "MaG",
    "hd.type.3.name": "Projector", "hd.type.3.strategy": "To Wait for the Invitation",
    "hd.type.3.signature": "Success", "hd.type.3.not_self": "Bitterness",
    "hd.type.3.aura": "Focused and absorbing \xe2\x80\x94 penetrates into the other's aura to see deeply",
    "hd.type.3.brief": "The guide who sees others clearly \xe2\x80\x94 designed to direct energy, not generate it",
    "hd.type.3.abbr": "Prj",
    "hd.type.4.name": "Reflector", "hd.type.4.strategy": "To Wait a Lunar Cycle",
    "hd.type.4.signature": "Surprise", "hd.type.4.not_self": "Disappointment",
    "hd.type.4.aura": "Resistant and sampling \xe2\x80\x94 reflects the health of the community",
    "hd.type.4.brief": "The mirror of the community \xe2\x80\x94 designed to evaluate by reflecting the world through a full lunar cycle",
    "hd.type.4.abbr": "Ref",
    # Authorities
    "hd.auth.0.name": "Emotional",
    "hd.auth.0.process": "Ride the emotional wave \xe2\x80\x94 clarity comes over time, never in the moment",
    "hd.auth.0.signal": "Wait for emotional clarity across highs and lows before deciding",
    "hd.auth.0.brief": "Decisions emerge from emotional patience \xe2\x80\x94 there is no truth in the now",
    "hd.auth.1.name": "Sacral",
    "hd.auth.1.process": "Listen to the gut response \xe2\x80\x94 an immediate uh-huh or uhn-uhn",
    "hd.auth.1.signal": "A visceral, in-the-body yes or no that bypasses the mind",
    "hd.auth.1.brief": "The body knows before the mind \xe2\x80\x94 respond to life through sacral sounds",
    "hd.auth.2.name": "Splenic",
    "hd.auth.2.process": "Trust the spontaneous knowing \xe2\x80\x94 the spleen speaks once and softly",
    "hd.auth.2.signal": "A quiet, instantaneous hit of intuition that does not repeat",
    "hd.auth.2.brief": "Survival intelligence speaks in the moment \xe2\x80\x94 trust the first instinct",
    "hd.auth.3.name": "Ego",
    "hd.auth.3.process": "Honor what the heart truly wants \xe2\x80\x94 willpower aligned with desire",
    "hd.auth.3.signal": "A sense of what you have the will and heart to commit to",
    "hd.auth.3.brief": "The heart center drives commitment \xe2\x80\x94 only promise what the ego can sustain",
    "hd.auth.4.name": "Self-Projected",
    "hd.auth.4.process": "Hear yourself speak your truth \xe2\x80\x94 the voice reveals direction",
    "hd.auth.4.signal": "Listen to what comes out of your mouth when you speak about the decision",
    "hd.auth.4.brief": "Identity speaks through the voice \xe2\x80\x94 talk it through with trusted others",
    "hd.auth.5.name": "Mental",
    "hd.auth.5.process": "Use the mind as a sounding board \xe2\x80\x94 no inner authority, rely on environment",
    "hd.auth.5.signal": "Discuss with others and notice what feels right in different environments",
    "hd.auth.5.brief": "No defined inner authority \xe2\x80\x94 decisions emerge through dialogue and environment",
    "hd.auth.6.name": "Lunar",
    "hd.auth.6.process": "Wait through a full 28-day lunar cycle \xe2\x80\x94 sample all transits before deciding",
    "hd.auth.6.signal": "After a full moon cycle, notice which option consistently felt right",
    "hd.auth.6.brief": "The moon's transit through all 64 gates reveals clarity \xe2\x80\x94 patience is everything",
    # Profiles (12)
    "hd.profile.0.theme": "Investigator / Martyr",
    "hd.profile.0.conscious": "Investigator \xe2\x80\x94 driven to build a secure foundation of knowledge",
    "hd.profile.0.unconscious": "Martyr \xe2\x80\x94 learns through trial and error, discovering what doesn't work",
    "hd.profile.0.brief": "The deeply experiential researcher \xe2\x80\x94 builds certainty through investigation and breakdowns",
    "hd.profile.1.theme": "Investigator / Opportunist",
    "hd.profile.1.conscious": "Investigator \xe2\x80\x94 needs a solid knowledge foundation before acting",
    "hd.profile.1.unconscious": "Opportunist \xe2\x80\x94 opportunities flow through personal networks and relationships",
    "hd.profile.1.brief": "The networked scholar \xe2\x80\x94 deep research shared through close community",
    "hd.profile.2.theme": "Hermit / Opportunist",
    "hd.profile.2.conscious": "Hermit \xe2\x80\x94 possesses natural talent that needs calling out by others",
    "hd.profile.2.unconscious": "Opportunist \xe2\x80\x94 life moves through relationship networks",
    "hd.profile.2.brief": "The naturally gifted friend \xe2\x80\x94 talent emerges when called by the right people",
    "hd.profile.3.theme": "Hermit / Heretic",
    "hd.profile.3.conscious": "Hermit \xe2\x80\x94 natural gifts that require solitude to develop",
    "hd.profile.3.unconscious": "Heretic \xe2\x80\x94 universalizing projections attract practical solutions from others",
    "hd.profile.3.brief": "The reluctant savior \xe2\x80\x94 called from isolation to deliver practical solutions",
    "hd.profile.4.theme": "Martyr / Heretic",
    "hd.profile.4.conscious": "Martyr \xe2\x80\x94 learns through bonds made and broken, trial and error",
    "hd.profile.4.unconscious": "Heretic \xe2\x80\x94 projected upon as having universal answers",
    "hd.profile.4.brief": "The resilient problem-solver \xe2\x80\x94 experience-born wisdom that others seek out",
    "hd.profile.5.theme": "Martyr / Role Model",
    "hd.profile.5.conscious": "Martyr \xe2\x80\x94 discovers through experimentation and broken bonds",
    "hd.profile.5.unconscious": "Role Model \xe2\x80\x94 three life phases: trial (to 30), observer (30-50), exemplar (50+)",
    "hd.profile.5.brief": "The experiential sage \xe2\x80\x94 hard-won wisdom that eventually becomes living example",
    "hd.profile.6.theme": "Opportunist / Role Model",
    "hd.profile.6.conscious": "Opportunist \xe2\x80\x94 influence flows through close community bonds",
    "hd.profile.6.unconscious": "Role Model \xe2\x80\x94 three life phases: trial, retreat to the roof, then embodied wisdom",
    "hd.profile.6.brief": "The trusted mentor \xe2\x80\x94 community-rooted guidance that matures into role model leadership",
    "hd.profile.7.theme": "Opportunist / Investigator",
    "hd.profile.7.conscious": "Opportunist \xe2\x80\x94 life direction comes through relationships",
    "hd.profile.7.unconscious": "Investigator \xe2\x80\x94 unconscious need for deep, authoritative foundation",
    "hd.profile.7.brief": "The fixed foundation networker \xe2\x80\x94 once the foundation is set, it does not change",
    "hd.profile.8.theme": "Heretic / Investigator",
    "hd.profile.8.conscious": "Heretic \xe2\x80\x94 others project universal solutions onto you",
    "hd.profile.8.unconscious": "Investigator \xe2\x80\x94 unconscious need to deeply research before delivering",
    "hd.profile.8.brief": "The practical general \xe2\x80\x94 deeply researched solutions delivered to meet projections",
    "hd.profile.9.theme": "Heretic / Hermit",
    "hd.profile.9.conscious": "Heretic \xe2\x80\x94 projected upon as having the answer",
    "hd.profile.9.unconscious": "Hermit \xe2\x80\x94 unconscious natural talent that needs withdrawal to recharge",
    "hd.profile.9.brief": "The called savior \xe2\x80\x94 natural talent projected upon by others, needing retreat",
    "hd.profile.10.theme": "Role Model / Hermit",
    "hd.profile.10.conscious": "Role Model \xe2\x80\x94 three life phases: trial, observation, embodiment",
    "hd.profile.10.unconscious": "Hermit \xe2\x80\x94 unconscious natural gift that flourishes in solitude",
    "hd.profile.10.brief": "The wise recluse \xe2\x80\x94 three-phase maturation with natural gifts that emerge alone",
    "hd.profile.11.theme": "Role Model / Martyr",
    "hd.profile.11.conscious": "Role Model \xe2\x80\x94 three-phase life journey toward authentic embodiment",
    "hd.profile.11.unconscious": "Martyr \xe2\x80\x94 unconscious drive to discover through trial and error",
    "hd.profile.11.brief": "The experienced optimist \xe2\x80\x94 double trial process that ultimately models authentic living",
    # Centers (9)
    "hd.center.0.name": "Head", "hd.center.0.defined": "Consistent mental pressure to think, question, and wonder",
    "hd.center.0.open": "Amplifies others' inspiration \xe2\x80\x94 overwhelmed by questions that aren't yours",
    "hd.center.0.question": "Am I trying to answer everybody else's questions?",
    "hd.center.0.biological": "Pineal gland",
    "hd.center.1.name": "Ajna", "hd.center.1.defined": "Fixed way of processing and conceptualizing information",
    "hd.center.1.open": "Open to all ways of thinking \xe2\x80\x94 wisdom is mental flexibility",
    "hd.center.1.question": "Am I trying to convince everyone I'm certain?",
    "hd.center.1.biological": "Anterior and posterior pituitary",
    "hd.center.2.name": "Throat", "hd.center.2.defined": "Consistent voice and capacity to manifest through expression",
    "hd.center.2.open": "Adapts communication to the audience \xe2\x80\x94 pressure to speak or act prematurely",
    "hd.center.2.question": "Am I trying to attract attention?",
    "hd.center.2.biological": "Thyroid and parathyroid",
    "hd.center.3.name": "G Center", "hd.center.3.defined": "Fixed sense of identity, direction, and love",
    "hd.center.3.open": "Shape-shifts identity depending on environment and companions",
    "hd.center.3.question": "Am I still looking for love and direction?",
    "hd.center.3.biological": "Liver and blood",
    "hd.center.4.name": "Heart", "hd.center.4.defined": "Reliable willpower and capacity for material promises",
    "hd.center.4.open": "Inconsistent willpower \xe2\x80\x94 wisdom is not needing to prove self-worth",
    "hd.center.4.question": "Am I still trying to prove myself?",
    "hd.center.4.biological": "Heart, stomach, gallbladder, thymus",
    "hd.center.5.name": "Spleen", "hd.center.5.defined": "Consistent intuition, immune response, and survival awareness",
    "hd.center.5.open": "Amplifies health and fear signals \xe2\x80\x94 holds on to what should be released",
    "hd.center.5.question": "Am I still holding on to what isn't good for me?",
    "hd.center.5.biological": "Lymphatic system, spleen, T-cells",
    "hd.center.6.name": "Sacral", "hd.center.6.defined": "Sustainable life force and work energy \xe2\x80\x94 the Generator's engine",
    "hd.center.6.open": "Inconsistent energy \xe2\x80\x94 wisdom is knowing when enough is enough",
    "hd.center.6.question": "Do I know when enough is enough?",
    "hd.center.6.biological": "Ovaries and testes",
    "hd.center.7.name": "Solar Plexus", "hd.center.7.defined": "Emotional wave that brings depth, passion, and feeling to experience",
    "hd.center.7.open": "Empathic amplifier \xe2\x80\x94 absorbs and magnifies the emotions of others",
    "hd.center.7.question": "Am I avoiding confrontation and truth?",
    "hd.center.7.biological": "Kidneys, prostate, pancreas, nervous system",
    "hd.center.8.name": "Root", "hd.center.8.defined": "Consistent adrenal pressure that drives action and momentum",
    "hd.center.8.open": "Amplifies stress \xe2\x80\x94 pressure to hurry and be free of the pressure",
    "hd.center.8.question": "Am I in a hurry to be free of the pressure?",
    "hd.center.8.biological": "Adrenal glands",
}

HD_ES = {
    "hd.tpl.glance": "%1$s %2$s \xe2\x80\x94 Puerta %3$d: %4$s",
    "hd.tpl.detail": "Tipo: %1$s. Estrategia: %2$s. Firma: %3$s. No-Ser: %4$s. Aura: %5$s. Autoridad: %6$s \xe2\x80\x94 %7$s. Perfil: %8$s (%9$s). %10$s / %11$s. Puerta Solar %12$d: %13$s (%14$s). %15$s.",
    # Types
    "hd.type.0.name": "Manifestador", "hd.type.0.strategy": "Informar",
    "hd.type.0.signature": "Paz", "hd.type.0.not_self": "Ira",
    "hd.type.0.aura": "Cerrada y repelente \xe2\x80\x94 empuja la energ\u00eda hacia afuera para iniciar",
    "hd.type.0.brief": "El iniciador que pone las cosas en movimiento \xe2\x80\x94 dise\u00f1ado para actuar independientemente e informar a otros",
    "hd.type.0.abbr": "Mft",
    "hd.type.1.name": "Generador", "hd.type.1.strategy": "Responder",
    "hd.type.1.signature": "Satisfacci\u00f3n", "hd.type.1.not_self": "Frustraci\u00f3n",
    "hd.type.1.aura": "Abierta y envolvente \xe2\x80\x94 atrae la vida hacia s\u00ed magn\u00e9ticamente",
    "hd.type.1.brief": "La fuerza vital del planeta \xe2\x80\x94 dise\u00f1ado para encontrar el trabajo correcto a trav\u00e9s de la respuesta visceral",
    "hd.type.1.abbr": "Gen",
    "hd.type.2.name": "Generador Manifestante", "hd.type.2.strategy": "Responder, Luego Informar",
    "hd.type.2.signature": "Satisfacci\u00f3n", "hd.type.2.not_self": "Frustraci\u00f3n",
    "hd.type.2.aura": "Abierta y envolvente \xe2\x80\x94 atrae la vida mientras acelera hacia la acci\u00f3n",
    "hd.type.2.brief": "El constructor multipasional \xe2\x80\x94 responde primero, luego inicia con energ\u00eda sostenible",
    "hd.type.2.abbr": "MaG",
    "hd.type.3.name": "Proyector", "hd.type.3.strategy": "Esperar la Invitaci\u00f3n",
    "hd.type.3.signature": "\u00c9xito", "hd.type.3.not_self": "Amargura",
    "hd.type.3.aura": "Enfocada y absorbente \xe2\x80\x94 penetra en el aura del otro para ver profundamente",
    "hd.type.3.brief": "El gu\u00eda que ve a otros claramente \xe2\x80\x94 dise\u00f1ado para dirigir energ\u00eda, no generarla",
    "hd.type.3.abbr": "Prj",
    "hd.type.4.name": "Reflector", "hd.type.4.strategy": "Esperar un Ciclo Lunar",
    "hd.type.4.signature": "Sorpresa", "hd.type.4.not_self": "Decepci\u00f3n",
    "hd.type.4.aura": "Resistente y muestreadora \xe2\x80\x94 refleja la salud de la comunidad",
    "hd.type.4.brief": "El espejo de la comunidad \xe2\x80\x94 dise\u00f1ado para evaluar reflejando el mundo a trav\u00e9s de un ciclo lunar completo",
    "hd.type.4.abbr": "Ref",
    # Authorities
    "hd.auth.0.name": "Emocional",
    "hd.auth.0.process": "Cabalga la ola emocional \xe2\x80\x94 la claridad llega con el tiempo, nunca en el momento",
    "hd.auth.0.signal": "Espera la claridad emocional a trav\u00e9s de altos y bajos antes de decidir",
    "hd.auth.0.brief": "Las decisiones emergen de la paciencia emocional \xe2\x80\x94 no hay verdad en el ahora",
    "hd.auth.1.name": "Sacral",
    "hd.auth.1.process": "Escucha la respuesta visceral \xe2\x80\x94 un inmediato aj\u00e1 o uhn-uhn",
    "hd.auth.1.signal": "Un s\u00ed o no visceral, en el cuerpo, que elude la mente",
    "hd.auth.1.brief": "El cuerpo sabe antes que la mente \xe2\x80\x94 responde a la vida a trav\u00e9s de sonidos sacrales",
    "hd.auth.2.name": "Espl\u00e9nico",
    "hd.auth.2.process": "Conf\u00eda en el saber espont\u00e1neo \xe2\x80\x94 el bazo habla una vez y suavemente",
    "hd.auth.2.signal": "Un golpe silencioso e instant\u00e1neo de intuici\u00f3n que no se repite",
    "hd.auth.2.brief": "La inteligencia de supervivencia habla en el momento \xe2\x80\x94 conf\u00eda en el primer instinto",
    "hd.auth.3.name": "Ego",
    "hd.auth.3.process": "Honra lo que el coraz\u00f3n verdaderamente quiere \xe2\x80\x94 voluntad alineada con el deseo",
    "hd.auth.3.signal": "La sensaci\u00f3n de aquello a lo que tienes la voluntad y el coraz\u00f3n para comprometerte",
    "hd.auth.3.brief": "El centro del coraz\u00f3n impulsa el compromiso \xe2\x80\x94 solo promete lo que el ego pueda sostener",
    "hd.auth.4.name": "Auto-Proyectado",
    "hd.auth.4.process": "Esc\u00fachate hablar tu verdad \xe2\x80\x94 la voz revela la direcci\u00f3n",
    "hd.auth.4.signal": "Escucha lo que sale de tu boca cuando hablas sobre la decisi\u00f3n",
    "hd.auth.4.brief": "La identidad habla a trav\u00e9s de la voz \xe2\x80\x94 habla con personas de confianza",
    "hd.auth.5.name": "Mental",
    "hd.auth.5.process": "Usa la mente como caja de resonancia \xe2\x80\x94 sin autoridad interna, depende del entorno",
    "hd.auth.5.signal": "Discute con otros y nota qu\u00e9 se siente correcto en diferentes entornos",
    "hd.auth.5.brief": "Sin autoridad interna definida \xe2\x80\x94 las decisiones emergen del di\u00e1logo y el entorno",
    "hd.auth.6.name": "Lunar",
    "hd.auth.6.process": "Espera un ciclo lunar completo de 28 d\u00edas \xe2\x80\x94 muestrea todos los tr\u00e1nsitos antes de decidir",
    "hd.auth.6.signal": "Despu\u00e9s de un ciclo lunar completo, nota qu\u00e9 opci\u00f3n se sinti\u00f3 consistentemente correcta",
    "hd.auth.6.brief": "El tr\u00e1nsito de la luna por las 64 puertas revela claridad \xe2\x80\x94 la paciencia lo es todo",
    # Profiles
    "hd.profile.0.theme": "Investigador / M\u00e1rtir",
    "hd.profile.0.conscious": "Investigador \xe2\x80\x94 impulsado a construir una base s\u00f3lida de conocimiento",
    "hd.profile.0.unconscious": "M\u00e1rtir \xe2\x80\x94 aprende por ensayo y error, descubriendo lo que no funciona",
    "hd.profile.0.brief": "El investigador profundamente experiencial \xe2\x80\x94 construye certeza a trav\u00e9s de la investigaci\u00f3n y las crisis",
    "hd.profile.1.theme": "Investigador / Oportunista",
    "hd.profile.1.conscious": "Investigador \xe2\x80\x94 necesita una base s\u00f3lida de conocimiento antes de actuar",
    "hd.profile.1.unconscious": "Oportunista \xe2\x80\x94 las oportunidades fluyen a trav\u00e9s de redes personales y relaciones",
    "hd.profile.1.brief": "El erudito conectado \xe2\x80\x94 investigaci\u00f3n profunda compartida a trav\u00e9s de la comunidad cercana",
    "hd.profile.2.theme": "Ermita\u00f1o / Oportunista",
    "hd.profile.2.conscious": "Ermita\u00f1o \xe2\x80\x94 posee talento natural que necesita ser reconocido por otros",
    "hd.profile.2.unconscious": "Oportunista \xe2\x80\x94 la vida se mueve a trav\u00e9s de redes de relaciones",
    "hd.profile.2.brief": "El amigo naturalmente dotado \xe2\x80\x94 el talento emerge cuando lo llaman las personas correctas",
    "hd.profile.3.theme": "Ermita\u00f1o / Hereje",
    "hd.profile.3.conscious": "Ermita\u00f1o \xe2\x80\x94 dones naturales que requieren soledad para desarrollarse",
    "hd.profile.3.unconscious": "Hereje \xe2\x80\x94 las proyecciones universalizantes atraen soluciones pr\u00e1cticas de otros",
    "hd.profile.3.brief": "El salvador renuente \xe2\x80\x94 llamado desde el aislamiento para entregar soluciones pr\u00e1cticas",
    "hd.profile.4.theme": "M\u00e1rtir / Hereje",
    "hd.profile.4.conscious": "M\u00e1rtir \xe2\x80\x94 aprende a trav\u00e9s de lazos hechos y rotos, ensayo y error",
    "hd.profile.4.unconscious": "Hereje \xe2\x80\x94 proyectado como poseedor de respuestas universales",
    "hd.profile.4.brief": "El solucionador resiliente \xe2\x80\x94 sabidur\u00eda nacida de la experiencia que otros buscan",
    "hd.profile.5.theme": "M\u00e1rtir / Modelo a Seguir",
    "hd.profile.5.conscious": "M\u00e1rtir \xe2\x80\x94 descubre a trav\u00e9s de la experimentaci\u00f3n y lazos rotos",
    "hd.profile.5.unconscious": "Modelo a Seguir \xe2\x80\x94 tres fases de vida: prueba (hasta 30), observador (30-50), ejemplo (50+)",
    "hd.profile.5.brief": "El sabio experiencial \xe2\x80\x94 sabidur\u00eda ganada con esfuerzo que eventualmente se convierte en ejemplo vivo",
    "hd.profile.6.theme": "Oportunista / Modelo a Seguir",
    "hd.profile.6.conscious": "Oportunista \xe2\x80\x94 la influencia fluye a trav\u00e9s de lazos comunitarios cercanos",
    "hd.profile.6.unconscious": "Modelo a Seguir \xe2\x80\x94 tres fases: prueba, retiro al techo, luego sabidur\u00eda encarnada",
    "hd.profile.6.brief": "El mentor de confianza \xe2\x80\x94 gu\u00eda enraizada en la comunidad que madura hacia el liderazgo ejemplar",
    "hd.profile.7.theme": "Oportunista / Investigador",
    "hd.profile.7.conscious": "Oportunista \xe2\x80\x94 la direcci\u00f3n de vida viene a trav\u00e9s de relaciones",
    "hd.profile.7.unconscious": "Investigador \xe2\x80\x94 necesidad inconsciente de una base profunda y autoritativa",
    "hd.profile.7.brief": "El networker de base fija \xe2\x80\x94 una vez establecida la base, no cambia",
    "hd.profile.8.theme": "Hereje / Investigador",
    "hd.profile.8.conscious": "Hereje \xe2\x80\x94 otros proyectan soluciones universales sobre ti",
    "hd.profile.8.unconscious": "Investigador \xe2\x80\x94 necesidad inconsciente de investigar profundamente antes de entregar",
    "hd.profile.8.brief": "El general pr\u00e1ctico \xe2\x80\x94 soluciones profundamente investigadas entregadas para cumplir proyecciones",
    "hd.profile.9.theme": "Hereje / Ermita\u00f1o",
    "hd.profile.9.conscious": "Hereje \xe2\x80\x94 proyectado como poseedor de la respuesta",
    "hd.profile.9.unconscious": "Ermita\u00f1o \xe2\x80\x94 talento natural inconsciente que necesita retirarse para recargarse",
    "hd.profile.9.brief": "El salvador llamado \xe2\x80\x94 talento natural proyectado por otros, necesitando retiro",
    "hd.profile.10.theme": "Modelo a Seguir / Ermita\u00f1o",
    "hd.profile.10.conscious": "Modelo a Seguir \xe2\x80\x94 tres fases de vida: prueba, observaci\u00f3n, encarnaci\u00f3n",
    "hd.profile.10.unconscious": "Ermita\u00f1o \xe2\x80\x94 don natural inconsciente que florece en soledad",
    "hd.profile.10.brief": "El sabio recluso \xe2\x80\x94 maduraci\u00f3n en tres fases con dones naturales que emergen en soledad",
    "hd.profile.11.theme": "Modelo a Seguir / M\u00e1rtir",
    "hd.profile.11.conscious": "Modelo a Seguir \xe2\x80\x94 viaje vital de tres fases hacia la encarnaci\u00f3n aut\u00e9ntica",
    "hd.profile.11.unconscious": "M\u00e1rtir \xe2\x80\x94 impulso inconsciente de descubrir por ensayo y error",
    "hd.profile.11.brief": "El optimista experimentado \xe2\x80\x94 doble proceso de prueba que finalmente modela una vida aut\u00e9ntica",
    # Centers
    "hd.center.0.name": "Cabeza", "hd.center.0.defined": "Presi\u00f3n mental constante para pensar, cuestionar y asombrarse",
    "hd.center.0.open": "Amplifica la inspiraci\u00f3n ajena \xe2\x80\x94 abrumado por preguntas que no son tuyas",
    "hd.center.0.question": "\u00bfEstoy tratando de responder las preguntas de todos los dem\u00e1s?",
    "hd.center.0.biological": "Gl\u00e1ndula pineal",
    "hd.center.1.name": "Ajna", "hd.center.1.defined": "Forma fija de procesar y conceptualizar informaci\u00f3n",
    "hd.center.1.open": "Abierto a todas las formas de pensamiento \xe2\x80\x94 la sabidur\u00eda es flexibilidad mental",
    "hd.center.1.question": "\u00bfEstoy tratando de convencer a todos de que estoy seguro?",
    "hd.center.1.biological": "Pit\u00faitaria anterior y posterior",
    "hd.center.2.name": "Garganta", "hd.center.2.defined": "Voz consistente y capacidad de manifestar a trav\u00e9s de la expresi\u00f3n",
    "hd.center.2.open": "Adapta la comunicaci\u00f3n a la audiencia \xe2\x80\x94 presi\u00f3n para hablar o actuar prematuramente",
    "hd.center.2.question": "\u00bfEstoy tratando de atraer la atenci\u00f3n?",
    "hd.center.2.biological": "Tiroides y paratiroides",
    "hd.center.3.name": "Centro G", "hd.center.3.defined": "Sentido fijo de identidad, direcci\u00f3n y amor",
    "hd.center.3.open": "La identidad cambia seg\u00fan el entorno y los compa\u00f1eros",
    "hd.center.3.question": "\u00bfSigo buscando amor y direcci\u00f3n?",
    "hd.center.3.biological": "H\u00edgado y sangre",
    "hd.center.4.name": "Coraz\u00f3n", "hd.center.4.defined": "Voluntad confiable y capacidad para promesas materiales",
    "hd.center.4.open": "Voluntad inconsistente \xe2\x80\x94 la sabidur\u00eda es no necesitar probar la autovaloraci\u00f3n",
    "hd.center.4.question": "\u00bfSigo tratando de probarme a m\u00ed mismo?",
    "hd.center.4.biological": "Coraz\u00f3n, est\u00f3mago, ves\u00edcula biliar, timo",
    "hd.center.5.name": "Bazo", "hd.center.5.defined": "Intuici\u00f3n constante, respuesta inmune y conciencia de supervivencia",
    "hd.center.5.open": "Amplifica se\u00f1ales de salud y miedo \xe2\x80\x94 se aferra a lo que deber\u00eda soltar",
    "hd.center.5.question": "\u00bfSigo aferr\u00e1ndome a lo que no es bueno para m\u00ed?",
    "hd.center.5.biological": "Sistema linf\u00e1tico, bazo, c\u00e9lulas T",
    "hd.center.6.name": "Sacral", "hd.center.6.defined": "Fuerza vital sostenible y energ\u00eda de trabajo \xe2\x80\x94 el motor del Generador",
    "hd.center.6.open": "Energ\u00eda inconsistente \xe2\x80\x94 la sabidur\u00eda es saber cu\u00e1ndo es suficiente",
    "hd.center.6.question": "\u00bfS\u00e9 cu\u00e1ndo es suficiente?",
    "hd.center.6.biological": "Ovarios y test\u00edculos",
    "hd.center.7.name": "Plexo Solar", "hd.center.7.defined": "Ola emocional que trae profundidad, pasi\u00f3n y sentimiento a la experiencia",
    "hd.center.7.open": "Amplificador emp\u00e1tico \xe2\x80\x94 absorbe y magnifica las emociones de otros",
    "hd.center.7.question": "\u00bfEstoy evitando la confrontaci\u00f3n y la verdad?",
    "hd.center.7.biological": "Ri\u00f1ones, pr\u00f3stata, p\u00e1ncreas, sistema nervioso",
    "hd.center.8.name": "Ra\u00edz", "hd.center.8.defined": "Presi\u00f3n adrenal constante que impulsa la acci\u00f3n y el momentum",
    "hd.center.8.open": "Amplifica el estr\u00e9s \xe2\x80\x94 presi\u00f3n por apurarse y liberarse de la presi\u00f3n",
    "hd.center.8.question": "\u00bfTengo prisa por liberarme de la presi\u00f3n?",
    "hd.center.8.biological": "Gl\u00e1ndulas suprarrenales",
}


# ============================================================
# KABBALAH — 10 sefirot + 22 paths + templates
# ============================================================

KAB_EN = {
    "kabbalah.tpl.glance": "%1$s \xe2\x80\x94 %2$s",
    "kabbalah.tpl.detail": "%1$s: %2$s. The question: %3$s. Planet: %4$s.",
    # Sefirah names (Hebrew — same in all languages)
    "kabbalah.sefirah.0.name": "Keter", "kabbalah.sefirah.1.name": "Chokmah",
    "kabbalah.sefirah.2.name": "Binah", "kabbalah.sefirah.3.name": "Chesed",
    "kabbalah.sefirah.4.name": "Gevurah", "kabbalah.sefirah.5.name": "Tiferet",
    "kabbalah.sefirah.6.name": "Netzach", "kabbalah.sefirah.7.name": "Hod",
    "kabbalah.sefirah.8.name": "Yesod", "kabbalah.sefirah.9.name": "Malkuth",
    # Meditations
    "kabbalah.sefirah.0.meditation": "Crown \xe2\x80\x94 the point before thought, pure will",
    "kabbalah.sefirah.1.meditation": "Wisdom \xe2\x80\x94 the flash of insight, the father principle",
    "kabbalah.sefirah.2.meditation": "Understanding \xe2\x80\x94 the womb that gives form to wisdom",
    "kabbalah.sefirah.3.meditation": "Mercy \xe2\x80\x94 boundless giving, expansion without limit",
    "kabbalah.sefirah.4.meditation": "Strength \xe2\x80\x94 necessary contraction, judgment, discipline",
    "kabbalah.sefirah.5.meditation": "Beauty \xe2\x80\x94 the heart that balances mercy and judgment",
    "kabbalah.sefirah.6.meditation": "Victory \xe2\x80\x94 endurance, artistic passion, desire",
    "kabbalah.sefirah.7.meditation": "Splendor \xe2\x80\x94 intellect, communication, humility",
    "kabbalah.sefirah.8.meditation": "Foundation \xe2\x80\x94 the gateway between above and below",
    "kabbalah.sefirah.9.meditation": "Kingdom \xe2\x80\x94 the physical world, embodiment, presence",
    # Questions
    "kabbalah.sefirah.0.question": "What exists before I think?",
    "kabbalah.sefirah.1.question": "What is the first spark of creation?",
    "kabbalah.sefirah.2.question": "How does the infinite become finite?",
    "kabbalah.sefirah.3.question": "Where must I give without condition?",
    "kabbalah.sefirah.4.question": "Where must I set boundaries?",
    "kabbalah.sefirah.5.question": "How do I harmonize opposites?",
    "kabbalah.sefirah.6.question": "What drives me to persist?",
    "kabbalah.sefirah.7.question": "How do I serve the truth?",
    "kabbalah.sefirah.8.question": "What connects my inner world to outer reality?",
    "kabbalah.sefirah.9.question": "Am I fully here?",
    # Briefs
    "kabbalah.sefirah.0.brief": "The unknowable origin \xe2\x80\x94 divine will before manifestation",
    "kabbalah.sefirah.1.brief": "Primal wisdom \xe2\x80\x94 the lightning flash that begins all things",
    "kabbalah.sefirah.2.brief": "The great mother \xe2\x80\x94 understanding that shapes raw wisdom into form",
    "kabbalah.sefirah.3.brief": "Unconditional love \xe2\x80\x94 the outpouring of grace",
    "kabbalah.sefirah.4.brief": "Sacred restriction \xe2\x80\x94 strength that shapes through limitation",
    "kabbalah.sefirah.5.brief": "The heart center \xe2\x80\x94 beauty born from the marriage of giving and restraint",
    "kabbalah.sefirah.6.brief": "The fire of eternity \xe2\x80\x94 passion that endures beyond reason",
    "kabbalah.sefirah.7.brief": "The glory of surrender \xe2\x80\x94 mind bowing to what is greater",
    "kabbalah.sefirah.8.brief": "The foundation \xe2\x80\x94 where all upper forces gather before manifesting",
    "kabbalah.sefirah.9.brief": "The kingdom of the present moment \xe2\x80\x94 divinity in matter",
    # Paths (22)
    "kabbalah.path.0.journey": "Stepping into the void with perfect trust",
    "kabbalah.path.0.lesson": "Faith requires no ground to stand on",
    "kabbalah.path.1.journey": "Channeling divine will into conscious creation",
    "kabbalah.path.1.lesson": "The creator creates by becoming transparent to creation",
    "kabbalah.path.2.journey": "The long descent from crown to heart",
    "kabbalah.path.2.lesson": "Wisdom crosses the abyss only through silence",
    "kabbalah.path.3.journey": "Wisdom meeting understanding \xe2\x80\x94 father and mother unite",
    "kabbalah.path.3.lesson": "Creation begins where two principles embrace",
    "kabbalah.path.4.journey": "Raw insight finding its center",
    "kabbalah.path.4.lesson": "Vision must find a heart or it remains blinding light",
    "kabbalah.path.5.journey": "Wisdom flowing into mercy",
    "kabbalah.path.5.lesson": "True teaching is an act of unconditional giving",
    "kabbalah.path.6.journey": "Understanding choosing beauty over severity",
    "kabbalah.path.6.lesson": "The first choice: love or fear \xe2\x80\x94 always love",
    "kabbalah.path.7.journey": "Form becoming discipline",
    "kabbalah.path.7.lesson": "Structure without compassion becomes a prison; with it, a chariot",
    "kabbalah.path.8.journey": "Mercy meeting judgment directly",
    "kabbalah.path.8.lesson": "True strength is mercy that knows when to say no",
    "kabbalah.path.9.journey": "Grace descending to the heart",
    "kabbalah.path.9.lesson": "The lamp of mercy illuminates the path inward",
    "kabbalah.path.10.journey": "Abundance turning into endurance",
    "kabbalah.path.10.lesson": "Fortune changes but passion outlasts every turning",
    "kabbalah.path.11.journey": "Judgment softened by beauty",
    "kabbalah.path.11.lesson": "Balance is not compromise \xe2\x80\x94 it is precision of the heart",
    "kabbalah.path.12.journey": "Severity becoming surrender",
    "kabbalah.path.12.lesson": "The deepest discipline is to stop struggling",
    "kabbalah.path.13.journey": "Heart releasing into passion",
    "kabbalah.path.13.lesson": "Something must die for desire to become authentic",
    "kabbalah.path.14.journey": "Beauty grounding into foundation",
    "kabbalah.path.14.lesson": "Harmony manifests only when it touches the ground",
    "kabbalah.path.15.journey": "Heart confronting the shadow",
    "kabbalah.path.15.lesson": "Beauty must include darkness or it becomes a lie",
    "kabbalah.path.16.journey": "Passion and intellect shattering illusion",
    "kabbalah.path.16.lesson": "When desire and truth collide, every false structure falls",
    "kabbalah.path.17.journey": "Passion entering dreams",
    "kabbalah.path.17.lesson": "The unconscious speaks in the language of what you love",
    "kabbalah.path.18.journey": "Desire becoming embodied",
    "kabbalah.path.18.lesson": "Joy is passion that has found a body",
    "kabbalah.path.19.journey": "Intellect awakening the foundation",
    "kabbalah.path.19.lesson": "The mind\xe2\x80\x99s final gift: calling the soul to rise",
    "kabbalah.path.20.journey": "Understanding completing itself in matter",
    "kabbalah.path.20.lesson": "The scholar\xe2\x80\x99s path ends where the hands begin",
    "kabbalah.path.21.journey": "Foundation becoming kingdom",
    "kabbalah.path.21.lesson": "The last step: making the invisible visible",
}

KAB_ES = {
    "kabbalah.tpl.glance": "%1$s \xe2\x80\x94 %2$s",
    "kabbalah.tpl.detail": "%1$s: %2$s. La pregunta: %3$s. Planeta: %4$s.",
    # Names stay Hebrew
    "kabbalah.sefirah.0.name": "Keter", "kabbalah.sefirah.1.name": "Chokmah",
    "kabbalah.sefirah.2.name": "Binah", "kabbalah.sefirah.3.name": "Chesed",
    "kabbalah.sefirah.4.name": "Gevurah", "kabbalah.sefirah.5.name": "Tiferet",
    "kabbalah.sefirah.6.name": "Netzach", "kabbalah.sefirah.7.name": "Hod",
    "kabbalah.sefirah.8.name": "Yesod", "kabbalah.sefirah.9.name": "Malkuth",
    # Meditations
    "kabbalah.sefirah.0.meditation": "Corona \xe2\x80\x94 el punto antes del pensamiento, voluntad pura",
    "kabbalah.sefirah.1.meditation": "Sabidur\u00eda \xe2\x80\x94 el destello de percepci\u00f3n, el principio paterno",
    "kabbalah.sefirah.2.meditation": "Entendimiento \xe2\x80\x94 el vientre que da forma a la sabidur\u00eda",
    "kabbalah.sefirah.3.meditation": "Misericordia \xe2\x80\x94 dar sin l\u00edmites, expansi\u00f3n sin restricci\u00f3n",
    "kabbalah.sefirah.4.meditation": "Fuerza \xe2\x80\x94 contracci\u00f3n necesaria, juicio, disciplina",
    "kabbalah.sefirah.5.meditation": "Belleza \xe2\x80\x94 el coraz\u00f3n que equilibra misericordia y juicio",
    "kabbalah.sefirah.6.meditation": "Victoria \xe2\x80\x94 resistencia, pasi\u00f3n art\u00edstica, deseo",
    "kabbalah.sefirah.7.meditation": "Esplendor \xe2\x80\x94 intelecto, comunicaci\u00f3n, humildad",
    "kabbalah.sefirah.8.meditation": "Fundamento \xe2\x80\x94 la puerta entre lo de arriba y lo de abajo",
    "kabbalah.sefirah.9.meditation": "Reino \xe2\x80\x94 el mundo f\u00edsico, encarnaci\u00f3n, presencia",
    # Questions
    "kabbalah.sefirah.0.question": "\u00bfQu\u00e9 existe antes de que yo piense?",
    "kabbalah.sefirah.1.question": "\u00bfCu\u00e1l es la primera chispa de la creaci\u00f3n?",
    "kabbalah.sefirah.2.question": "\u00bfC\u00f3mo lo infinito se vuelve finito?",
    "kabbalah.sefirah.3.question": "\u00bfD\u00f3nde debo dar sin condici\u00f3n?",
    "kabbalah.sefirah.4.question": "\u00bfD\u00f3nde debo poner l\u00edmites?",
    "kabbalah.sefirah.5.question": "\u00bfC\u00f3mo armonizo los opuestos?",
    "kabbalah.sefirah.6.question": "\u00bfQu\u00e9 me impulsa a persistir?",
    "kabbalah.sefirah.7.question": "\u00bfC\u00f3mo sirvo a la verdad?",
    "kabbalah.sefirah.8.question": "\u00bfQu\u00e9 conecta mi mundo interior con la realidad exterior?",
    "kabbalah.sefirah.9.question": "\u00bfEstoy plenamente aqu\u00ed?",
    # Briefs
    "kabbalah.sefirah.0.brief": "El origen incognoscible \xe2\x80\x94 voluntad divina antes de la manifestaci\u00f3n",
    "kabbalah.sefirah.1.brief": "Sabidur\u00eda primordial \xe2\x80\x94 el rel\u00e1mpago que inicia todas las cosas",
    "kabbalah.sefirah.2.brief": "La gran madre \xe2\x80\x94 entendimiento que moldea la sabidur\u00eda bruta en forma",
    "kabbalah.sefirah.3.brief": "Amor incondicional \xe2\x80\x94 el desborde de la gracia",
    "kabbalah.sefirah.4.brief": "Restricci\u00f3n sagrada \xe2\x80\x94 fuerza que moldea a trav\u00e9s de la limitaci\u00f3n",
    "kabbalah.sefirah.5.brief": "El centro del coraz\u00f3n \xe2\x80\x94 belleza nacida de la uni\u00f3n del dar y la restricci\u00f3n",
    "kabbalah.sefirah.6.brief": "El fuego de la eternidad \xe2\x80\x94 pasi\u00f3n que perdura m\u00e1s all\u00e1 de la raz\u00f3n",
    "kabbalah.sefirah.7.brief": "La gloria de la rendici\u00f3n \xe2\x80\x94 la mente inclin\u00e1ndose ante lo que es mayor",
    "kabbalah.sefirah.8.brief": "El fundamento \xe2\x80\x94 donde todas las fuerzas superiores se re\u00fanen antes de manifestarse",
    "kabbalah.sefirah.9.brief": "El reino del momento presente \xe2\x80\x94 divinidad en la materia",
    # Paths
    "kabbalah.path.0.journey": "Adentrarse en el vac\u00edo con confianza perfecta",
    "kabbalah.path.0.lesson": "La fe no requiere suelo donde pararse",
    "kabbalah.path.1.journey": "Canalizar la voluntad divina en creaci\u00f3n consciente",
    "kabbalah.path.1.lesson": "El creador crea volvi\u00e9ndose transparente a la creaci\u00f3n",
    "kabbalah.path.2.journey": "El largo descenso de la corona al coraz\u00f3n",
    "kabbalah.path.2.lesson": "La sabidur\u00eda cruza el abismo solo a trav\u00e9s del silencio",
    "kabbalah.path.3.journey": "Sabidur\u00eda encontrando entendimiento \xe2\x80\x94 padre y madre se unen",
    "kabbalah.path.3.lesson": "La creaci\u00f3n comienza donde dos principios se abrazan",
    "kabbalah.path.4.journey": "La percepci\u00f3n cruda encontrando su centro",
    "kabbalah.path.4.lesson": "La visi\u00f3n debe encontrar un coraz\u00f3n o permanece como luz cegadora",
    "kabbalah.path.5.journey": "La sabidur\u00eda fluyendo hacia la misericordia",
    "kabbalah.path.5.lesson": "La verdadera ense\u00f1anza es un acto de dar incondicional",
    "kabbalah.path.6.journey": "El entendimiento eligiendo la belleza sobre la severidad",
    "kabbalah.path.6.lesson": "La primera elecci\u00f3n: amor o miedo \xe2\x80\x94 siempre amor",
    "kabbalah.path.7.journey": "La forma convirti\u00e9ndose en disciplina",
    "kabbalah.path.7.lesson": "La estructura sin compasi\u00f3n se convierte en prisi\u00f3n; con ella, en carro",
    "kabbalah.path.8.journey": "La misericordia encontrando el juicio directamente",
    "kabbalah.path.8.lesson": "La verdadera fuerza es la misericordia que sabe cu\u00e1ndo decir no",
    "kabbalah.path.9.journey": "La gracia descendiendo al coraz\u00f3n",
    "kabbalah.path.9.lesson": "La l\u00e1mpara de la misericordia ilumina el camino interior",
    "kabbalah.path.10.journey": "La abundancia transform\u00e1ndose en resistencia",
    "kabbalah.path.10.lesson": "La fortuna cambia pero la pasi\u00f3n sobrevive a cada giro",
    "kabbalah.path.11.journey": "El juicio suavizado por la belleza",
    "kabbalah.path.11.lesson": "El equilibrio no es compromiso \xe2\x80\x94 es precisi\u00f3n del coraz\u00f3n",
    "kabbalah.path.12.journey": "La severidad convirti\u00e9ndose en rendici\u00f3n",
    "kabbalah.path.12.lesson": "La disciplina m\u00e1s profunda es dejar de luchar",
    "kabbalah.path.13.journey": "El coraz\u00f3n liber\u00e1ndose hacia la pasi\u00f3n",
    "kabbalah.path.13.lesson": "Algo debe morir para que el deseo se vuelva aut\u00e9ntico",
    "kabbalah.path.14.journey": "La belleza enraiz\u00e1ndose en el fundamento",
    "kabbalah.path.14.lesson": "La armon\u00eda se manifiesta solo cuando toca el suelo",
    "kabbalah.path.15.journey": "El coraz\u00f3n confrontando la sombra",
    "kabbalah.path.15.lesson": "La belleza debe incluir la oscuridad o se convierte en mentira",
    "kabbalah.path.16.journey": "Pasi\u00f3n e intelecto destrozando la ilusi\u00f3n",
    "kabbalah.path.16.lesson": "Cuando el deseo y la verdad chocan, toda estructura falsa cae",
    "kabbalah.path.17.journey": "La pasi\u00f3n entrando en los sue\u00f1os",
    "kabbalah.path.17.lesson": "El inconsciente habla en el lenguaje de lo que amas",
    "kabbalah.path.18.journey": "El deseo encarn\u00e1ndose",
    "kabbalah.path.18.lesson": "La alegr\u00eda es la pasi\u00f3n que ha encontrado un cuerpo",
    "kabbalah.path.19.journey": "El intelecto despertando el fundamento",
    "kabbalah.path.19.lesson": "El \u00faltimo don de la mente: llamar al alma a elevarse",
    "kabbalah.path.20.journey": "El entendimiento complet\u00e1ndose en la materia",
    "kabbalah.path.20.lesson": "El camino del erudito termina donde comienzan las manos",
    "kabbalah.path.21.journey": "El fundamento convirti\u00e9ndose en reino",
    "kabbalah.path.21.lesson": "El \u00faltimo paso: hacer visible lo invisible",
}


# ============================================================
# HINDU — 30 tithis + templates
# ============================================================

HINDU_EN = {
    "hindu.tpl.glance": "%1$s -- %2$s . %3$s . %4$s",
    "hindu.tpl.detail": "%1$s: %2$s. Deity: %3$s. %4$s day for %5$s.",
    "hindu.tpl.nakshatra": " Nakshatra: %1$s.",
    "hindu.tpl.yoga": " Yoga: %1$s.",
}

HINDU_ES = {
    "hindu.tpl.glance": "%1$s -- %2$s . %3$s . %4$s",
    "hindu.tpl.detail": "%1$s: %2$s. Deidad: %3$s. D\u00eda %4$s para %5$s.",
    "hindu.tpl.nakshatra": " Nakshatra: %1$s.",
    "hindu.tpl.yoga": " Yoga: %1$s.",
}

# (name, deity, quality, activity, brief,
#  deity_es, quality_es, activity_es, brief_es)
# Names stay Sanskrit in all languages
TITHIS = [
    ("Shukla Pratipada", "Agni", "Auspicious", "Beginning new ventures",
     "First day of the bright fortnight -- new beginnings",
     "Agni", "Auspicioso", "Iniciar nuevos emprendimientos",
     "Primer d\u00eda de la quincena luminosa -- nuevos comienzos"),
    ("Shukla Dvitiya", "Brahma", "Auspicious", "Travel, marriage",
     "Day of creativity and union",
     "Brahma", "Auspicioso", "Viajes, matrimonio",
     "D\u00eda de creatividad y uni\u00f3n"),
    ("Shukla Tritiya", "Gauri", "Very Auspicious", "Rituals, celebrations",
     "Akshaya Tritiya -- prosperity that never diminishes",
     "Gauri", "Muy Auspicioso", "Rituales, celebraciones",
     "Akshaya Tritiya -- prosperidad que nunca disminuye"),
    ("Shukla Chaturthi", "Ganesha", "Neutral", "Warfare, aggression",
     "Day of obstacles and their removal",
     "Ganesha", "Neutro", "Guerra, agresi\u00f3n",
     "D\u00eda de obst\u00e1culos y su remoci\u00f3n"),
    ("Shukla Panchami", "Nagas", "Auspicious", "Learning, education",
     "Day of knowledge -- Vasant Panchami",
     "Nagas", "Auspicioso", "Aprendizaje, educaci\u00f3n",
     "D\u00eda del conocimiento -- Vasant Panchami"),
    ("Shukla Shashthi", "Kartikeya", "Auspicious", "Healing, vitality",
     "Day of divine youth and energy",
     "Kartikeya", "Auspicioso", "Sanaci\u00f3n, vitalidad",
     "D\u00eda de juventud divina y energ\u00eda"),
    ("Shukla Saptami", "Surya", "Auspicious", "Worship, travel",
     "Day of the Sun -- illumination",
     "Surya", "Auspicioso", "Adoraci\u00f3n, viajes",
     "D\u00eda del Sol -- iluminaci\u00f3n"),
    ("Shukla Ashtami", "Shiva", "Neutral", "Fasting, contemplation",
     "Day of transformation -- neither good nor ill",
     "Shiva", "Neutro", "Ayuno, contemplaci\u00f3n",
     "D\u00eda de transformaci\u00f3n -- ni bueno ni malo"),
    ("Shukla Navami", "Durga", "Auspicious", "Courage, determination",
     "Day of the fierce goddess",
     "Durga", "Auspicioso", "Coraje, determinaci\u00f3n",
     "D\u00eda de la diosa feroz"),
    ("Shukla Dashami", "Yama", "Neutral", "Justice, duty",
     "Day of dharmic action",
     "Yama", "Neutro", "Justicia, deber",
     "D\u00eda de acci\u00f3n dh\u00e1rmica"),
    ("Shukla Ekadashi", "Vishnu", "Very Auspicious", "Fasting, devotion",
     "Day of spiritual discipline -- Ekadashi fast",
     "Vishnu", "Muy Auspicioso", "Ayuno, devoci\u00f3n",
     "D\u00eda de disciplina espiritual -- ayuno de Ekadashi"),
    ("Shukla Dvadashi", "Vishnu", "Auspicious", "Charity, pilgrimage",
     "Day of generosity",
     "Vishnu", "Auspicioso", "Caridad, peregrinaci\u00f3n",
     "D\u00eda de generosidad"),
    ("Shukla Trayodashi", "Kamadeva", "Auspicious", "Love, arts, devotion",
     "Day of desire and beauty",
     "Kamadeva", "Auspicioso", "Amor, artes, devoci\u00f3n",
     "D\u00eda del deseo y la belleza"),
    ("Shukla Chaturdashi", "Shiva", "Inauspicious", "Remedial rituals",
     "Day before fullness -- tension and preparation",
     "Shiva", "Desfavorable", "Rituales remediales",
     "D\u00eda antes de la plenitud -- tensi\u00f3n y preparaci\u00f3n"),
    ("Purnima", "Soma", "Very Auspicious", "Worship, celebration",
     "Full Moon -- complete illumination",
     "Soma", "Muy Auspicioso", "Adoraci\u00f3n, celebraci\u00f3n",
     "Luna Llena -- iluminaci\u00f3n completa"),
    ("Krishna Pratipada", "Agni", "Neutral", "Rest after fullness",
     "First day of waning -- the turn inward begins",
     "Agni", "Neutro", "Descanso tras la plenitud",
     "Primer d\u00eda del menguante -- comienza el giro interior"),
    ("Krishna Dvitiya", "Brahma", "Neutral", "Domestic work",
     "Day of gentle decrease",
     "Brahma", "Neutro", "Trabajo dom\u00e9stico",
     "D\u00eda de suave disminuci\u00f3n"),
    ("Krishna Tritiya", "Gauri", "Auspicious", "Rituals, remembrance",
     "Day of enduring grace",
     "Gauri", "Auspicioso", "Rituales, remembranza",
     "D\u00eda de gracia perdurable"),
    ("Krishna Chaturthi", "Ganesha", "Inauspicious", "Avoid new ventures",
     "Day of hidden obstacles",
     "Ganesha", "Desfavorable", "Evitar nuevos emprendimientos",
     "D\u00eda de obst\u00e1culos ocultos"),
    ("Krishna Panchami", "Nagas", "Neutral", "Study, reflection",
     "Day of inner knowledge",
     "Nagas", "Neutro", "Estudio, reflexi\u00f3n",
     "D\u00eda del conocimiento interior"),
    ("Krishna Shashthi", "Kartikeya", "Neutral", "Healing practices",
     "Day of quiet strength",
     "Kartikeya", "Neutro", "Pr\u00e1cticas de sanaci\u00f3n",
     "D\u00eda de fuerza silenciosa"),
    ("Krishna Saptami", "Surya", "Neutral", "Routine work",
     "Day of fading light",
     "Surya", "Neutro", "Trabajo rutinario",
     "D\u00eda de luz menguante"),
    ("Krishna Ashtami", "Shiva", "Inauspicious", "Fasting, austerity",
     "Krishna Ashtami -- Janmashtami (Krishna's birthday)",
     "Shiva", "Desfavorable", "Ayuno, austeridad",
     "Krishna Ashtami -- Janmashtami (cumplea\u00f1os de Krishna)"),
    ("Krishna Navami", "Durga", "Neutral", "Protective rituals",
     "Day of fierce protection",
     "Durga", "Neutro", "Rituales de protecci\u00f3n",
     "D\u00eda de protecci\u00f3n feroz"),
    ("Krishna Dashami", "Yama", "Neutral", "Justice, settling accounts",
     "Day of reckoning",
     "Yama", "Neutro", "Justicia, saldar cuentas",
     "D\u00eda del ajuste de cuentas"),
    ("Krishna Ekadashi", "Vishnu", "Very Auspicious", "Fasting, devotion",
     "Day of spiritual discipline -- Ekadashi fast",
     "Vishnu", "Muy Auspicioso", "Ayuno, devoci\u00f3n",
     "D\u00eda de disciplina espiritual -- ayuno de Ekadashi"),
    ("Krishna Dvadashi", "Vishnu", "Auspicious", "Charity",
     "Day of release and giving",
     "Vishnu", "Auspicioso", "Caridad",
     "D\u00eda de liberaci\u00f3n y generosidad"),
    ("Krishna Trayodashi", "Kamadeva", "Neutral", "Arts, creativity",
     "Day of subtle beauty",
     "Kamadeva", "Neutro", "Artes, creatividad",
     "D\u00eda de belleza sutil"),
    ("Krishna Chaturdashi", "Shiva", "Inauspicious", "Maha Shivaratri (great night of Shiva)",
     "Night before darkness -- dissolution",
     "Shiva", "Desfavorable", "Maha Shivaratri (gran noche de Shiva)",
     "Noche antes de la oscuridad -- disoluci\u00f3n"),
    ("Amavasya", "Pitris", "Neutral", "Ancestor worship, new beginnings",
     "New Moon -- the still point before rebirth",
     "Pitris", "Neutro", "Adoraci\u00f3n ancestral, nuevos comienzos",
     "Luna Nueva -- el punto de quietud antes del renacimiento"),
]

for i, t in enumerate(TITHIS):
    n = i + 1
    HINDU_EN[f"hindu.tithi.{n}.name"] = t[0]
    HINDU_EN[f"hindu.tithi.{n}.deity"] = t[1]
    HINDU_EN[f"hindu.tithi.{n}.quality"] = t[2]
    HINDU_EN[f"hindu.tithi.{n}.activity"] = t[3]
    HINDU_EN[f"hindu.tithi.{n}.brief"] = t[4]
    # Names stay Sanskrit
    HINDU_ES[f"hindu.tithi.{n}.name"] = t[0]
    HINDU_ES[f"hindu.tithi.{n}.deity"] = t[5]
    HINDU_ES[f"hindu.tithi.{n}.quality"] = t[6]
    HINDU_ES[f"hindu.tithi.{n}.activity"] = t[7]
    HINDU_ES[f"hindu.tithi.{n}.brief"] = t[8]


# ============================================================
# MERGE
# ============================================================

def merge_and_write():
    # Read existing
    with open(EN_PATH, "r", encoding="utf-8") as f:
        en = json.load(f)
    with open(ES_PATH, "r", encoding="utf-8") as f:
        es = json.load(f)

    # Count before
    en_before = len(en)
    es_before = len(es)

    # Merge all systems
    for d in [ICHING_EN, HD_EN, KAB_EN, HINDU_EN]:
        en.update(d)
    for d in [ICHING_ES, HD_ES, KAB_ES, HINDU_ES]:
        es.update(d)

    # Sort keys
    en = dict(sorted(en.items()))
    es = dict(sorted(es.items()))

    # Write back
    with open(EN_PATH, "w", encoding="utf-8") as f:
        json.dump(en, f, indent=2, ensure_ascii=False)
        f.write("\n")
    with open(ES_PATH, "w", encoding="utf-8") as f:
        json.dump(es, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"EN: {en_before} → {len(en)} keys (+{len(en) - en_before})")
    print(f"ES: {es_before} → {len(es)} keys (+{len(es) - es_before})")


if __name__ == "__main__":
    merge_and_write()
