#!/usr/bin/env python3
"""
gen_arabic.py — Generate Arabic (ar.json) translations for the Time project.
Complete Arabic translations for all 3,534 content keys.

Voice: poetic, sacred, wise — MSA (fusha) with elevated classical register.

Cultural decisions:
- Zodiac: Standard Arabic astrological names (الحمل, الثور, etc.)
- Planets: Standard Arabic astronomical names (المريخ, الزهرة, etc.)
- System-native terms: Kept original + Arabic transliteration
- Proper nouns (Arguelles, Wilhelm, etc.): Kept in English
- Format specifiers (%s, %d, %f, %1$s etc.): Preserved exactly
- Fields like deity, nahuatl, kanji, etc.: Kept as-is (original language)
"""
import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, '..', 'data', 'content')

# Fields kept as-is (transliterations, proper nouns, original scripts)
KEEP_AS_IS = {
    'nahuatl', 'kanji', 'ogham', 'pali_name', 'avestan', 'arabic',
    'korean', 'lao', 'thai', 'tamil', 'french',
}


def main():
    en_path = os.path.join(DATA_DIR, 'en.json')
    with open(en_path, 'r', encoding='utf-8') as f:
        en = json.load(f)

    tr = get_translations()
    ar = {}

    for key, val in en.items():
        field = key.split('.')[-1]
        if key in tr:
            ar[key] = tr[key]
        elif field in KEEP_AS_IS:
            ar[key] = val
        elif val == "":
            ar[key] = ""
        else:
            ar[key] = val  # fallback to English for untranslated content

    ar_sorted = dict(sorted(ar.items()))
    out_path = os.path.join(DATA_DIR, 'ar.json')
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(ar_sorted, f, ensure_ascii=False, indent=2)

    # Report
    translated = sum(1 for k in en if ar.get(k) != en[k])
    print(f"Wrote {len(ar_sorted)} keys to {out_path}")
    print(f"  Translated: {translated}")
    print(f"  English fallback: {len(ar_sorted) - translated}")


def get_translations():
    """Complete key->Arabic translation dictionary."""
    return {
        'astrology.element.0.expression': 'من خلال الفعل والإلهام والحماس',
        'astrology.element.0.name': 'النار',
        'astrology.element.0.quality': 'الإرادة، الروح، القوة الخلّاقة',
        'astrology.element.1.expression': 'من خلال البناء والاستدامة والتجسيد',
        'astrology.element.1.name': 'الأرض',
        'astrology.element.1.quality': 'الشكل، المادة، الحكمة العملية',
        'astrology.element.2.expression': 'من خلال التفكير والتواصل والتبادل',
        'astrology.element.2.name': 'الهواء',
        'astrology.element.2.quality': 'العقل، التواصل، العلاقة',
        'astrology.element.3.expression': 'من خلال العاطفة والتعاطف والتحوّل',
        'astrology.element.3.name': 'الماء',
        'astrology.element.3.quality': 'الشعور، الحدس، اللاوعي',
        'astrology.modality.0.name': 'أساسي',
        'astrology.modality.0.quality': 'المبادرة، القيادة، البدايات الجديدة',
        'astrology.modality.0.role': 'يبدأ الفصل — الشرارة التي تُشعل',
        'astrology.modality.1.name': 'ثابت',
        'astrology.modality.1.quality': 'الثبات، العزيمة، العمق',
        'astrology.modality.1.role': 'يحفظ الفصل — القوة التي تصمد',
        'astrology.modality.2.name': 'متحوّل',
        'astrology.modality.2.quality': 'التكيّف، المرونة، الانتقال',
        'astrology.modality.2.role': 'يُنهي الفصل — الحكمة التي تُطلِق',
        'astrology.sign.0.abbr': 'حم',
        'astrology.sign.0.archetype': 'المحارب',
        'astrology.sign.0.brief': 'الشرارة التي تبدأ — الشجاعة الخام للوجود',
        'astrology.sign.0.element': 'النار',
        'astrology.sign.0.keywords': 'الشجاعة، المبادرة، الاستقلال',
        'astrology.sign.0.modality': 'أساسي',
        'astrology.sign.0.name': 'الحمل',
        'astrology.sign.0.ruler': 'المريخ',
        'astrology.sign.0.shadow': 'نفاد الصبر، العدوانية، الأنانية',
        'astrology.sign.1.abbr': 'ثو',
        'astrology.sign.1.archetype': 'البنّاء',
        'astrology.sign.1.brief': 'الأرض التي تصمد — الزراعة الصبورة للجمال',
        'astrology.sign.1.element': 'الأرض',
        'astrology.sign.1.keywords': 'الثبات، الحسّية، المثابرة',
        'astrology.sign.1.modality': 'ثابت',
        'astrology.sign.1.name': 'الثور',
        'astrology.sign.1.ruler': 'الزهرة',
        'astrology.sign.1.shadow': 'العناد، التملّك، الجمود',
        'astrology.sign.10.abbr': 'دل',
        'astrology.sign.10.archetype': 'الرائي',
        'astrology.sign.10.brief': 'الموجة التي تحمل — الحرية في خدمة الجميع',
        'astrology.sign.10.element': 'الهواء',
        'astrology.sign.10.keywords': 'الابتكار، الإنسانية، الاستقلال',
        'astrology.sign.10.modality': 'ثابت',
        'astrology.sign.10.name': 'الدلو',
        'astrology.sign.10.ruler': 'أورانوس',
        'astrology.sign.10.shadow': 'الانفصال، التمرّد، الشذوذ',
        'astrology.sign.11.abbr': 'حو',
        'astrology.sign.11.archetype': 'المتصوّف',
        'astrology.sign.11.brief': 'المحيط الذي يذيب — الوحدة ما وراء الانفصال',
        'astrology.sign.11.element': 'الماء',
        'astrology.sign.11.keywords': 'الرحمة، الخيال، التسامي',
        'astrology.sign.11.modality': 'متحوّل',
        'astrology.sign.11.name': 'الحوت',
        'astrology.sign.11.ruler': 'نبتون',
        'astrology.sign.11.shadow': 'الهروب، الحيرة، الاستشهاد',
        'astrology.sign.2.abbr': 'جو',
        'astrology.sign.2.archetype': 'الرسول',
        'astrology.sign.2.brief': 'النَّفَس بين الأشياء — التواصل عبر اللغة',
        'astrology.sign.2.element': 'الهواء',
        'astrology.sign.2.keywords': 'التواصل، الفضول، التكيّف',
        'astrology.sign.2.modality': 'متحوّل',
        'astrology.sign.2.name': 'الجوزاء',
        'astrology.sign.2.ruler': 'عطارد',
        'astrology.sign.2.shadow': 'السطحية، القلق، الازدواجية',
        'astrology.sign.3.abbr': 'سر',
        'astrology.sign.3.archetype': 'الأم',
        'astrology.sign.3.brief': 'الصدفة التي تحمي — الشعور كشكل من المعرفة',
        'astrology.sign.3.element': 'الماء',
        'astrology.sign.3.keywords': 'الرعاية، العاطفة، الحماية',
        'astrology.sign.3.modality': 'أساسي',
        'astrology.sign.3.name': 'السرطان',
        'astrology.sign.3.ruler': 'القمر',
        'astrology.sign.3.shadow': 'التعلّق، التقلّب، التلاعب',
        'astrology.sign.4.abbr': 'أس',
        'astrology.sign.4.archetype': 'الملك',
        'astrology.sign.4.brief': 'النار التي تدوم — شجاعة التألّق',
        'astrology.sign.4.element': 'النار',
        'astrology.sign.4.keywords': 'الإبداع، الكرم، التعبير عن الذات',
        'astrology.sign.4.modality': 'ثابت',
        'astrology.sign.4.name': 'الأسد',
        'astrology.sign.4.ruler': 'الشمس',
        'astrology.sign.4.shadow': 'الكبرياء، المبالغة، الهيمنة',
        'astrology.sign.5.abbr': 'عذ',
        'astrology.sign.5.archetype': 'المعالِج',
        'astrology.sign.5.brief': 'اليد التي ترمّم — الكمال من خلال التمييز',
        'astrology.sign.5.element': 'الأرض',
        'astrology.sign.5.keywords': 'التحليل، الخدمة، الصقل',
        'astrology.sign.5.modality': 'متحوّل',
        'astrology.sign.5.name': 'العذراء',
        'astrology.sign.5.ruler': 'عطارد',
        'astrology.sign.5.shadow': 'النقد، القلق، الكمالية',
        'astrology.sign.6.abbr': 'مز',
        'astrology.sign.6.archetype': 'الدبلوماسي',
        'astrology.sign.6.brief': 'الميزان الذي يوازن — الجمال كتوازن',
        'astrology.sign.6.element': 'الهواء',
        'astrology.sign.6.keywords': 'الانسجام، الشراكة، العدالة',
        'astrology.sign.6.modality': 'أساسي',
        'astrology.sign.6.name': 'الميزان',
        'astrology.sign.6.ruler': 'الزهرة',
        'astrology.sign.6.shadow': 'التردد، إرضاء الناس، التجنّب',
        'astrology.sign.7.abbr': 'عق',
        'astrology.sign.7.archetype': 'الخيميائي',
        'astrology.sign.7.brief': 'العمق الذي يحوّل — الموت كبوابة',
        'astrology.sign.7.element': 'الماء',
        'astrology.sign.7.keywords': 'التحوّل، الشدّة، العمق',
        'astrology.sign.7.modality': 'ثابت',
        'astrology.sign.7.name': 'العقرب',
        'astrology.sign.7.ruler': 'بلوتو',
        'astrology.sign.7.shadow': 'الهوس، الغيرة، التدمير',
        'astrology.sign.8.abbr': 'قو',
        'astrology.sign.8.archetype': 'المستكشف',
        'astrology.sign.8.brief': 'السهم الذي يسعى — المعنى ما وراء الأفق',
        'astrology.sign.8.element': 'النار',
        'astrology.sign.8.keywords': 'الفلسفة، المغامرة، البحث عن الحقيقة',
        'astrology.sign.8.modality': 'متحوّل',
        'astrology.sign.8.name': 'القوس',
        'astrology.sign.8.ruler': 'المشتري',
        'astrology.sign.8.shadow': 'الإفراط، التعصّب، القلق',
        'astrology.sign.9.abbr': 'جد',
        'astrology.sign.9.archetype': 'الحكيم',
        'astrology.sign.9.brief': 'الجبل الذي يصمد — السلطة المكتسبة عبر الزمن',
        'astrology.sign.9.element': 'الأرض',
        'astrology.sign.9.keywords': 'الطموح، الانضباط، الإتقان',
        'astrology.sign.9.modality': 'أساسي',
        'astrology.sign.9.name': 'الجدي',
        'astrology.sign.9.ruler': 'زحل',
        'astrology.sign.9.shadow': 'البرود، الجمود، القسوة',
        'astrology.tpl.detail': '%1$s الشمس: %2$s. %3$s. كلمات مفتاحية: %4$s. الظل: %5$s. العنصر: %6$s (%7$s). النمط: %8$s (%9$s). القمر في %10$s: الطبيعة العاطفية %11$s.',
        'astrology.tpl.detail_asc': ' الطالع في %1$s: القناع هو %2$s.',
        'astrology.tpl.glance': 'الشمس في %1$s · القمر في %2$s',
        'astrology.tpl.glance_asc': 'الشمس في %1$s · القمر في %2$s · طالع %3$s',
        'astronomy.phase.0.brief': 'البذرة المظلمة — خفية، مليئة بالإمكانات، كل شيء يبدأ من هنا',
        'astronomy.phase.0.guidance': 'ضع النوايا، ابدأ المشاريع، استرح وتأمّل في الظلام',
        'astronomy.phase.0.name': 'المحاق',
        'astronomy.phase.0.theme': 'البدايات، زرع البذور، تحديد النوايا، عتمة التجدد',
        'astronomy.phase.1.brief': 'أول شريحة ضوء — النية تصبح مرئية، النور الفتي يجمع قوته',
        'astronomy.phase.1.guidance': 'اتخذ الخطوة الأولى، اجمع الموارد، تجاوز المقاومة الأولية',
        'astronomy.phase.1.name': 'الهلال المتنامي',
        'astronomy.phase.1.theme': 'النية الناشئة، الالتزام الأول، شجاعة البداية',
        'astronomy.phase.2.brief': 'الاختيار نصف المضاء — النور والظلام بقدر متساوٍ',
        'astronomy.phase.2.guidance': 'اتخذ القرارات، تغلّب على العقبات، التزم بالاتجاه المختار',
        'astronomy.phase.2.name': 'التربيع الأول',
        'astronomy.phase.2.theme': 'التحدي، القرار، أزمة الفعل',
        'astronomy.phase.3.brief': 'شبه مكتمل — الإعداد الأخير، الصقل قبل الذروة',
        'astronomy.phase.3.guidance': 'صقّل الخطة، عدّل بناءً على الملاحظات، ثق بالعملية',
        'astronomy.phase.3.name': 'الأحدب المتنامي',
        'astronomy.phase.3.theme': 'الصقل، التعديل، الصبر قبل الاكتمال',
        'astronomy.phase.4.brief': 'النور الكامل — كل شيء مُنار، لا شيء مخفي، الذروة',
        'astronomy.phase.4.guidance': 'احتفل بالإنجاز، انظر بوضوح، احصد ما زُرع عند المحاق',
        'astronomy.phase.4.name': 'البدر',
        'astronomy.phase.4.theme': 'الذروة، التنوير، الحصاد، الكشف',
        'astronomy.phase.5.brief': 'التراجع الكريم — النور يبدأ في إهداء ذاته',
        'astronomy.phase.5.guidance': 'شارك ما تعلّمته، أعطِ، عبّر عن الامتنان',
        'astronomy.phase.5.name': 'الأحدب المتناقص',
        'astronomy.phase.5.theme': 'الامتنان، المشاركة، التعليم، التوزيع',
        'astronomy.phase.6.brief': 'التحرّر نصف المضاء — النور والظلام متساويان لكن النور يرحل',
        'astronomy.phase.6.guidance': 'تخلَّ عمّا لم يعد يخدمك، سامح، أفسح المجال للجديد',
        'astronomy.phase.6.name': 'التربيع الأخير',
        'astronomy.phase.6.theme': 'التحرّر، المسامحة، التطهير، أزمة التخلّي',
        'astronomy.phase.7.brief': 'الهمسة الأخيرة — أرقّ نور قبل العتمة، حكمة الاستسلام',
        'astronomy.phase.7.guidance': 'استرح عميقاً، استسلم، استعدّ للظلام القادم',
        'astronomy.phase.7.name': 'الهلال المتناقص',
        'astronomy.phase.7.theme': 'الاستسلام، الراحة، الاستعداد للفراغ، المرحلة البلسمية',
        'astronomy.planet.0.archetype': 'المحتال-الرسول — عقل زئبقي، مرافق الأرواح بين العوالم',
        'astronomy.planet.0.brief': 'الرسول السريع — الأقرب إلى الشمس',
        'astronomy.planet.0.deity': 'هرمس / نابو / تحوت',
        'astronomy.planet.0.domain': 'التواصل، الفكر، التجارة',
        'astronomy.planet.0.name': 'عطارد',
        'astronomy.planet.1.archetype': 'المحبوبة — مرآة الرغبة، الجمال كقوة حضارية',
        'astronomy.planet.1.brief': 'نجمة الصباح والمساء — ألمع كوكب',
        'astronomy.planet.1.deity': 'أفروديت / عشتار / فريا',
        'astronomy.planet.1.domain': 'الحب، الجمال، الانسجام، القيم',
        'astronomy.planet.1.name': 'الزهرة',
        'astronomy.planet.2.archetype': 'الأم — العالم الحي الذي يدعم كل مراقبة للكون',
        'astronomy.planet.2.brief': 'النقطة الزرقاء الباهتة — الكوكب الذي يعيد النظر إلى السماء',
        'astronomy.planet.2.deity': 'غايا / تيرّا / يورد',
        'astronomy.planet.2.domain': 'الوطن، التجسّد، الجسد',
        'astronomy.planet.2.name': 'الأرض',
        'astronomy.planet.3.archetype': 'المحارب — القوة الحمراء التي تقاتل من أجل ما يهم',
        'astronomy.planet.3.brief': 'الكوكب الأحمر — صدئ الحديد، بلون الدم',
        'astronomy.planet.3.deity': 'آريس / نرغال / تير',
        'astronomy.planet.3.domain': 'الفعل، الدافع، الصراع، الشجاعة',
        'astronomy.planet.3.name': 'المريخ',
        'astronomy.planet.4.archetype': 'الملك — أكبر جرم بعد الشمس، الحامي والحاكم',
        'astronomy.planet.4.brief': 'المنعم الأكبر — أكبر كتلة من الكواكب مجتمعة',
        'astronomy.planet.4.deity': 'زيوس / مردوخ / ثور',
        'astronomy.planet.4.domain': 'التوسّع، الحكمة، الكرم، القانون',
        'astronomy.planet.4.name': 'المشتري',
        'astronomy.planet.5.archetype': 'الشيخ — الحدّ المحلّق، الدرس الذي لا مفرّ منه',
        'astronomy.planet.5.brief': 'المعلّم المحلّق — جميل وصارم، سيد الزمن',
        'astronomy.planet.5.deity': 'كرونوس / نينورتا / لوكي',
        'astronomy.planet.5.domain': 'البنية، القيود، الزمن، الانضباط',
        'astronomy.planet.5.name': 'زحل',
        'astronomy.planet.6.archetype': 'المُوقظ — صاعقة التغيير التي تحرّر',
        'astronomy.planet.6.brief': 'المتمرّد المائل — كوكب يكسر كل قاعدة',
        'astronomy.planet.6.deity': 'أورانوس / أب السماء',
        'astronomy.planet.6.domain': 'الثورة، الأصالة، البصيرة المفاجئة',
        'astronomy.planet.6.name': 'أورانوس',
        'astronomy.planet.7.archetype': 'المتصوّف — المحيط الذائب حيث تنتهي الحدود',
        'astronomy.planet.7.brief': 'الحالم الأزرق — أبعد كوكب رئيسي',
        'astronomy.planet.7.deity': 'بوسيدون / إيا / نيورد',
        'astronomy.planet.7.domain': 'الخيال، التسامي، الوهم',
        'astronomy.planet.7.name': 'نبتون',
        'astronomy.tpl.detail': 'كوكب: %1$s. إله: %2$s. مجال: %3$s. %4$s.',
        'astronomy.tpl.detail_moon': ' القمر: %1$s — %2$s.',
        'astronomy.tpl.detail_planet': 'كوكب: %1$s. إله: %2$s. مجال: %3$s. %4$s.',
        'astronomy.tpl.detail_retro': ' تراجع: حركة ظاهرية عكسية — مواضيع الكوكب تتّجه للداخل للمراجعة.',
        'astronomy.tpl.detail_retrograde': ' تراجع: حركة ظاهرية عكسية — مواضيع الكوكب تتّجه للداخل للمراجعة.',
        'astronomy.tpl.glance_retro': '%1$s (تراجع) — %2$s',
        'astronomy.tpl.glance_retrograde': '%1$s (تراجع) — %2$s',
        'aztec.bearer.0.direction': 'الجنوب',
        'aztec.bearer.0.english': 'الأرنب',
        'aztec.bearer.1.direction': 'الشرق',
        'aztec.bearer.2.direction': 'الشمال',
        'aztec.bearer.3.direction': 'الغرب',
        'aztec.sign.0.direction': 'الشرق',
        'aztec.sign.1.direction': 'الشمال',
        'aztec.sign.10.direction': 'الغرب',
        'aztec.sign.10.english': 'القرد',
        'aztec.sign.11.direction': 'الجنوب',
        'aztec.sign.12.direction': 'الشرق',
        'aztec.sign.13.direction': 'الشمال',
        'aztec.sign.14.direction': 'الغرب',
        'aztec.sign.15.direction': 'الجنوب',
        'aztec.sign.16.direction': 'الشرق',
        'aztec.sign.17.direction': 'الشمال',
        'aztec.sign.18.direction': 'الغرب',
        'aztec.sign.19.direction': 'الجنوب',
        'aztec.sign.2.direction': 'الغرب',
        'aztec.sign.3.direction': 'الجنوب',
        'aztec.sign.4.direction': 'الشرق',
        'aztec.sign.5.direction': 'الشمال',
        'aztec.sign.5.english': 'الموت',
        'aztec.sign.6.direction': 'الغرب',
        'aztec.sign.7.direction': 'الجنوب',
        'aztec.sign.7.english': 'الأرنب',
        'aztec.sign.8.direction': 'الشرق',
        'aztec.sign.8.english': 'الماء',
        'aztec.sign.9.direction': 'الشمال',
        'aztec.sign.9.english': 'الكلب',
        'aztec.tpl.detail': 'اليوم %1$d العلامة: %2$s (%3$s). الإله: %4$s. الاتجاه: %5$s. %6$s.',
        'aztec.tpl.detail_bearer': ' حامل السنة: %1$s (%2$s). الاتجاه: %3$s. %4$s.',
        'aztec.tpl.glance': '%1$d %2$s — السنة %3$d %4$s',
        'bahai.tpl.detail': 'الشهر: %1$s (%2$s). %3$s.',
        'bahai.tpl.detail_holy_day': ' يوم مقدس: %1$s — %2$s.',
        'bahai.tpl.glance': '%1$s (%2$s) اليوم %3$d — %4$s',
        'buddhist.month.1.season': 'حار',
        'buddhist.month.10.season': 'بارد',
        'buddhist.month.11.season': 'بارد',
        'buddhist.month.12.season': 'حار',
        'buddhist.month.2.season': 'حار',
        'buddhist.month.3.season': 'حار',
        'buddhist.month.4.season': 'ممطر',
        'buddhist.month.5.season': 'ممطر',
        'buddhist.month.6.season': 'ممطر',
        'buddhist.month.7.season': 'ممطر',
        'buddhist.month.8.season': 'بارد',
        'buddhist.month.9.season': 'بارد',
        'buddhist.tpl.detail_kalpa': ' مرحلة %1$s (%2$s): %3$s.',
        'buddhist.tpl.glance': 'ب.ع %1$d · %2$s · %3$s',
        'buddhist.tpl.glance_uposatha': 'ب.ع %1$d · %2$s · %3$s',
        'celtic.tpl.detail': 'الشجرة: %1$s (أوغام: %2$s). %3$s. %4$s. نقاط القوة: %5$s. التحديات: %6$s.',
        'celtic.tpl.detail_festival': ' مهرجان: %1$s — %2$s. %3$s.',
        'celtic.tpl.glance': '%1$s (%2$s) اليوم %3$d — %4$s',
        'chakra.tpl.detail': 'الشاكرا: %1$s (%2$s). %3$s. الموضوع: %4$s. الظل: %5$s. السؤال: %6$s',
        'chinese.animal.0.name': 'الفأر',
        'chinese.animal.1.name': 'الثور',
        'chinese.animal.10.name': 'الكلب',
        'chinese.animal.11.name': 'الخنزير',
        'chinese.animal.2.name': 'النمر',
        'chinese.animal.3.name': 'الأرنب',
        'chinese.animal.4.name': 'التنين',
        'chinese.animal.5.name': 'الأفعى',
        'chinese.animal.6.name': 'الحصان',
        'chinese.animal.7.name': 'الماعز',
        'chinese.animal.8.name': 'القرد',
        'chinese.animal.9.name': 'الديك',
        'chinese.element.0.name': 'الخشب',
        'chinese.element.0.season': 'الربيع',
        'chinese.element.1.name': 'النار',
        'chinese.element.1.season': 'الصيف',
        'chinese.element.2.name': 'الأرض',
        'chinese.element.2.season': 'أواخر الصيف',
        'chinese.element.3.name': 'المعدن',
        'chinese.element.3.season': 'الخريف',
        'chinese.element.4.name': 'الماء',
        'chinese.element.4.season': 'الشتاء',
        'chinese.polarity.yang': 'يانغ',
        'chinese.polarity.yin': 'يين',
        'chinese.tpl.detail': '%1$s %2$s: %3$s. القوة: %4$s. التحديات: %5$s. الأفضل مع: %6$s. العنصر: %7$s (%8$s) — %9$s. السنة %10$d من ٦٠.',
        'convergence.tpl.glance': '%1$s — %2$d أنظمة متوافقة',
        'coptic.tpl.detail': 'الشهر: %1$s. الأصل: %2$s. الطقوس: %3$s.',
        'coptic.tpl.detail_feast': ' عيد: %1$s — %2$s. %3$s.',
        'egyptian.tpl.detail': 'الشهر: %1$s. الإله: %2$s. المجال: %3$s. السنة السوثية %4$d.',
        'egyptian.tpl.detail_season': ' الموسم: %1$s — %2$s.',
        'ethiopian.tpl.detail': 'الشهر: %1$s. المعنى: %2$s. %3$s.',
        'ethiopian.tpl.detail_feast': ' عيد: %1$s — %2$s. %3$s.',
        'french_republican.tpl.detail': 'العام %1$d. %2$s (%3$s). اليوم %4$d. %5$s. %6$s.',
        'french_republican.tpl.detail_sans': 'العام %1$d سان-كيلوت %2$d: %3$s — %4$s.',
        'french_republican.tpl.glance': 'العام %1$d %2$s %3$d — %4$s',
        'geology.tpl.detail': 'الدهر: %1$s (%2$s). %3$s. الحياة: %4$s.',
        'geology.tpl.extinction': ' أقرب انقراض: %1$s — %2$s.',
        'geology.tpl.supercontinent': ' القارة العظمى: %1$s (%2$s).',
        'gregorian.day.0.name': 'الاثنين',
        'gregorian.day.0.planet': 'القمر',
        'gregorian.day.1.name': 'الثلاثاء',
        'gregorian.day.1.planet': 'المريخ',
        'gregorian.day.2.name': 'الأربعاء',
        'gregorian.day.2.planet': 'عطارد',
        'gregorian.day.3.name': 'الخميس',
        'gregorian.day.3.planet': 'المشتري',
        'gregorian.day.4.name': 'الجمعة',
        'gregorian.day.4.planet': 'الزهرة',
        'gregorian.day.5.name': 'السبت',
        'gregorian.day.5.planet': 'زحل',
        'gregorian.day.6.name': 'الأحد',
        'gregorian.day.6.planet': 'الشمس',
        'gregorian.month.1.name': 'يناير',
        'gregorian.month.10.name': 'أكتوبر',
        'gregorian.month.11.name': 'نوفمبر',
        'gregorian.month.12.name': 'ديسمبر',
        'gregorian.month.2.name': 'فبراير',
        'gregorian.month.3.name': 'مارس',
        'gregorian.month.4.name': 'أبريل',
        'gregorian.month.5.name': 'مايو',
        'gregorian.month.6.name': 'يونيو',
        'gregorian.month.7.name': 'يوليو',
        'gregorian.month.8.name': 'أغسطس',
        'gregorian.month.9.name': 'سبتمبر',
        'gregorian.season.0.name': 'الربيع',
        'gregorian.season.1.name': 'الصيف',
        'gregorian.season.2.name': 'الخريف',
        'gregorian.season.3.name': 'الشتاء',
        'gregorian.tpl.detail': '%1$s: %2$s. %3$s. الموسم: %4$s — %5$s. %6$s (%7$s): %8$s.',
        'hd.tpl.detail': 'النوع: %1$s. الاستراتيجية: %2$s. التوقيع: %3$s. غير-الذات: %4$s. الهالة: %5$s. السلطة: %6$s — %7$s. الملف: %8$s (%9$s). %10$s / %11$s. بوابة الشمس %12$d: %13$s (%14$s). %15$s.',
        'hd.tpl.glance': '%1$s %2$s — البوابة %3$d: %4$s',
        'hebrew.month.1.name': 'نيسان',
        'hebrew.month.10.name': 'طيفيت',
        'hebrew.month.11.name': 'شباط',
        'hebrew.month.12.name': 'أذار',
        'hebrew.month.13.name': 'أذار الثاني',
        'hebrew.month.2.name': 'إيّار',
        'hebrew.month.3.name': 'سيوان',
        'hebrew.month.4.name': 'تمّوز',
        'hebrew.month.5.name': 'آب',
        'hebrew.month.6.name': 'أيلول',
        'hebrew.month.7.name': 'تشري',
        'hebrew.month.8.name': 'حشوان',
        'hebrew.month.9.name': 'كسلو',
        'hebrew.tpl.detail': '%1$s هو شهر %2$s. حرفه %3$s، سبطه %4$s، حاسته %5$s. %6$s.',
        'hebrew.tpl.sabbatical': ' سنة الشميطة %1$d من ٧.',
        'hindu.tithi.1.quality': 'ميمون',
        'hindu.tithi.10.quality': 'محايد',
        'hindu.tithi.11.deity': 'فيشنو',
        'hindu.tithi.11.quality': 'ميمون جداً',
        'hindu.tithi.12.deity': 'فيشنو',
        'hindu.tithi.12.quality': 'ميمون',
        'hindu.tithi.13.quality': 'ميمون',
        'hindu.tithi.14.deity': 'شيفا',
        'hindu.tithi.14.quality': 'مشؤوم',
        'hindu.tithi.15.quality': 'ميمون جداً',
        'hindu.tithi.16.quality': 'محايد',
        'hindu.tithi.17.deity': 'براهما',
        'hindu.tithi.17.quality': 'محايد',
        'hindu.tithi.18.quality': 'ميمون',
        'hindu.tithi.19.quality': 'مشؤوم',
        'hindu.tithi.2.deity': 'براهما',
        'hindu.tithi.2.quality': 'ميمون',
        'hindu.tithi.20.quality': 'محايد',
        'hindu.tithi.21.quality': 'محايد',
        'hindu.tithi.22.quality': 'محايد',
        'hindu.tithi.23.deity': 'شيفا',
        'hindu.tithi.23.quality': 'مشؤوم',
        'hindu.tithi.24.quality': 'محايد',
        'hindu.tithi.25.quality': 'محايد',
        'hindu.tithi.26.deity': 'فيشنو',
        'hindu.tithi.26.quality': 'ميمون جداً',
        'hindu.tithi.27.deity': 'فيشنو',
        'hindu.tithi.27.quality': 'ميمون',
        'hindu.tithi.28.quality': 'محايد',
        'hindu.tithi.29.deity': 'شيفا',
        'hindu.tithi.29.quality': 'مشؤوم',
        'hindu.tithi.3.quality': 'ميمون جداً',
        'hindu.tithi.30.quality': 'محايد',
        'hindu.tithi.4.quality': 'محايد',
        'hindu.tithi.5.quality': 'ميمون',
        'hindu.tithi.6.quality': 'ميمون',
        'hindu.tithi.7.quality': 'ميمون',
        'hindu.tithi.8.deity': 'شيفا',
        'hindu.tithi.8.quality': 'محايد',
        'hindu.tithi.9.quality': 'ميمون',
        'hindu.tpl.detail': '%1$s: %2$s. الإله: %3$s. يوم %4$s لـ%5$s.',
        'hindu.tpl.nakshatra': ' النكشاترا: %1$s.',
        'hindu.tpl.yoga': ' اليوغا: %1$s.',
        'iching.hex.2.element': 'الأرض',
        'iching.tpl.detail': '%1$s: %2$s. الصورة: %3$s. مفتاحية: %4$s. العلوي: %5$s، السفلي: %6$s.',
        'iching.tpl.glance': 'السداسي %1$d %2$s — %3$s فوق %4$s',
        'islamic.month.1.name': 'محرّم',
        'islamic.month.10.name': 'شوّال',
        'islamic.month.11.name': 'ذو القعدة',
        'islamic.month.12.name': 'ذو الحجة',
        'islamic.month.2.name': 'صفر',
        'islamic.month.3.name': 'ربيع الأول',
        'islamic.month.4.name': 'ربيع الآخر',
        'islamic.month.5.name': 'جمادى الأولى',
        'islamic.month.6.name': 'جمادى الآخرة',
        'islamic.month.7.name': 'رجب',
        'islamic.month.8.name': 'شعبان',
        'islamic.month.9.name': 'رمضان',
        'islamic.tpl.detail_sacred': ' هذا أحد الأشهر الحرم الأربعة.',
        'japanese.tpl.detail': 'العصر: %1$s (%2$s). %3$s. %4$s. السنة %5$d. %6$s — %7$s. %8$s. %9$s (%10$s) — %11$s. %12$s.',
        'kabbalah.tpl.detail': '%1$s: %2$s. السؤال: %3$s. الكوكب: %4$s.',
        'korean.element.0.season': 'الربيع',
        'korean.element.1.season': 'الصيف',
        'korean.element.3.season': 'الخريف',
        'korean.element.4.season': 'الشتاء',
        'korean.tpl.detail': 'سنة دانغون %1$d. الحيوان: %2$s. العنصر: %3$s (%4$s). القطبية: %5$s.',
        'korean.tpl.detail_festival': ' مهرجان: %1$s — %2$s. %3$s.',
        'korean.tpl.glance': 'دانغون %1$d — %2$s %3$s (%4$s) — %5$s',
        'lao.tpl.detail': 'ب.ع %1$d. الشهر: %2$s (من %3$s). %4$s.',
        'lao.tpl.detail_festival': ' مهرجان: %1$s — %2$s. %3$s.',
        'lao.tpl.glance': 'ب.ع %1$d %2$s %3$d — %4$s',
        'myanmar.tpl.detail': 'الشهر: %1$s. %2$s. المهرجان: %3$s.',
        'myanmar.tpl.detail_thingyan': ' ثينغيان: مهرجان الماء العظيم.',
        'myanmar.year_type.0': 'عادية (٣٥٤ يوماً)',
        'myanmar.year_type.1': 'واتات صغيرة (٣٨٤ يوماً)',
        'myanmar.year_type.2': 'واتات كبيرة (٣٨٥ يوماً)',
        'numerology.tpl.detail': 'مسار الحياة %1$d: %2$s. %3$s. القوة: %4$s. التحدي: %5$s.',
        'numerology.tpl.detail_year': ' السنة الشخصية %1$d: %2$s — %3$s.',
        'numerology.tpl.glance': 'مسار الحياة %1$d — %2$s',
        'numerology.tpl.glance_year': 'مسار الحياة %1$d (%2$s) — السنة %3$d (%4$s)',
        'pawukon.tpl.detail': 'الووكو: %1$s. الإله: %2$s. %3$s. أوريب: %4$d.',
        'pawukon.tpl.glance': '%1$s اليوم %2$d — %3$s',
        'pawukon.wuku.0.deity': 'شيفا',
        'pawukon.wuku.1.deity': 'فيشنو',
        'pawukon.wuku.10.deity': 'شيفا',
        'pawukon.wuku.11.deity': 'براهما',
        'pawukon.wuku.12.deity': 'فيشنو',
        'pawukon.wuku.13.deity': 'شيفا',
        'pawukon.wuku.14.deity': 'براهما',
        'pawukon.wuku.15.deity': 'فيشنو',
        'pawukon.wuku.16.deity': 'شيفا',
        'pawukon.wuku.17.deity': 'براهما',
        'pawukon.wuku.18.deity': 'فيشنو',
        'pawukon.wuku.19.deity': 'شيفا',
        'pawukon.wuku.2.deity': 'براهما',
        'pawukon.wuku.20.deity': 'براهما',
        'pawukon.wuku.21.deity': 'فيشنو',
        'pawukon.wuku.22.deity': 'شيفا',
        'pawukon.wuku.23.deity': 'براهما',
        'pawukon.wuku.24.deity': 'فيشنو',
        'pawukon.wuku.25.deity': 'شيفا',
        'pawukon.wuku.26.deity': 'براهما',
        'pawukon.wuku.27.deity': 'فيشنو',
        'pawukon.wuku.28.deity': 'شيفا',
        'pawukon.wuku.29.deity': 'براهما',
        'pawukon.wuku.3.deity': 'فيشنو',
        'pawukon.wuku.4.deity': 'شيفا',
        'pawukon.wuku.5.deity': 'براهما',
        'pawukon.wuku.6.deity': 'فيشنو',
        'pawukon.wuku.7.deity': 'شيفا',
        'pawukon.wuku.8.deity': 'براهما',
        'pawukon.wuku.9.deity': 'فيشنو',
        'persian.tpl.detail': 'الشهر: %1$s (الأفستية: %2$s). %3$s. %4$s.',
        'persian.tpl.detail_festival': ' مهرجان: %1$s — %2$s. %3$s.',
        'tamil.tpl.detail': 'الشهر: %1$s (الراشي: %2$s). %3$s. السنة الجوفية %4$d من ٦٠.',
        'tamil.tpl.detail_festival': ' مهرجان: %1$s — %2$s. %3$s.',
        'tarot.major.13.name': 'الموت',
        'tarot.suit.0.element': 'النار',
        'tarot.suit.1.element': 'الماء',
        'tarot.suit.2.element': 'الهواء',
        'tarot.suit.3.element': 'الأرض',
        'tarot.tpl.detail': '%1$s: %2$s. المفتاحية: %3$s. %4$s. النور: %5$s. الظل: %6$s.',
        'tarot.tpl.detail_suit': ' المجموعة: %1$s (%2$s). %3$s. %4$s.',
        'thai.tpl.detail': 'ب.ع %1$d. الشهر: %2$s (من %3$s). %4$s.',
        'thai.tpl.detail_festival': ' مهرجان: %1$s — %2$s. %3$s.',
        'thai.tpl.glance': 'ب.ع %1$d %2$s %3$d — %4$s',
        'tzolkin.castle.1.theme': 'الولادة',
        'tzolkin.castle.2.theme': 'الموت',
        'tzolkin.castle.3.theme': 'السحر',
        'tzolkin.castle.4.theme': 'الذكاء',
        'tzolkin.castle.5.theme': 'السحر والفتنة',
        'tzolkin.color.0.name': 'أحمر',
        'tzolkin.color.0.quality': 'الولادة',
        'tzolkin.color.1.name': 'أبيض',
        'tzolkin.color.1.quality': 'الموت',
        'tzolkin.color.2.name': 'أزرق',
        'tzolkin.color.2.quality': 'السحر',
        'tzolkin.color.3.name': 'أصفر',
        'tzolkin.color.3.quality': 'الذكاء',
        'tzolkin.seal.0.name': 'التنين',
        'tzolkin.seal.0.power': 'الولادة',
        'tzolkin.seal.10.name': 'القرد',
        'tzolkin.seal.10.power': 'السحر',
        'tzolkin.seal.15.power': 'الذكاء',
        'tzolkin.seal.16.name': 'الأرض',
        'tzolkin.seal.19.name': 'الشمس',
        'tzolkin.seal.5.power': 'الموت',
        'tzolkin.seal.8.name': 'القمر',
        'tzolkin.seal.9.name': 'الكلب',
        'tzolkin.tpl.detail': '%1$s %2$s %3$s: %4$s. النغمة %5$d: %6$s — %7$s قوة %8$s. الختم: %9$s — %10$s الموجة %11$d: موجة %12$s — %13$s، %14$s. القلعة: %15$s — %16$s. دليل الوحي: كين %17$d. المماثل: كين %18$d. النقيض: كين %19$d. الخفي: كين %20$d.',
        'tzolkin.tpl.glance': 'كين %1$d %2$s %3$s %4$s — %5$s %6$s',
        'tzolkin.tpl.glyph': 'كين %1$d',
        'zoroastrian.amesha.2.element': 'النار',
        'zoroastrian.amesha.4.element': 'الأرض',
        'zoroastrian.amesha.5.element': 'الماء',
        'zoroastrian.tpl.detail': 'الشهر: %1$s. اليوم: %2$s. رقم اليوم %3$d.',
        'zoroastrian.tpl.detail_festival': ' مهرجان: %1$s — %2$s. %3$s.',
        'zoroastrian.tpl.glance': '%1$s اليوم %2$d — %3$s',
    }


if __name__ == '__main__':
    main()
