#!/usr/bin/env python3
"""gen_msdf_header.py -- Convert MSDF atlas + metrics to C header.

Usage:
  1. Generate atlas with msdf-atlas-gen:
     msdf-atlas-gen -font Font.ttf -type msdf -size 32 \
       -charset charset.txt -imageout atlas.png -json metrics.json

  2. Run this script:
     python3 tools/gen_msdf_header.py \
       --atlas atlas.png --metrics metrics.json \
       --name mono --output src/render/msdf_mono_data.h

The output is a self-contained C header with:
  - Atlas pixel data as static const uint8_t[] (RGB, 3 bytes/pixel)
  - Glyph metrics as static const struct[] (UV coords, advance, bearing)
  - Atlas dimensions and glyph count constants

Requires: Pillow (pip install Pillow)
"""

import argparse
import json
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow required. Install: pip install Pillow", file=sys.stderr)
    sys.exit(1)


def load_atlas(path: str) -> tuple:
    """Load atlas PNG, return (width, height, rgb_bytes)."""
    img = Image.open(path).convert("RGB")
    w, h = img.size
    pixels = img.tobytes()  # RGB, 3 bytes per pixel
    return w, h, pixels


def load_metrics(path: str) -> dict:
    """Load msdf-atlas-gen JSON metrics."""
    with open(path) as f:
        return json.load(f)


def c_array(data: bytes, name: str, per_line: int = 16) -> str:
    """Format bytes as a C array initializer."""
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")
    return "\n".join(lines)


def gen_header(atlas_path: str, metrics_path: str, name: str) -> str:
    """Generate the complete C header string."""
    w, h, pixels = load_atlas(atlas_path)
    metrics = load_metrics(metrics_path)

    guard = f"TIME_MSDF_{name.upper()}_DATA_H"
    prefix = f"msdf_{name}"

    # Extract glyph data from metrics
    atlas_info = metrics.get("atlas", {})
    glyphs = metrics.get("glyphs", [])

    # Atlas dimensions from the JSON (or from image)
    atlas_w = atlas_info.get("width", w)
    atlas_h = atlas_info.get("height", h)
    atlas_size = atlas_info.get("size", 32)

    # Build glyph entries
    glyph_entries = []
    for g in sorted(glyphs, key=lambda x: x.get("unicode", 0)):
        unicode_val = g.get("unicode", 0)
        advance = g.get("advance", 0.0)

        # Plane bounds (glyph box in font units)
        pb = g.get("planeBounds", {})
        pl = pb.get("left", 0.0)
        pb_bottom = pb.get("bottom", 0.0)
        pr = pb.get("right", 0.0)
        pt = pb.get("top", 0.0)

        # Atlas bounds (UV in pixels)
        ab = g.get("atlasBounds", {})
        al = ab.get("left", 0.0)
        ab_bottom = ab.get("bottom", 0.0)
        ar = ab.get("right", 0.0)
        at_val = ab.get("top", 0.0)

        glyph_entries.append(
            f"    {{ {unicode_val}, {advance:.6f}f, "
            f"{{ {pl:.6f}f, {pb_bottom:.6f}f, {pr:.6f}f, {pt:.6f}f }}, "
            f"{{ {al:.6f}f, {ab_bottom:.6f}f, {ar:.6f}f, {at_val:.6f}f }} }},"
        )

    pixel_array = c_array(pixels, f"{prefix}_pixels")

    return f"""/* {prefix}_data.h -- Auto-generated MSDF atlas data.
 * Generated by tools/gen_msdf_header.py
 * Font: {name}
 * Atlas: {atlas_w}x{atlas_h}, {atlas_size}px MSDF
 * Glyphs: {len(glyphs)}
 *
 * DO NOT EDIT -- regenerate with gen_msdf_header.py */

#ifndef {guard}
#define {guard}

#include <stdint.h>

#define {prefix.upper()}_ATLAS_W    {atlas_w}
#define {prefix.upper()}_ATLAS_H    {atlas_h}
#define {prefix.upper()}_ATLAS_SIZE {atlas_size}
#define {prefix.upper()}_GLYPH_COUNT {len(glyphs)}
#define {prefix.upper()}_PIXEL_BYTES ({atlas_w} * {atlas_h} * 3)

/* Per-glyph metrics */
typedef struct {{
    float left, bottom, right, top;
}} {prefix}_bounds_t;

typedef struct {{
    int unicode;
    float advance;
    {prefix}_bounds_t plane;   /* glyph box in font units */
    {prefix}_bounds_t atlas;   /* UV bounds in atlas pixels */
}} {prefix}_glyph_t;

/* Glyph metrics table ({len(glyphs)} entries, sorted by unicode) */
static const {prefix}_glyph_t {prefix.upper()}_GLYPHS[{len(glyphs)}] = {{
{chr(10).join(glyph_entries)}
}};

/* Atlas pixel data (RGB, 3 bytes per pixel, {atlas_w}x{atlas_h} = {len(pixels)} bytes) */
static const uint8_t {prefix.upper()}_PIXELS[{len(pixels)}] = {{
{pixel_array}
}};

/* Lookup glyph by unicode codepoint. Returns NULL if not found. */
static inline const {prefix}_glyph_t *{prefix}_find(int unicode) {{
    /* Binary search (glyphs sorted by unicode) */
    int lo = 0, hi = {prefix.upper()}_GLYPH_COUNT - 1;
    while (lo <= hi) {{
        int mid = (lo + hi) / 2;
        if ({prefix.upper()}_GLYPHS[mid].unicode == unicode) return &{prefix.upper()}_GLYPHS[mid];
        if ({prefix.upper()}_GLYPHS[mid].unicode < unicode) lo = mid + 1;
        else hi = mid - 1;
    }}
    return (void *)0;
}}

#endif /* {guard} */
"""


def gen_charset_file(output: str):
    """Generate charset.txt for msdf-atlas-gen (Basic Latin + Latin-1 Supplement)."""
    codepoints = []
    # Basic Latin (U+0020 - U+007E)
    for cp in range(0x0020, 0x007F):
        codepoints.append(str(cp))
    # Latin-1 Supplement (U+00A0 - U+00FF)
    for cp in range(0x00A0, 0x0100):
        codepoints.append(str(cp))

    with open(output, "w") as f:
        f.write("\n".join(codepoints) + "\n")
    print(f"Wrote {len(codepoints)} codepoints to {output}")


def main():
    parser = argparse.ArgumentParser(description="Convert MSDF atlas to C header")
    sub = parser.add_subparsers(dest="command")

    # generate command
    gen = sub.add_parser("generate", help="Generate C header from atlas + metrics")
    gen.add_argument("--atlas", required=True, help="Path to atlas PNG")
    gen.add_argument("--metrics", required=True, help="Path to metrics JSON")
    gen.add_argument("--name", required=True, help="Font name (e.g., 'mono', 'sans')")
    gen.add_argument("--output", required=True, help="Output .h file path")

    # charset command
    cs = sub.add_parser("charset", help="Generate charset.txt for msdf-atlas-gen")
    cs.add_argument("--output", default="charset.txt", help="Output file")

    args = parser.parse_args()

    if args.command == "generate":
        header = gen_header(args.atlas, args.metrics, args.name)
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, "w") as f:
            f.write(header)
        print(f"Generated {args.output}")

    elif args.command == "charset":
        gen_charset_file(args.output)

    else:
        parser.print_help()
        # Also print quick-start guide
        print("\n--- Quick Start ---")
        print("1. Generate charset:  python3 tools/gen_msdf_header.py charset")
        print("2. Generate atlas:    msdf-atlas-gen -font Font.ttf -type msdf "
              "-size 32 -charset charset.txt -imageout atlas.png -json metrics.json")
        print("3. Generate header:   python3 tools/gen_msdf_header.py generate "
              "--atlas atlas.png --metrics metrics.json --name mono "
              "--output src/render/msdf_mono_data.h")


if __name__ == "__main__":
    main()
